### ISSUE TITLE
Custom directory on install doesn't allow changes

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#10]
NOTE this issue is from binary version of wallet and may not reflect current code
### Describe the issue
Issue Install 'custom directory' doesn't allow custom location
### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
Install wallet from binaries

### Expected behavior
Clicking 'use a custom data directory' should activate directory field and allow user to specify location in the field

### Actual behavior
Field changes from greyed out to black, but actual location can't be changed by user

### What version of Veil wallet are you using?
Testing binary builds Windows (64) and Linux (64)

**Comment by furszy** [comment]
done. convert-gui-to-png branch
