### ISSUE TITLE
Wrong warning showed to user when encrypting wallet?

### ISSUE THREAD

**Issue by us77ipis** [Veil-Project/veil#1000]
### Description
If I understood correctly our recent discussion on discord, the warning that is shown to the user when encrypting a wallet *If you encrypt your wallet and lose your passphrase, you will LOSE ALL OF YOUR Veil!* is wrong, since you can always recover everything using the seed words that you backed up during wallet creation.

### Expected behavior
No misleading warning, that might lead the user to think he is doing something wrong when encrypting his wallet.

### Actual behavior
![screenshot](https://i.ibb.co/0qZPF7B/Screenshot-from-2022-04-22-14-52-10.png)

### Wallet version
Current `master` branch

**Comment by ohcee** [comment]
I changed the warning so it does not seem so doom and gloom for encrypting your wallet.
![issue#1000](https://user-images.githubusercontent.com/46406370/212175479-911bfbaf-0f64-4f59-a18d-359ecf7c926a.png)

**Comment by seanPhill** [comment]
Thanks! Elsewhere I am sure that users are told they can always restore their coins with the seed words, (although it can be a lot more work to do so than with a Bitcoin wallet), but it is good to fix it here. Next update I will check that we have that fixed, if you haven't already made a PR for it.

**Comment by seanPhill** [comment]
Done. :) Just hope that everyone does not lose their passphrase, as well as does not lose their seed phrase.
