### ISSUE TITLE
Zerocoin not shown in Coin Control. Is this intended?

### ISSUE THREAD

**Issue by ianGre** [Veil-Project/veil#101]
Someone asks me to send them Zerocoin, but Coin Control doesn't show any Zerocoins. I know i have them, from the total showing in the wallet.

Is this as intended and is there some other way to spend zero coins or is this a bug?

**Comment by ianGre** [comment]
I've been told that Zerocoins will be selected automatically, but that zero coins will be added to coin Control in the future.

**Comment by 4x13** [comment]
Moved to new issue
