### ISSUE TITLE
Copy Receiving address doesn't work

### ISSUE THREAD

**Issue by MisterKangaroo** [Veil-Project/veil#102]
Copying receiving adress doesnt work anymore.
Not in the receive tab nor under the QR code.
When clicking the "copy to clipboard"-button it shows "Adress copied" but the clipboard remains empty.

Win 10 x64, testnet 9

**Comment by MisterKangaroo** [comment]
Works with a fresh wallet.dat

**Comment by MisterKangaroo** [comment]
After a while it stopped working again (under QR code and in receive tab) like described above...
(it works in the adress book section)
![notworking](https://user-images.githubusercontent.com/43561981/50553436-ec4bb600-0ca6-11e9-975f-e46849cd3104.PNG)

**Comment by StrontiumZ38** [comment]
Experienced same problem. Windows 7 64

**Comment by ianGre** [comment]
Which OS is the original problem in? My macOS wallet copies the address from both places fine.

tps1qqptcjm0dcstjhshv9xha7wrq9gt4udtlxspydznegmdqkerl4838xgpq2sdwdhrls43zekj9fv8ed76ugw8daaetk9vggrw3492z89vra7y7qqq8zglzq

tps1qqp22ql9md2h6q2zu9ygf9pvs3g25dl8z0hppkh2uazz2tscrukce9spqg9tjrm9tg5p9eflrhtkpqw2ty262xlsm7pr7l2x34sk6tl3lpau5qqqe6t909

**Comment by MisterKangaroo** [comment]
Windows 10 x64 @ianGre

**Comment by ianGre** [comment]
Oh, that's right. I remember a conversation about the way that Windows clipboard copies in RTF and pasting it outside the VM was not possible, unless I first pasted into Notepad and then copied and pasted it again, so it was in plaintext. But you mentioned that this was not so in your case.

**Comment by 4x13** [comment]
Can someone check the testnet-13 release

**Comment by MisterKangaroo** [comment]
I checked...
It copies the stealth address but in the shortened version that displays... (xxxxxxxx...xxxxxx).
So it can't be pasted in the send tab, cause the send tab doesn't recognize a legit address.

**Comment by ianGre** [comment]
![screen shot 2019-01-02 at 1 25 50 pm](https://user-images.githubusercontent.com/36124423/50580539-cdfed980-0ea3-11e9-91d0-d6d911b56796.png)
This was after encrypting the wallet in testnet-13. Previously the first receiving address was down there. Also, yes, the only time the complete address could be copied was when you created it. Otherwise it displays _and copies_ like Kanga described.

**Comment by ianGre** [comment]
Oh! I just remembered! This was when the encrypted wallet was LOCKED.

Maybe there should be a tooltip to tell people that they need to UNLOCK the wallet to reveal this address???

**Comment by StrontiumZ38** [comment]
tps1qqp4er3jufn2nj57hk2zrmzt2uw9ee643x27dex0v6farhctqnceqvspq0lqh936km4ltszjdmsuh5s9rfeqs68vpfzx4dduvv3lsemq5qw3qqqqn83xaf
from 
![image](https://user-images.githubusercontent.com/38264865/50580613-f7176e00-0e93-11e9-8023-778c3fb79246.png)
Working fine for me as long as address is visible.

**Comment by MisterKangaroo** [comment]
Mine was unlocked and this address under the wrong code worked... While the ones in the address book copied in the shortened version like described above

**Comment by StrontiumZ38** [comment]
Ah yes. The address book shortens for me also,

**Comment by MisterKangaroo** [comment]
Still copies the shortened version of the adress in 1.0.0.3

**Comment by StrontiumZ38** [comment]
This can be closed now @4x13

**Comment by MisterKangaroo** [comment]
works now
