### ISSUE TITLE
Address book contact overprinting (GUI)

### ISSUE THREAD

**Issue by MisterKangaroo** [Veil-Project/veil#103]
When i save a stealth adress with name in Adressbook -> Contacts...
the adress and the name are rendered at the same vertical position.

Win10 x64
1920x1080px res
standard wallet size

![stealthaddress](https://user-images.githubusercontent.com/43561981/50553606-5580f880-0caa-11e9-869f-69ab408bb415.PNG)

**Comment by 4x13** [comment]
fixed
