### ISSUE TITLE
veil.tools hyperlink in wallet "looks like your new here" not working. 

### ISSUE THREAD

**Issue by ohcee** [Veil-Project/veil#1032]
The link to *veil.tools* doesn't take you to the website. It's broken and doesn't do anything when clicked. 
![Screenshot 2023-05-15 at 8 46 58 PM](https://github.com/Veil-Project/veil/assets/46406370/3e38f8ff-14cb-48ae-abc4-37a7fa12daa4)
![Screenshot 2023-05-15 at 8 47 34 PM](https://github.com/Veil-Project/veil/assets/46406370/470d05f1-233a-43ba-b732-b27af088bc3e)

**Comment by seanPhill** [comment]
I've started a fresh wallet to test this, and yes, nothing happens if clicked, but if selected, copied, and pasted it does open correctly in a browser. (I will still see about fixing this though.)

**Comment by seanPhill** [comment]
Tried some suggested properties changes to the QLabel class widget, like this (originally just the last listed property):
```
                    <property name="textFormat">
                        <enum>Qt::RichText</enum>
                    </property>
                    <property name="textInteractionFlags">
                        <set>Qt::TextBrowserInteraction</set>
                    </property>
                    <property name="text">
```
But it didn't make the URL a hyperlink. (Anyone) Check my branch if you have any suggestions.
(Note, this edit did not fix it!)
https://github.com/seanPhill/veil/tree/Fix-veil.tools-link-on-empty-overview-page
