### ISSUE TITLE
Address contact info - no limit on entry name so conflicts with address.

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#104]
### Describe the issue
Looking at Mister Kangaroos issue made me test something in a similar vein. Contact name and address in address book can clash if the name is exceptionally long.

#### Can you recreate the problem
Yes
#### If so, please list the steps to reproduce below:

Run wallet. Enter Send, contacts, create a contact with a very long name.

### Expected behavior
The contact name and address should remain distinct and legible.

### Actual behavior
Exceptionally long names will reach the address and make both illegible. A limit should be placed on how long a contact name can be in characters.

### What version of Veil wallet are you using?
Testing binary builds Windows (64) (testing version 10)

![image](https://user-images.githubusercontent.com/38264865/50553966-38bde280-0cf5-11e9-9319-3ce078af0a33.png)

**Comment by presstab** [comment]
@4x13 Why is this high priority? This is something that would rarely impact anyone using the wallet normally, and causes no actual change in usefulness other than being ugly.

**Comment by StrontiumZ38** [comment]
Looks to have been changed 
![image](https://user-images.githubusercontent.com/38264865/50625030-89894180-0f68-11e9-96fa-4443cac4f1d1.png)
