### ISSUE TITLE
Bitcoin logo and name featured on binary install

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#11]
NOTE this issue is from binary version of wallet and may not reflect current code
### Describe the issue
Issue Install splash features Bitcoin logo rather than Veil
### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
Open binaries to attempt install

### Expected behavior
The wallet install wizard should feature Veil graphics and brand name

### Actual behavior
The wallet install wizard features Bitcoin logo and branding in copy

### What version of Veil wallet are you using?
Testing binary builds Windows (64)

**Comment by veildev** [comment]
screenshot please.

**Comment by veildev** [comment]
check branch `gui-fixes` and close the issue if it's solved please.
