### ISSUE TITLE
3.) Coin Control needs to be functional

### ISSUE THREAD

**Issue by 4x13** [Veil-Project/veil#111]
Coin Control (doesn’t work, no calcs, nothing brought forward to send tab, no zerocoin)

if users can’t send basecoin to ringct, these will need to be controlled some how in coin control. 

the issues I see is that presently miners mine to basecoin address (mining addresses)

**Comment by 4x13** [comment]
Looks like calcs are functioning for allowing u to choose basecoin but nothing is brought forward to the send tab as expected.

**Comment by presstab** [comment]
#233
