### ISSUE TITLE
6.) Add public Hardcoded nodes for Mainnet

### ISSUE THREAD

**Issue by 4x13** [Veil-Project/veil#115]
Add hard coded IP’s for Mainnet public servers/nodes.

	116.203.43.112
	159.69.20.168
	94.130.180.117
	94.130.185.98
	195.201.24.97
	116.203.40.38
	195.201.24.15
	195.201.24.37

**Comment by presstab** [comment]
They are all now hardcoded in as veilseed.presstab.pw which is connected to by the client. If we want to create pnseeds, and have it compiled in, we could do that later. This does the trick for now.
