### ISSUE TITLE
Bitcoin network mentioned instead of Veil

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#12]
NOTE this issue is from binary version of wallet and may not reflect current code
### Describe the issue
Issue Bitcoin network mentioned instead of Veil when searching for network
### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
Run wallet and proceed past enter password

### Expected behavior
Opening wallet beyond password setup gives sync dialogue mentioning Veil network in pop-up when clicking 'connecting to peers' text

### Actual behavior
Opening pop-up dialogue discussing syncing mentions Bitcoin network and not Veil network

### What version of Veil wallet are you using?
Testing binary builds Windows (64) and Linux (64)

**Comment by 4x13** [comment]
need to re-verify with recent update

**Comment by StrontiumZ38** [comment]
This appears to be fixed
![image](https://user-images.githubusercontent.com/38264865/50543922-12327580-0c29-11e9-9ff1-e82d4c7c310e.png)
