### ISSUE TITLE
Button text cuts off for some users

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#13]
NOTE this issue is from binary version of wallet and may not reflect current code
### Describe the issue
Issue Bitcoin network mentioned instead of Veil when searching for network
### Can you reliably reproduce the issue?
Not me personally, but users can and shared screen. I cannot recreate at various resolutions on my monitor and versions.
#### If so, please list the steps to reproduce below:
Run wallet and proceed past enter password to main 'Time to transfer some Veil' screen

### Expected behavior
Button text on central buttons in main area fit to button saying 'Learn more about Veil'

### Actual behavior
Button dialogue is cut off at the first L and last L creating 'earn more about Vei' copy

### What version of Veil wallet are you using?
Testing binary build X

**Comment by veildev** [comment]
Button not on the wallet anymore, closing this.
