### ISSUE TITLE
FAQs pop-up window lacking [X] button

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#14]
NOTE this issue is from binary version of wallet and may not reflect current code
### Describe the issue
FAQs window once uponed lacks an X button to close it on some OSs
### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
Run wallet and proceed past enter password
Click the button to read about Veil 

### Expected behavior
The FAQs pop-up window should feature an X to close FAQs window and return to main application window upon clicking

### Actual behavior
Linux and Windows versions of the wallet lack the X button, forcing users to click the window active, then press escape key to close it

### What version of Veil wallet are you using?
Testing binary builds Windows (64) and Linux (64)

**Comment by ianGre** [comment]
I'm running the Linux veil wallet in an Ubuntu VM built by Veil-testenv with Vagrant (on Github, by Marsmensch) and the [x] exit button **does** show up in the top right hand corner, and correctly exits the FAQ page **if** the VM window has been resized sufficiently. I have not tried this on a physical Linux PC, but I would expect Display size would be a factor.

**Comment by StrontiumZ38** [comment]
This seems to be solved with complete binary test release, so closing issue.
