### ISSUE TITLE
Receiving address cropped on wallet bottom left

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#140]
### Describe the issue
The address shown on bottom of the leftmost panel of the wallet is cut off due to being too long

#### Can you recreate the problem
Yes
#### If so, please list the steps to reproduce below:

Run wallet. Look to bottom left of wallet
![image](https://user-images.githubusercontent.com/38264865/50576803-1d6de700-0e5d-11e9-81c1-c11e1353cfc9.png)

### Expected behavior
The address should be complete and legible.

### Actual behavior
The address is cropped at the end due to insufficient room.

### What version of Veil wallet are you using?
Testing binary builds Windows (64)

**Comment by 4x13** [comment]
should be fixed in next release

**Comment by 4x13** [comment]
fixed
