### ISSUE TITLE
Adding new address in contact book no longer displays address/name

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#143]
### Describe the issue
Adding address to address book no longer displays address (different to #122 I believe)

#### Can you recreate the problem
Yes
#### If so, please list the steps to reproduce below:

Run wallet. Enter contacts tab, add address.

### Expected behavior
The address name and address should be displayed.

### Actual behavior
No visual changes outside of the 'address created' message.
![image](https://user-images.githubusercontent.com/38264865/50576834-c583b000-0e5d-11e9-8440-7e7c6faf12c1.png)

![image](https://user-images.githubusercontent.com/38264865/50576831-b7359400-0e5d-11e9-9ae6-4de21921dad4.png)

### What version of Veil wallet are you using?
Testing binary builds Windows (64)

**Comment by 4x13** [comment]
Should be fixed in next release

**Comment by 4x13** [comment]
fixed
