### ISSUE TITLE
Add select Address Book entries from Send tab

### ISSUE THREAD

**Issue by 4x13** [Veil-Project/veil#147]

**Comment by StrontiumZ38** [comment]
If one has contacts in address book for recipients
![image](https://user-images.githubusercontent.com/38264865/50665252-445e2180-0ff3-11e9-96a8-f43bf5b876c6.png)
There is no way on the send tab to pull in that address directly
![image](https://user-images.githubusercontent.com/38264865/50665294-6657a400-0ff3-11e9-9851-70eb170b2bfb.png)
The add recipient simply opens a new blank entry for user to fill. The user cannot select a recipient from their address book, but instead would have to first go to address book and copy address, then paste into send tab, creating a lot of extra work.
