### ISSUE TITLE
When doing zerocoin spends, we need a visual indicator of the spend progress

### ISSUE THREAD

**Issue by 4x13** [Veil-Project/veil#149]

**Comment by StrontiumZ38** [comment]
This continues to be a cause for much fuss and hot topic in support channel.

**Comment by presstab** [comment]
Bounty: 750

**Comment by veilgets** [comment]
Developer: MatWaller

**Comment by MatWaller** [comment]
Did anyone have anything in mind for where they would like this visual indicator to be placed?

**Comment by Rock-N-Troll** [comment]
The wallet is single threaded for spends and the action occurs from the GUI spend screen. The wallet also tends to freeze up while waiting for the zerocoin spend process to complete.

I think for these reasons it should probably be in the send confirmation popup.

**Comment by codeofalltrades** [comment]
Closing.
Zerocoins will be removed in a future release.
