### ISSUE TITLE
Staking message 'miner'

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#15]
NOTE this issue is from binary version of wallet and may not reflect current code
### Describe the issue
The wallet informs user that 'miner started' and  'miner stopped' when staking is enabled/disabled
### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
Run wallet beyond first run

### Expected behavior
Opening the wallet with staking active, as well as clicking to enabled/disable staking should refer to the process as 'staking active' and 'staking disabled'

### Actual behavior
Opening the wallet and clicking the staking button results in 'miner started' and 'miner stopped' messages

### What version of Veil wallet are you using?
Testing binary builds Windows (64) and Linux (64)

**Comment by MisterKangaroo** [comment]
persists in actual version (testnet 3)

**Comment by 4x13** [comment]
fixed
