### ISSUE TITLE
4.) Multi-block Zerocoin Spend transaction issue

### ISSUE THREAD

**Issue by 4x13** [Veil-Project/veil#151]
[debug-multi-block-spend-issue.log](https://github.com/Veil-Project/veil/files/2719997/debug-multi-block-spend-issue.log)

**Comment by 4x13** [comment]
Issue is that I sent 35 (10 zerocoin) denoms which should have been spread over 2 blocks. first set of 200 showed up but second set of 15 did not, log shows mempool issue.

first tx.

https://testnet.veil-project.com/block/6bc01582c884a4ebb2b6e27de6aa3f9e8fbc35ee885aa8b215ba5699de9b9c18

**Comment by presstab** [comment]
I have no issue with this functionality. There is no guarantee that both transactions can get into a block.
