### ISSUE TITLE
8.) Wallet coin totals are not added properly for total balance

### ISSUE THREAD

**Issue by 4x13** [Veil-Project/veil#155]

**Comment by StrontiumZ38** [comment]
@presstab @veildev  big progress here, however there still looks to be some issues.
![image](https://user-images.githubusercontent.com/38264865/50733978-78e00200-11da-11e9-9378-c66dd63b31f1.png)
Balance total seems to calculate all spendable coins, and in that case is working fine on the overview base level. However, clicking the ? for a breakdown changes the story, and doesn't give appropriate info. Info in the console also doens't match the ? display.
![image](https://user-images.githubusercontent.com/38264865/50734009-14717280-11db-11e9-88d1-6b16b3703f45.png)
Overview reward transaction details seem fixed, no longer adding the additional 20 to reward.
![image](https://user-images.githubusercontent.com/38264865/50734014-2c48f680-11db-11e9-8b9a-caac41fd7fdc.png)
However minting transaction details still seem off, as seen above an automint shows an amount of '20'
![image](https://user-images.githubusercontent.com/38264865/50734031-821d9e80-11db-11e9-8011-51ac1ec5a779.png)
And here my manual mint of 40 zerocoin also shows 20 (though with 0.4 reflecting fee as a tell).

**Comment by presstab** [comment]
#219
