### ISSUE TITLE
minted zerocoins are not showing up in some users wallets

### ISSUE THREAD

**Issue by veilgets** [Veil-Project/veil#166]

**Comment by veilgets** [comment]
might have to do with zerocoin mints not confirming, that seems to be happening often

**Comment by presstab** [comment]
Need some type of description of exact steps to reproduce this, or transaction logs or something, or will have to close this issue.

**Comment by StrontiumZ38** [comment]
Sounds like a good part of this problem could be fixed with a notification that zerocoins take some time to mature/be available and display, or am I missing something?

**Comment by presstab** [comment]
The not displaying issue is fixed in 325d7c12ac6856acdb9fd3198ca36a3db469ac31
