### ISSUE TITLE
wallet crashing/freezing when spending zerocoin

### ISSUE THREAD

**Issue by veilgets** [Veil-Project/veil#167]

**Comment by StrontiumZ38** [comment]
Shouldn't be crashing, just becoming unresponsive for a while. Waiting it out resolves it.

**Comment by dxxcoin** [comment]
wallet freezes when sending coins
debug.log
https://dropmefiles.com/D5Uzr

**Comment by StrontiumZ38** [comment]
This should be solved and only result in errors rather than crashing. @4x13

**Comment by presstab** [comment]
#219
