### ISSUE TITLE
change to hex values in console text.

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#173]
This is to change the colour of particular text in the console to better stand out from the surrounding grey text and be easier to distinguish for users (particularly those who are colour-blind) I've included images of the hex colour values as well as code I believe would fix it. Not making pull request as been asked to avoid at a time like this.

![image](https://user-images.githubusercontent.com/38264865/50683280-d9453700-1054-11e9-8d2c-4fdc8f46add7.png)

**Comment by veildev** [comment]
Follow the brand color palette and create a PR when it's done. No need to create an issue for this.
