### ISSUE TITLE
Version not being updated with releases

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#175]
**Explain issue**
Version not being updated with releases of wallet.
https://github.com/Veil-Project/veil/blob/master/configure.ac#L6
**Can this be recreated?**
Yes
**Expected behaviour**
New releases should increase version number incrementally
**Actual behaviour**
All releases have carried the same version info as per source line linked above

**Comment by presstab** [comment]
master branch does not get updated, only the release branch. We will set it to end in 99 as is typical for handling of this.
