### ISSUE TITLE
1.0.0.5 issues spending: A

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#176]
### Describe the issue
Can no longer spend veil to self on testnet. Met with errors

#### Can you recreate the problem
Yes
#### If so, please list the steps to reproduce below:

Run wallet. Go to spend tab. Input wallet address and send veil to self.

### Expected behavior
Coins should be spent to address and arrive ready to be minted.

### Actual behavior
Met with mistaken error on balance to stealth address.
![image](https://user-images.githubusercontent.com/38264865/50685937-ab64f000-105e-11e9-9681-1db9e22b9c56.png)

Met with invalid entry message to basecoin address
![image](https://user-images.githubusercontent.com/38264865/50685912-9720f300-105e-11e9-8674-79d9aab253f9.png)

### What version of Veil wallet are you using?
Live windows 64 1.0.0.5

**Comment by StrontiumZ38** [comment]
**UPDATE**
@presstab  I'm now able to send only in multiples of 10 on testnet. Trying non-multiples (such as 15) ends in 'the amount exceeds your balance' (see image below)
![image](https://user-images.githubusercontent.com/38264865/50734112-d5442100-11dc-11e9-9d12-141622c35221.png)
![image](https://user-images.githubusercontent.com/38264865/50734116-e3923d00-11dc-11e9-93e5-abdd4930436d.png)
Sending myself veil in multiples of 10 to test stealth address seems to work fine but carries a huge fee being included in the spend (see below).
![image](https://user-images.githubusercontent.com/38264865/50734123-22c08e00-11dd-11e9-854a-22a15f3bae2f.png)

**Comment by ianGre** [comment]
[testnet] (Current wallet builds 1.0.0.6 on Mac and Windows)
I got the same "The amount exceeds your balance" when sending one Veil from my Mac wallet to my Windows wallet. I cancelled out of the spend window and do not find the transaction in the transaction list, and would not have expected it, had I not **coincidentally** received one Veil in my Windows wallet!!

At least it SAID it was a 1 Veil incoming transaction! (Maybe you will need the raw transaction data that is also found on the testnet block explorer?) And the balance increased! But the [testnet]  block explorer says the amount is zero.

Txid: 4368e4a88ad70f7006183f1bf45c3fdfa0eca15b61cc377cecda35672bbeb896

https://testnet.veil-project.com/tx/4368e4a88ad70f7006183f1bf45c3fdfa0eca15b61cc377cecda35672bbeb896

```
Mined Time            Sun, 06 Jan 2019 23:10:32 UTC
In Block                  fa769395ef6ee894e2d2e25cbfe8131ce84be2bec5668ec8eaf34746dddda923
In Block Height       3515
Total Input              0 tVeil
Total Output           0 tVeil
Fees                        0 tVeil



➡ No Inputs (Newly Generated Coins)
--

> Rangeproof
 --
(middle-truncated address)               Hidden Amount
(middle-truncated address)               Hidden Amount
(middle-truncated address)               Hidden Amount

Fee: 0 tVeil                                           48 Confirmations                   0 tVeil

**Comment by presstab** [comment]
#219 Fixes the issues with the logic for sending coins on the GUI screen.
