### ISSUE TITLE
1.0.0.5 losing track of zerocoins when wallet restored via either method.

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#179]
People losing zerocoin balance from both GUI and getzerocoinbalance when restoring from both seed and wallet.dat

I assume these are not completely lost, but certainly worrying users.

**Comment by 4x13** [comment]
when restoring from seed, they will definitely need to run searchdeterministiczerocoin 0 5000 2

5000 is how many far they want to go back in the chain, make sure it is the chain tip
