### ISSUE TITLE
Auto-minting right above 10

### ISSUE THREAD

**Issue by Tris10w** [Veil-Project/veil#180]
Auto-minting seems to work well when base coins is much higher. I've noticed around 10-10.5ish area, auto-mint is not launching.

Expected the auto mint to factor in the fee and the current base coin and mint. 10.3 base coin should be enough. ( going to test with 11 and see if this makes a difference)

Yes. load wallet with 10ish base coins and have minting enabled at 10.

This occurred in .3 .4 and .5

Windows 10 

Could the AutoZeromint method attach the variables being calculated? such as the base coin amount and the available coin amount method ? Might make this a little easier to debug :)

**Comment by enervey** [comment]
My automint isn't working either, so I just manually mint occasionally. 

![image](https://user-images.githubusercontent.com/17502298/50693431-ed614800-1004-11e9-9047-f9b01b9ada72.png)

![image](https://user-images.githubusercontent.com/17502298/50693473-0964e980-1005-11e9-9084-fa2eccfc6a52.png)

**Comment by ianGre** [comment]
This point where autominting is not starting would be the zero coin denomination minimum of 10 Veil, _plus_ the calculated fee. There is a bug (still) where the wallet calculates the fee much higher than what actually can be seen in the block explorer. For example, Fee looks like it will be 0.1, but is actually 0.01 (one thousandth of the 10 Veil zero coin being minted). Because the wallet 'thinks' the fee is 0.1 (or 0.3 or whatever) it will not automint yet. The happens with a spend. It thinks you don't have enough for the fee, even though you do. 

I recommend that (aside from the fee miscalculation being fixed - obviously - that the "convertible to zerocoin" amount shown in the wallet be calculated to account for the fee, and only showing a multiple of ten. Maybe two convertible amounts need to be displayed? One from RingCT balance and one from Basecoin!

**Comment by ianGre** [comment]
@enervey Automint also takes time, as does manual minting, how long have you waited for autominting?

**Comment by Tris10w** [comment]
> This point where autominting is not starting would be the zero coin denomination minimum of 10 Veil, _plus_ the calculated fee. There is a bug (still) where the wallet calculates the fee much higher than what actually can be seen in the block explorer. For example, Fee looks like it will be 0.1, but is actually 0.01 (one thousandth of the 10 Veil zero coin being minted). Because the wallet 'thinks' the fee is 0.1 (or 0.3 or whatever) it will not automint yet. The happens with a spend. It thinks you don't have enough for the fee, even though you do.
> 
> I recommend that (aside from the fee miscalculation being fixed - obviously - that the "convertible to zerocoin" amount shown in the wallet be calculated to account for the fee, and only showing a multiple of ten. Maybe two convertible amounts need to be displayed? One from RingCT balance and one from Basecoin!

Even so, wouldn't a base coin count of 13 satisfy the fee? I agree there's a bug with the fee, but seems there's something else involved.

I've let it run for a good amount of time and it did not pull the trigger. Auto-minting a higher value of base coins worked without a hinge. It would wait until the previous mint was fully completed and confirmed, but it still went sequentially. 

Manual fires immediately and processes as one would intend depending on the network.

**Comment by ianGre** [comment]
```base coin count of 13 satisfy the fee? ```
Yes it would, to mint one 10 Veil zerocoin, but people have been complaining about the remaining three Veil not being minted, when the minimum denomination is ten.

**Comment by Tris10w** [comment]
> Yes it would, to mint one 10 Veil zerocoin, but people have been complaining about the remaining three Veil not being minted, when the minimum denomination is ten.

This thread is about it not minting one 10. the 3 is considered change :)

**Comment by ianGre** [comment]
True, but I need to generalise the problem, so that it will be fixed for people with 10.05 Veil also, who have enough for the real fee, but not enough for the wrongly calculated fee.

**Comment by enervey** [comment]
Here are the most recent log entries right before the daemon crashed again for me:

![image](https://user-images.githubusercontent.com/17502298/50712235-bb6cd780-103e-11e9-8df7-0fa7196440a7.png)

**Comment by presstab** [comment]
Can confirm that I see a problem with automint. For some reason, it is not correctly getting the available balance. For example I have 50 or so basecoins, and it is only recognizing 9 of them when looking at automint. I am guessing this is the primary problem people are seeing.

**Comment by presstab** [comment]
#219 fixes balance errors that were causing this specific issue with autominting.
