### ISSUE TITLE
Veil wallet not synchronising

### ISSUE THREAD

**Issue by ghost** [Veil-Project/veil#181]
Veil wallet not synchronising
[debug.log](https://github.com/Veil-Project/veil/files/2727119/debug.log)

full blockchain sync

no connection to peers
![capture](https://user-images.githubusercontent.com/46376064/50690230-d898aa80-102c-11e9-834e-d92144582ee9.JPG)
see debug 

every time i open it

v1.0.0.4-a20cc0114

intel i3, ssd 240

see attached

see atatched

**Comment by ianGre** [comment]
There is a new wallet released, please load 1.0.0.5 (or wait for 1.0.0.6)

Mine synced fine on a commit above 1.0.0.5

(I think the "1.0.0.2" below is a typo (right below 5 on a numeric keypad) will report separately. The e9bfd4e75 will identify it.) 


Veil Core version v1.0.0.2-e9bfd4e75 (64-bit)

**Comment by presstab** [comment]
Try starting with the `-resync` flag and also using `clearbanned` command in the console to make sure you can connect to peers.

**Comment by pkecpecp** [comment]
Thank you it is fixed!!!!
