### ISSUE TITLE
Wallet losing transaction history (Windows, 1.0.0.5)

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#191]
**Describe the issue**
Wallet with balance has no transaction history
**Can you recreate the issue?**
Not dependably, but it appears to be from restarting wallet - possibly with forced resync
I've experienced this on tesnet, and a user just shared an image of it from mainnet
![image](https://user-images.githubusercontent.com/38264865/50719086-acd3fe00-10da-11e9-8ca1-9b8ad84e98ed.png)
**Version**
Windows 64,

**Comment by 4x13** [comment]
did you try rescanblockchain??

**Comment by veildev** [comment]
The GUI is showing every transaction that is returned in the method `getWalletTxs` of the wallet class. It's not a GUI issue.

**Comment by StrontiumZ38** [comment]
No longer seeing this issue across many attempts. Closing
