### ISSUE TITLE
Mining able to win more than 5 straight blocks before staking can with staking active 1.0.0.5

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#192]
**Explain issue**
The system is supposed to disallow PoW finding more than 5 consecutive blocks. It's shown that this is not the case.
**Can you recreate this issue?**
Not by choice, but it's happening on the active chains (main and test), though more apparent on testnet due to difficulty balance.
**What should happen?**
The 6th block should be forced into a PoS stake reward rather than a 6th PoW mining reward.
**What actually happens?**
![image](https://user-images.githubusercontent.com/38264865/50720941-5bd40200-10fa-11e9-9cde-0e92d95fa0b4.png)
**Release version**
1.0.0.5

**Comment by 4x13** [comment]
I already said it does not go into effect until block 15000
