### ISSUE TITLE
Restarting wallet resets automint denomination.

### ISSUE THREAD

**Issue by veilgets** [Veil-Project/veil#197]
gui doesn’t save automint denomination choice upon restart.

**Comment by ianGre** [comment]
CONFIRMED! (In wallet built 11 commits after 1.0.0.5)

**Comment by veildev** [comment]
@veilgets GUI doesn't store anything.

**Comment by veilgets** [comment]
@veildev ok, is it something we can add?

**Comment by StrontiumZ38** [comment]
Related to #361

**Comment by furszy** [comment]
#372 done.
