### ISSUE TITLE
Wallet tries to add loose coinstake transactions to mempool

### ISSUE THREAD

**Issue by presstab** [Veil-Project/veil#199]
`2019-01-05T18:45:03Z ERROR: AcceptToMemoryPoolWithTime: failed to accept tx to mempool: coinstake`

Loose coinstake transactions never need to be added to mempool. Need an exclusion added somewhere.

**Comment by Zirillian** [comment]
This might be the error that keeps my wallet from opening? I submitted debug log to #178  also
[debug.log](https://github.com/Veil-Project/veil/files/2729980/debug.log)

**Comment by StrontiumZ38** [comment]
@presstab any chance this is what's contributing to crashing? I see this is low priority at the moment, but it seems to be present in a lot of debug logs I'm getting. Not sure if that's a symptom or coincidence though.

**Comment by presstab** [comment]
#219
