### ISSUE TITLE
Crash during syncing 1.0.0.5

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#201]
Experienced a different kind of crash to usual while syncing. Result was non-responsive program with accompanying error message window.

![image](https://user-images.githubusercontent.com/38264865/50731200-c0966780-11a1-11e9-8437-2a12bb37d076.png)

**Windows (64) error report**

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	veil-qt.exe
  Application Version:	1.0.0.5
  Application Timestamp:	00000000
  Fault Module Name:	veil-qt.exe
  Fault Module Version:	1.0.0.5
  Fault Module Timestamp:	00000000
  Exception Code:	40000015
  Exception Offset:	000000000153f234
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	3081
  Additional Information 1:	304e
  Additional Information 2:	304e6160638bb0733a6ad6493d9d68b8
  Additional Information 3:	6273
  Additional Information 4:	627324e82c27fefcc4ecb74d42cc0eb8

**Log snippet**

[crash.txt](https://github.com/Veil-Project/veil/files/2730056/crash.txt)

**System, version**

Windows (64), 1.0.0.5

**Comment by presstab** [comment]
Somewhere there is a `map::at` error. This is very hard to track down.

**Comment by StrontiumZ38** [comment]
I've been unable to recreate this error. @presstab do you want this closed, or leave it in anticipation of it happening again?

**Comment by StrontiumZ38** [comment]
Closing as I've neither experienced or had reports of this since.
