### ISSUE TITLE
Feature request: Balance breakdown to remain visible until I move the mouse away.

### ISSUE THREAD

**Issue by ianGre** [Veil-Project/veil#202]
Clicking the (?) next to Total Balance reveals the Zerocoin, RingCT and Basecoin breakdown.

**I wish that** it would remain until I move the mouse away, or have some other way of being viewed. It is very annoying to continually have to relaunch that little bit of information while contemplating how much is in each category.  

Veil macOS wallet v1.0.0.5 self-compiled.

This is a feature request.

**Comment by ianGre** [comment]
If I could tag this as low priority I would.

**Comment by StrontiumZ38** [comment]
Without looking at the code, it seems to be on a 5 second timer. @ianGre can you confirm this is still an issue on Mac?

**Comment by seanPhill** [comment]
It's about 5 seconds on both Mac and Linux.

**Comment by presstab** [comment]
Bounty Price: 156.25
Estimated Hours: 2.5

**Comment by veilgets** [comment]
Developer: drag0ng
