### ISSUE TITLE
Threads 0 on search deterministic zerocoin causes crash

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#203]
**Describe issue**
Using the 'searchdeterministiczerocoin x x x' command results in a crash if the final digit is set to 0 threads.

**Expected behaviour**
The input should fail rather than crash the wallet

**Actual behaviour**
The wallet crashes

**Comment by presstab** [comment]
c154ece5c1387940d4899345f4ff65aaccc8168e
