### ISSUE TITLE
Decryption crash. Assert crypter.cpp 207.

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#208]
**Explain issue**
The wallet gives an assertion error when launching using an existing wallet.dat after updating version. I experienced this with testnet wallet, and a user just shared the same. I was able to cancel out of the error and proceed as my testnet wallet was unencrypted at the time.
![image](https://user-images.githubusercontent.com/38264865/50735144-f3b21880-11ec-11e9-9662-77148165468e.png)
**Can you recreate the issue?**
Not reliably. My mainnet wallet worked fine. Other users have experienced this problem.

**Comment by presstab** [comment]
Reproduced this error. Found the cause. Working to fix it.
