### ISSUE TITLE
Buttons not visible on macOS wallet, branch convert-gui-png

### ISSUE THREAD

**Issue by ianGre** [Veil-Project/veil#21]
Branch: convert-gui-to-png
OS: macOS 10.13 High Sierra
Behaviour: This was fine when using SVG buttons, but in this branch the buttons are invisible. The buttons still work, but you cannot see them.

**Comment by veildev** [comment]
png is crap.. added png icons again. Pixelated but there.. check convert-gui-to-png branch.

Working on svg gitian support after this release rush.

**Comment by 4x13** [comment]
Should be resolved

**Comment by ianGre** [comment]
Yes, the later Mac wallet has no problem with button visibility.
