### ISSUE TITLE
Transaction history of basecoin to zerocoin mint shows about double the amount

### ISSUE THREAD

**Issue by ianGre** [Veil-Project/veil#210]
Using the self-built current master as of 1.0.0.6

On testnet, in the Qt GUI wallet

I _manually_ minted 1000 basecoin to 100 denomination zerocoin. In the Transaction Details of the wallet it displays:

```
ID: 417c2c7f76adb169c2c8f85b7818815d8fa18d4a674b079adc8daa953886e04a
Amount: 2000.01000000 VEIL
...
Fee: 0.01000000 VEIL
...
```

https://testnet.veil-project.com/tx/417c2c7f76adb169c2c8f85b7818815d8fa18d4a674b079adc8daa953886e04a

In the testnet block explorer it shows 

```
Transaction 417c2c7f76adb169c2c8f85b7818815d8fa18d4a674b079adc8daa953886e04a
Summary
Mined Time Sun, 06 Jan 2019 19:13:19 UTC
In Block 0b518f1f9857924ebc1055d3b22c18d8fe75d204997a70ba6ddef8dc602e7eb0
In Block Height 3285
Total Input 1019.97 tVeil
Total Output 1019.96 tVeil
Fees 0.01 tVeil
```

**Comment by ianGre** [comment]
The same thing happens with autominted denom ten zerocoins.
```
2019-01-06T15:41:27Z CreateZerocoinMintTransaction: new mint  DeterministicMint:
2019-01-06T15:41:27Z CommitTransaction:
2019-01-06T15:41:27Z [default wallet] AddToWallet d7af388a958e112104dd419edaa688cede90d490b46cb7111e7964fd149b7515  new
2019-01-06T15:41:27Z [default wallet] Relaying wtx d7af388a958e112104dd419edaa688cede90d490b46cb7111e7964fd149b7515
2019-01-06T15:41:27Z copied wallet.dat to /Users/xxxx/Library/Application Support/Veil/testnet3/backups/wallet-autozbackup-5.dat
2019-01-06T15:41:27Z CWallet::AutoZeromint() @ block 3050: successfully minted 10 Zerocoin. Current percentage of Zerocoin: 99.190484%
2019-01-06T15:41:27Z UpdateTip: new best=d67696c9c154b771adb477768c590b40e81b9870f2b66a47ab2f2688754c6d0e height=3050 version=0x20000000 log2_work=22.012507 tx=5304 date='2019-01-06T15:40:55Z' progress=0.304972 cache=0.7MiB(3712txo)
2019-01-06T15:41:27Z [default wallet] AddToWallet d7af388a958e112104dd419edaa688cede90d490b46cb7111e7964fd149b7515  
```

**Comment by ianGre** [comment]
[Testnet]
This happened the same on my current build (level with 1.0.0.7) self-built from master.
Action: Mint 1010 Basecoin to Zerocoin
Transaction Detail from wallet
Tx ID: 387c9fc7b1f03980ff9673e9e789bc88cd270ac54580fc9b3b117bbf714d9e42
Amount: 2000.02000000 VEIL
Fee: 0.02000000 VEIL
(Currently unconfirmed!) !! I just realised that according to the 'rules' a zerocoin has to wait not only 200 confirmations, but for another user to mint another of the same! That makes minting 100s or 1000s on a testnet with two peers is extremely unlikely! This must be why I have 2,270 unconfirmed. Regardless, this issue report is about the double value display problem, which still remains.

(At the same time, an (auto)mint shows as 20.00000000 VEIL and 0.00000000 VEIL fee.
TxID 387c9fc7b1f03980ff9673e9e789bc88cd270ac54580fc9b3b117bbf714d9e42)
(Forget about following this on the Testnet Block Explorer, it got restarted this morning, generating from scratch, so doesn't have any of this history!)

**Comment by ianGre** [comment]
[testnet] Built on current 'wallet scan' build.
Tested one manual mint 100 denom. again, with testnet explorer confirmation.

State 1     listzerocoinamounts 
```
[
  {
    "denomination": 10,
    "mints_spendable": 1458,
    "mints_pending": 73
  },
  {
    "denomination": 100,
    "mints_spendable": 0,
    "mints_pending": 0
  },
  {
    "denomination": 1000,
    "mints_spendable": 0,
    "mints_pending": 1
  },
  {
    "denomination": 10000,
    "mints_spendable": 0,
    "mints_pending": 0
  }
]
```

Action: Manually minted a 100 zerocoin from basecoin.
Transaction Details (in wallet):
ID	bc0653bd202d8de93cc0f96ccf01029c2616e616bfef87483cab8ae9fd0d5f14
Amt	200.0100000 Veil
Fee	0.01000000 Veil

Display in testnet block explorer:
https://testnet.veil-project.com/tx/bc0653bd202d8de93cc0f96ccf01029c2616e616bfef87483cab8ae9fd0d5f14

Transaction	bc0653bd202d8de93cc0f96ccf01029c2616e616bfef87483cab8ae9fd0d5f14
 # Summary
Mined Time		Thu, 10 Jan 2019 21:39:18 UTC
In Block		4a04c12127256a36319b1d7039243935817d739afa7e1984dab5120c246ea7ca
In Block Height	7061
Total Input		109.95 tVeil
Total Output	109.94 tVeil
Fees			0.01 tVeil

Details		bc0653bd202d8de93cc0f96ccf01029c2616e616bfef87483cab8ae9fd0d5f14
mined Thu, 10 Jan 2019 21:39:18 UTC
➡ ms8mVwW13p1x97X7u29cfoZuvVBHjcjzaS	9.95 tVeil
➡ ms8mVwW13p1x97X7u29cfoZuvVBHjcjzaS	50 tVeil
➡ ms8mVwW13p1x97X7u29cfoZuvVBHjcjzaS	50 tVeil

Zerocoin Accumulator
100 tVeil ×
ms8mVwW13p1x97X7u29cfoZuvVBHjcjzaS	9.94 tVeil ×

Fee: 0.01 tVeil			4 Confirmations			109.94 tVeil

State 2     listzerocoinamounts 
```
[
  {
    "denomination": 10,
    "mints_spendable": 1476,
    "mints_pending": 126
  },
  {
    "denomination": 100,
    "mints_spendable": 0,
    "mints_pending": 1
  },
  {
    "denomination": 1000,
    "mints_spendable": 0,
    "mints_pending": 1
  },
  {
    "denomination": 10000,
    "mints_spendable": 0,
    "mints_pending": 0
  }
]
```

**Comment by StrontiumZ38** [comment]
@ianGre can this be closed?

**Comment by seanPhill** [comment]
The amounts shown in transaction history (detail) for mints from basecoin is still not showing an amount that reflects the actual transaction. It seems to simply add up the inputs and outputs. In the transaction list it shows a sensible number now, but when you click it shows a completely different amount.

**Comment by presstab** [comment]
Bounty: 333.33

**Comment by veilgets** [comment]
Developer: codeofalltrades

**Comment by seanPhill** [comment]
I have tested this today, and it is not showing the amount displaying in error as it did in early January.
The display is normal, showing:
Zerocoin Mint n/a
and the date, time and the amount of the fee, which is the effect on the balance.
when clicking into the transaction it also shows (correctly) the amount of the fee.
Granted, this still might not be very clear to newcomers, but it is important that the values shown in the wallet reflect the effect on the wallet balance resulting from the transaction.

THIS ISSUE MAY BE CLOSED.

**Comment by ianGre** [comment]
Oh, yes. I agree. I haven't seen this fault in a long time.
