### ISSUE TITLE
Autominting denom 100 (rather than 10) is not working. [testnet]

### ISSUE THREAD

**Issue by ianGre** [Veil-Project/veil#211]
version. Self-built from master @ 1.0.0.6 MacOS
[testnet]

I had changed the minting denom from 10 to 100 and the previously regular minting ceased. It only minted in 100 denom when I manually minted from Basecoin.

Debug.log shows```
2019-01-06T19:47:59Z [default wallet] CWallet::AutoZeromint(): Nothing minted because either not enough funds available or the requested denomination size (100) is not yet reached.
```

In Console:
```
getbalances
{
  "basecoin_spendable": "6334.49",
  "basecoin_unconfirmed": "0.00",
  "basecoin_immature": "0.00",
  "ct_spendable": "0.00",
  "ct_unconfirmed": "0.00",
  "ct_immature": "0.00",
  "ringct_spendable": "0.00",
  "ringct_unconfirmed": "0.00",
  "ringct_immature": "0.00",
  "zerocoin_spendable": "7160.00",
  "zerocoin_unconfirmed": "440.00",
  "zerocoin_immature": "420.00"
}
```

**Comment by ianGre** [comment]
Note the mints_pending amounts

```
listzerocoinamounts

[
  {
    "denomination": 10,
    "mints_spendable": 795,
    "mints_pending": 26
  },
  {
    "denomination": 100,
    "mints_spendable": 0,
    "mints_pending": 0
  },
  {
    "denomination": 1000,
    "mints_spendable": 0,
    "mints_pending": 1
  },
  {
    "denomination": 10000,
    "mints_spendable": 0,
    "mints_pending": 0
  }
]
```

**Comment by 4x13** [comment]
if u read that screen, it clearlys ays that those (4) selectable amounts are for the automatic conversion. manually u would need to enter 90 for (9) 10 denoms to be created or 100 for (1) 100 denom

**Comment by presstab** [comment]
Try building from master at least as high as commit ad48107d3c7a76de2241cc1b7ab33f95f6670483 and see if it changes this behavior.

**Comment by ianGre** [comment]
My wallet has minted many tens since, but now I just tried manually and it says insufficient balance.
![screen shot 2019-01-09 at 7 00 07 am](https://user-images.githubusercontent.com/36124423/50855609-6b926580-13dc-11e9-9413-0d1c2fac1ad2.png)

**Comment by ianGre** [comment]
I've only just now set the auto-mint value back to 100, again, so this (below) is not entirely unexpected, but it is, a bit. 
```
listzerocoinamounts
[
{    "denomination": 10,
     "mints_spendable": 2902,
     "mints_pending": 169
},
{     "denomination": 100,
     "mints_spendable": 0,
     "mints_pending": 0
},
{     "denomination": 1000,
     "mints_spendable": 0,
     "mints_pending": 1 
},
{     "denomination": 10000,
     "mints_spendable": 0,
     "mints_pending": 0   } ]
```

**Comment by ianGre** [comment]
Just a couple of minutes later, more tens have been minted, but not the 1000. Note, I had it set to 100, not 1000!

**Comment by seanPhill** [comment]
This issue could be replaced by the new feature request: 
Feature Request: Show autominting network conditions to explain lack of automint action #395
