### ISSUE TITLE
What’s the meaning behind this error, occurs when finding a stake.

### ISSUE THREAD

**Issue by veilgets** [Veil-Project/veil#212]
2019-01-05T12:29:51Z CreateNewBlock(): block weight: 57640 txs: 6 fees: 6000000 sigops 406 Proof-Of-Stake:1 
2019-01-05T12:29:51Z CreateNewBlock: FOUND STAKE!!
 block: 
CBlock(hash=ba62299707a5919fb79a742965c9b28845fb935cdf8f7fcff63908710a7b01b8, ver=0x20000000, hashPrevBlock=0b45bd1f28d8607c494c578dfb588ab84d9de817bd5c6f66ce5dc2c1b8013160, hashVeilData=5492cbc619fdc23ff8e9caef963ae4284538170c2343b5cdab1443a97ed84be9, hashMerkleRoot=2c7eb294f47d9b4bad262d8f902487b9635054dcc91c1922b7e86be2931bc4ca, hashWitnessMerkleRoot=2c7eb294f47d9b4bad262d8f902487b9635054dcc91c1922b7e86be2931bc4ca, hashProofOfFullNode=0fc91ccb385e3a312b0a452ba1e13fadd2d4c0c1b33e64be51828231715dd94d, nTime=1546691382, nBits=1b00bffb, nNonce=0, vtx=7)
  CTransaction(hash=52398d675f, ver=2, vin.size=1, nLockTime=0)
    CTxIn(COutPoint(0000000000, 4294967295), coinbase 02a00e00)
    CScriptWitness()
    CTxOutStandard(nValue=0.00000000, scriptPubKey=)

  CTransaction(hash=79d4605fba, ver=2, vin.size=1, nLockTime=0)
    CTxIn(COutPoint(0000000000, 4294967295), scriptSig=c2028e2c03012102df0b6ae2, nSequence=2147483658)
    CScriptWitness()
    CTxOutStandard(nValue=0.00000000, scriptPubKey=)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10280004c80f9f0858634a343d065)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10280004c8069d6a47739719e23df)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10280004c8069fbbfc484c2d57340)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10280004c808538d124f379c9bfef)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10280004c804bb38caebfb95dd70e)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10281004c818381592c9ad64b5848)

CTransaction(hash=83db0d410e, ver=2, vin.size=1, nLockTime=0)
    CTxIn(COutPoint(71e35ae502, 1), scriptSig=)
    CScriptWitness(304402206793db6f92bfd9628b2258f8a99f62cf5bdc5078066144fac3a989343245e334022079b4f973fdca5ec16a545a45d6735f259cad61e9122c72490191dc5e129bb75501, 023e8bfdd99d422522e628351a9305c3714bb9d800a0cd221e05812cee0e2f493f)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10281004c81f936f540d9d97cde40)
    CTxOutStandard(nValue=237.65818238, scriptPubKey=00144fafb58201a32a82fa641f6099)

  CTransaction(hash=db87606f0d, ver=2, vin.size=1, nLockTime=0)
    CTxIn(COutPoint(83db0d410e, 1), scriptSig=)
    CScriptWitness(304402200bb1c3b3957411a981b97de20bab401a4f2657949ca8cc26e997043000e87ef40220288684d62e1fe659a94a77ef4ae0a4208fbf3e410a10f20b97c57eae60bfae8001, 023e8bfdd99d422522e628351a9305c3714bb9d800a0cd221e05812cee0e2f493f)
    CTxOutStandard(nValue=100.00000000, scriptPubKey=c10280004c80e9d25963061eef7635)
    CTxOutStandard(nValue=137.64818238, scriptPubKey=00144fafb58201a32a82fa641f6099)

  CTransaction(hash=e7eab950bd, ver=2, vin.size=1, nLockTime=0)
    CTxIn(COutPoint(4a835ef45f, 1), scriptSig=)
    CScriptWitness(304402205a22d6fd519c6d28da50bae7983510fe585f6b449f696cd633bda17abbce21ad022040d63165cd09b4eec8875072221f829460706c6cad1baa0578fec03ced15a17101, 023e8bfdd99d422522e628351a9305c3714bb9d800a0cd221e05812cee0e2f493f)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10281004c810fce3222b5c7fb0962)
    CTxOutStandard(nValue=252.45476450, scriptPubKey=00144fafb58201a32a82fa641f6099)

CTransaction(hash=9f20389c48, ver=2, vin.size=1, nLockTime=0)
    CTxIn(COutPoint(e7eab950bd, 1), scriptSig=)
    CScriptWitness(30440220150aae600b4255e72453f969a454c166cd1042a37b42574764dd3589aa1d7f9702200704c059405741b30b8855d18cb214d08f0ef592a02155110bf5064b352e675d01, 023e8bfdd99d422522e628351a9305c3714bb9d800a0cd221e05812cee0e2f493f)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10280004c80157781b41aecca40ae)
    CTxOutStandard(nValue=242.44476450, scriptPubKey=00144fafb58201a32a82fa641f6099)

  CTransaction(hash=97c2c89e64, ver=2, vin.size=1, nLockTime=0)
    CTxIn(COutPoint(db87606f0d, 1), scriptSig=)
    CScriptWitness(304402204535c8ea1b86733d9ea1832e5423bd880fdc8477f083f2af4fb1d60d3a041dcc02201e9989e0d933cbf2c2a259695532d8213961c32f8d0f626486c98be23784fcd901, 023e8bfdd99d422522e628351a9305c3714bb9d800a0cd221e05812cee0e2f493f)
    CTxOutStandard(nValue=100.00000000, scriptPubKey=c10281004c819d4e169eecc1655af4)
    CTxOutStandard(nValue=37.63818238, scriptPubKey=00144fafb58201a32a82fa641f6099)

2019-01-05T12:29:53Z ERROR: ContextualCheckZerocoinMint: pubcoin b47be5029a was already accumulated in tx d8cc53beb480dd114c9ea449e633267123b360ac01b6a8e9a5bbedb786a3c458
2019-01-05T12:29:53Z ERROR: ConnectBlock: zerocoin mint failed contextual check
2019-01-05T12:29:53Z ERROR: CreateNewBlock: TestBlockValidity failed:  (code 16)
2019-01-05T12:29:53Z ERROR: CreateNewBlock: Clearing mempool because of error

**Comment by veilgets** [comment]
another one, different error

https://cdn.discordapp.com/attachments/531569822010441750/531578152791834624/error2.txt

**Comment by Tris10w** [comment]
I've seen this one quite frequently. Around 50% of stakes end in this.

**Comment by mrjaekin** [comment]
All of my stakes end in this error.  Win7 64bit installer and zip

**Comment by veilgets** [comment]
more staking errors:
https://cdn.discordapp.com/attachments/531569822010441750/531872933988139018/error3.txt
https://cdn.discordapp.com/attachments/531569822010441750/531873148824715264/error4.txt

**Comment by presstab** [comment]
The error happens when the wallet has spent a zerocoin, but does not have it marked as spent. Or it could also be that one of the transactions included in the block packaged by the stake included a zerocoin that was already spent.
#219 Should reduce about 80% of this error reporting.

**Comment by veilgets** [comment]
ty for the info, the other 3 errors differ from each other, could u check those too
