### ISSUE TITLE
Possibly displaying transactions that do not belong to the user's wallet.

### ISSUE THREAD

**Issue by Replicon1** [Veil-Project/veil#213]
I installed a purse (1.0.0.6) on other computer (with the arm-processor)
restored by means of Import wallet
carried out synchronization and the sequence
getarchivedzerocoin 
reconsiderzerocoins 
resetspentzerocoin 
resetmintzerocoin true 
rescanblockchain 
searchdeterministiczerocoin 0 5000 2
Need wait 15 minutes
getbalances

as a result: instead of 40 zerocoin - it is much more
![2019-01-06_22-44-39](https://user-images.githubusercontent.com/46427109/50741392-b7db7b00-120d-11e9-8318-3c43a279927b.png)

in addition it was found out that through this purse there pass transactions of other users. We found each other and checked.
![2019-01-07_00-05-51](https://user-images.githubusercontent.com/46427109/50741935-61723a80-1215-11e9-8463-807cc3e0c9c4.png)

**Comment by Replicon1** [comment]
in addition it was found out that through this purse there pass transactions of other users. We found each other and checked.
![2019-01-07_00-05-51](https://user-images.githubusercontent.com/46427109/50741675-52898900-1211-11e9-89de-c6efd8f60da7.png)

**Comment by presstab** [comment]
What do you mean past transactions of other users? Can you give more detail about that?

**Comment by seanPhill** [comment]
I have to wonder whether users have in the past few days _imported_ zerocoins that were minted while another wallet.dat was active and mixed up data folders while changing the wallet seed. All sorts of things that have been out of control. If the user "knows" _who_ the other user is, who the coins belong to then it is _statistically impossible_ for this to have been a cryptographic error!

**Comment by seanPhill** [comment]
Another user (and possibly this user) has claimed that some users have been _trying_ to get invalid coins and history in order to claim to Support that these are really their coins.

**Comment by Replicon1** [comment]
I specify, at all users who restore the purse through import of wallet.dat,
receive a purse with the identical address "... 8ar8" - it is necessary to
look for a mistake from here.

On your question. After creation of a purse synchronization, in the history
of transactions - operations which have no relation to my real purse begins.

When the purse is open, in real time I see replenishment of balance and
writing off though I do not make any operations at this time.

пн, 7 янв. 2019 г. в 22:05, Tom Bradshaw (presstab) <
notifications@github.com>:

**Comment by Replicon1** [comment]
yes, it so.

I specify, at all users who restore the purse through import of wallet.dat,
receive a purse with the identical address "... 8ar8" - it is necessary to
look for a mistake from here.

On your question. After creation of a purse synchronization, in the history
of transactions - operations which have no relation to my real purse begins.

When the purse is open, in real time I see replenishment of balance and
writing off though I do not make any operations at this time.

вт, 8 янв. 2019 г. в 22:56, Sean Phillips <notifications@github.com>:

**Comment by presstab** [comment]
As far as I can tell this was caused by the bug of creating a wallet with an empty seed using the "Import Wallet File" button.
