### ISSUE TITLE
example command in help is wrong - deterministiczerocoinstate

### ISSUE THREAD

**Issue by ianGre** [Veil-Project/veil#214]
Was mintpoolstatus taken as a template for the help text for one or more commands?
mintpoolstatus is not found.

```Veil Core version v1.0.0.6-1674a6312 (64-bit) Windows 10

help deterministiczerocoinstate

deterministiczerocoinstate
The current state of the mintpool of the deterministic zerocoin wallet.

Examples
> veil-cli mintpoolstatus 
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "mintpoolstatus", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/
```

**Comment by 4x13** [comment]
Why not submit a PR if it just a textual update?

**Comment by ianGre** [comment]
I thought this was where all issues should be submitted, regardless of type. Maybe I should search for each one myself and issue a pull request? I guess I could.

**Comment by presstab** [comment]
@ianGre fine to post that here. Thanks.

**Comment by presstab** [comment]
c154ece5c1387940d4899345f4ff65aaccc8168e
