### ISSUE TITLE
Crazy fees on mint on convert CT to Basecoin 1.0.0.6

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#215]
Crazy fees on mint on convert CT to Basecoin
![image](https://user-images.githubusercontent.com/38264865/50745382-33204980-126d-11e9-860d-a1ad42bd6653.png)

**Comment by 4x13** [comment]
This has already been posted

**Comment by StrontiumZ38** [comment]
I made it a separate issue because it was CT to Basecoin rather than zerocoin. Wasn't sure if they were handled by same code or if they're different enough to be distinct issues (the huge fee made me think it's being calculated in a different way).

**Comment by presstab** [comment]
As far as I know, this is just a problem with the displaying of the tx in the GUI. Can you find the txhash and use in the console:
`getrawtransaction <txid> 1` 
And then look for the first part of the vout vector where is says: `ct_fee`. That is the transaction fee.
