### ISSUE TITLE
Mining by default, even when disabling from console 1.0.0.6

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#216]
I'm mining upon opening test wallet, despite not having enabled mining. Even after entering generatecontinuous false it seemingly continues to mine blocks.
![image](https://user-images.githubusercontent.com/38264865/50746058-a4adc700-1270-11e9-9a11-bd80e12ed36d.png)

**Comment by seanPhill** [comment]
This _might_ only be happening in Windows, or in code that has since been fixed.

**Comment by StrontiumZ38** [comment]
I can't confirm for sure, but this seems to be fixed. PC not behaving as if mining, but difficulty on testnet has increased to the point I can't be sure. Might need confirmation that this has been addressed before closing @presstab

**Comment by StrontiumZ38** [comment]
Can confirm this is still a thing. Wallet left on from fresh install today and testnet mined all day.
