### ISSUE TITLE
Spending  works but shows "Amounts exceeds your balance"

### ISSUE THREAD

**Issue by MisterKangaroo** [Veil-Project/veil#217]
A minor GUI issue on the windows x64 wallet (testnet)
When spending zerocoins it seems to work but shows "Amount exceeds your balance" nonetheless.
And it shows a 0 in the transaction overview (see screenshot).
![0trans](https://user-images.githubusercontent.com/43561981/50748508-26cec900-123a-11e9-8c1f-16951e2e2cfb.PNG)

**Comment by MisterKangaroo** [comment]
![id](https://user-images.githubusercontent.com/43561981/50748547-4cf46900-123a-11e9-8cac-d55cc9331024.PNG)

**Comment by presstab** [comment]
This is when it creates a zerocoinspend from the GUI correct?

**Comment by MisterKangaroo** [comment]
Yes it is

**Comment by furszy** [comment]
Done.
