### ISSUE TITLE
Win32 wallet on Windows XP, dwmapi.dll not found.

### ISSUE THREAD

**Issue by ianGre** [Veil-Project/veil#22]
I installed the Win32 EXE (from the precompiled EXE).

When I launched the program it could not start, because dwmapi.dll was not found.

**Comment by ianGre** [comment]
The same DLL problem when trying to launch from the admin account it was installed by.

NOTE: This Windows 32-bit version is Windows XP. So maybe just note that it is not supported, or note which Windows versions are supported.

**Comment by 4x13** [comment]
Was this the recent gitian built images I posted to github?

**Comment by ianGre** [comment]
This was from the dropbox posted executable, but I am closing this because Windows XP is not a priority, and there will likely be other dependencies not present in this obsolete operating system.
