### ISSUE TITLE
Is there any way to inform the user that the synchronization process is not stuck?

### ISSUE THREAD

**Issue by gabrielnergaard** [Veil-Project/veil#221]
Running 1.0.0.6 on Mac OS X 10.14.2, my screen appeared to be in a stuck state for about five minutes:

![](https://clipz.in/6pmn7.png)

Just when I was about to quit the application, it started processing blocks.

During those five minutes in which the app obviously was not stuck, but the user would from the UI believe it to be so, is there any status information we can show to communicate that it's not stuck?

**Comment by presstab** [comment]
How do you know it was not stuck during those 5 minutes? I am occasionally seeing periods of repetitive loops in syncing where nothing really progresses.

**Comment by gabrielnergaard** [comment]
I do not know that it was not stuck during those 5 minutes. In fact, I thought it was stuck and was about to quit the app when it suddenly progressed. When it proceeded, I then presumed that it wasn’t stuck.
Jan 7, 2019, 10:18 PM by notifications@github.com:

**Comment by seanPhill** [comment]
That's why I rarely leave it at that screen. I hide it and look at the Information tab of the "Advanced Options" window.

**Comment by StrontiumZ38** [comment]
Is this something that can wait until new wallet? I don't undervalue this from a UX perspective whatsoever, but it may be resources better spent elsewhere for now.

**Comment by presstab** [comment]
Bounty: 187.5

**Comment by veilgets** [comment]
Developer: MatWaller

**Comment by MatWaller** [comment]
Closed with #543
