### ISSUE TITLE
Find a better icon for the overview navigation item

### ISSUE THREAD

**Issue by gabrielnergaard** [Veil-Project/veil#222]
The icon currently used for the overview screen is the one commonly used for the "refresh" action:

![](https://clipz.in/u7a7j.png)

Please choose something more appropriate to overview. (At least, something that's not already commonly understood to stand for something else.)

**Comment by Tris10w** [comment]
This is actually a great point. For me, it's showing transactions, so possibly something to that extent. If we're still attempting to make that an "overview", then possibly a Home icon would work.

cheers.

**Comment by gabrielnergaard** [comment]
This issue was previously opened and closed by @veildev as a "design decision". It's a wrong design decision. If there's any doubt of that, here's a Google Image search of "refresh icon":

![](https://clipz.in/zf4ac.png)

**Comment by StrontiumZ38** [comment]
Due to ongoing efforts within the team, I think this can be closed as it serves no real purpose being here. @gabrielnergaard or @4x13
