### ISSUE TITLE
Address Label Editing

### ISSUE THREAD

**Issue by rkp889** [Veil-Project/veil#223]
Editing existing address label creates new empty address entry with said label.

Editing any labels should be reflected on the address line selected

![capture](https://user-images.githubusercontent.com/38085566/50781265-e7709e80-1272-11e9-808e-0dd991fd4e49.PNG)

v 1.0.0.6, Github

Win 10 1803

**Comment by veildev** [comment]
Hi, check this compiling from the sources please.

**Comment by rkp889** [comment]
sorry, were you asking me to compile my own or compare a hash against the pre-compiled version?

**Comment by presstab** [comment]
I think what @veildev meant is that this feature is added and in the current master branch. So if you can compile from master, try it, if not we should have a new build out today that would let you see the ability to edit that was added.
