### ISSUE TITLE
Move the nav to the left-hand side

### ISSUE THREAD

**Issue by gabrielnergaard** [Veil-Project/veil#225]
As we were worried would happen, having the nav on the right side has caused confusion in many cases as reported by the public in Discord.

I'm creating this placeholder issue for a discussion of moving the nav to the left side.

**Comment by 4x13** [comment]
I think it should be user selectable as I prefer it on the right hand side.

**Comment by seanPhill** [comment]
The _only_ problem I see with RHS is that some people did not have their application Window wide-enough to see the nav bar. For navigational use I personally prefer the RHS. That's where my mouse is when I grab it! The other issue some have (or one has) raised is the question of whether the navigation menu is _visually part of_ the main window.

**Comment by gabrielnergaard** [comment]
The placement of the navigation, like most UI considerations, might seem subjective, but it’s not. See the left-vs-right section here:

https://www.webfx.com/blog/web-design/10-usability-tips-based-on-research-studies/ <https://www.webfx.com/blog/web-design/10-usability-tips-based-on-research-studies/>

Every designer in the Veil project (myself included) reacted to this issue, and there are several cases of confusion amoungst the public (according to gets). 

At the end of the day, though, it’s better to leave it on the right, than to add a setting for it.
Jan 8, 2019, 8:45 PM by notifications@github.com:

**Comment by StrontiumZ38** [comment]
Due to ongoing efforts within the team, I think this can be closed as it serves no real purpose being here. @gabrielnergaard or @4x13
