### ISSUE TITLE
add warning you need atleast 10 Veil to manually mint to zerocoin

### ISSUE THREAD

**Issue by veilgets** [Veil-Project/veil#226]
In the screen for manual minting please add a message saying u need atleast 10 basecoin/ringct to mint a zerocoin

**Comment by 4x13** [comment]
should actually be 10.1 for each 10 denom to be minted

**Comment by veilgets** [comment]
right, is fee 0.1 or 0.01, either way need the fee

**Comment by seanPhill** [comment]
I've seen 0.01 in the block explorer, and 0.1 in the GUI, but that is in other issue number(s).

**Comment by presstab** [comment]
Bounty Price: 93.75
Estimated Hours: 1.5

**Comment by veilgets** [comment]
Developer: drag0ng
