### ISSUE TITLE
When creating new block..... ConnectBlock: Consensus::CheckTxInputs: xxxx bad-txns-inputs-missingorspent

### ISSUE THREAD

**Issue by pmfrulez** [Veil-Project/veil#235]
after found stake 

2019-01-06T10:27:30Z CreateCoinStake : kernel found
2019-01-06T10:27:31Z GenerateAccumulatorWitness: generating
2019-01-06T10:27:35Z GenerateAccumulatorWitness : 1041 mints added to witness
2019-01-06T10:27:43Z CreateNewBlock(): block weight: 82460 txs: 15 fees: 17866904 sigops 434 Proof-Of-Stake:1 
2019-01-06T10:27:43Z CreateNewBlock: FOUND STAKE!!
 block: 
CBlock(hash=e73d6e7c541a4c31752fb61717265db26047223d920974a269bfb13dd84bd702, ver=0x20000000, hashPrevBlock=4aa0190d22a560bf7eac8054535ba29c9eddb85addea176daebc63dccb26fa62, hashVeilData=164c398cfa256cde96d915de0ffcace4f345b3c195b851eb3ff4b7f2249d9e72, hashMerkleRoot=530fdc19aaba066b794d76b8615fb5f2920f5884007e4ef8158482645c6db81a, hashWitnessMerkleRoot=530fdc19aaba066b794d76b8615fb5f2920f5884007e4ef8158482645c6db81a, hashProofOfFullNode=df2efec65f031cd29c42d1eb8a0499f1ae9e33b4579f08f07c74c4756fa06ce2, nTime=1546770452, nBits=1b011ea2, nNonce=0, vtx=16)
  CTransaction(hash=8f95658baa, ver=2, vin.size=1, nLockTime=0)
    CTxIn(COutPoint(0000000000, 4294967295), coinbase 029c1300)
    CScriptWitness()
    CTxOutStandard(nValue=0.00000000, scriptPubKey=)

  CTransaction(hash=7ba129a230, ver=2, vin.size=1, nLockTime=0)
    CTxIn(COutPoint(0000000000, 4294967295), scriptSig=c202942c03012102f57ba586, nSequence=2147483658)
    CScriptWitness()
    CTxOutStandard(nValue=0.00000000, scriptPubKey=)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10281004c81190a40d585806be51a)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10280004c8069853f9752a5cd9796)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10280004c807b5eecdba5d3aff162)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10281004c810bc7790ad07152bb4a)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10280004c805d04bf584f50bc0c91)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10280004c80477f6f2c9985683d9b)

  CTransaction(hash=2b01c071b3, ver=2, vin.size=1, nLockTime=0)
    CTxIn(COutPoint(7fe4e68c6e, 1), scriptSig=)
    CScriptWitness(30440220135c8716e402521b6818a9c871e2a60db416452d10e014264c6369e275e2d3aa0220657393dcf8ac5ff71bf417ea8c8ff666cb5278b95a0c288001ca6ca1635b735a01, 03539fe2804a19699da599acb2ef1b527f2ade9d24a165f4ce9bdde19059bab6f4)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10281004c8143f3bbf448534acd74)
    CTxOutStandard(nValue=20.02860564, scriptPubKey=0014ce4aa26b72d374ad5b0c0e502f)

  CTransaction(hash=75fd92d5c2, ver=2, vin.size=1, nLockTime=0)
    CTxIn(COutPoint(2b01c071b3, 1), scriptSig=)
    CScriptWitness(304402203b74553bb147d76b5b3f407b5f204f7e87e34a68b4534f9cb3925bcbaae426d00220615cd8a4dc211333f3e7112085354759365e52b6e038f0648fd24d62b270671901, 03539fe2804a19699da599acb2ef1b527f2ade9d24a165f4ce9bdde19059bab6f4)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10280004c8035e20b29f8c296e51b)
    CTxOutStandard(nValue=10.01860564, scriptPubKey=0014ce4aa26b72d374ad5b0c0e502f)

  CTransaction(hash=b4b4996ce3, ver=2, vin.size=1, nLockTime=0)
    CTxIn(COutPoint(75fd92d5c2, 1), scriptSig=)
    CScriptWitness(304402200db3ec7c321a941ed60379a1c2288c4276f65f1d82c8f18c92beffd8b4b0d4110220069513d7a8c7358b7a581c3545794c7aefb807b13c617c9a8c46584e3433fee501, 03539fe2804a19699da599acb2ef1b527f2ade9d24a165f4ce9bdde19059bab6f4)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10281004c81e172607d60f9aeaf94)

  CTransaction(hash=371c9d357f, ver=2, vin.size=3, nLockTime=0)
    CTxIn(COutPoint(f373b535b1, 4), scriptSig=)
    CTxIn(COutPoint(9c996ee426, 1), scriptSig=)
    CTxIn(COutPoint(2a45c47b36, 13), scriptSig=)
    CScriptWitness(304402206bf72e58ee271037d3fbe8f0dfd8848b3ae897d44dc0b4a97e89cec1e54b96a3022062f62afd9abd41238f1b393123bfb5abac933750856d3dc7a51e9cd1cf11f56501, 03ca6f17bce428e4fb19ae59bfe698bd31455cc4ed252eba795b8561b31c44009a)
    CScriptWitness(30440220039bbb3ac939e86ca415fdf29fb44bf7e55f39211363b56125c4ee445206d8c20220097fc02d653761bcdc1e075e94aaf2fc03f199a3f0771d93a7f1a401155f00b901, 03ca6f17bce428e4fb19ae59bfe698bd31455cc4ed252eba795b8561b31c44009a)
    CScriptWitness(30440220068e5a5d0f633fa8c29f82c0f4327a8f4972a63a5b3405795b691369b8b99c44022069c299da4f8f960e2512ef8b87d246c36c4cd1b5d8501abce336051db715fb8001, 03ca6f17bce428e4fb19ae59bfe698bd31455cc4ed252eba795b8561b31c44009a)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10280004c8075dd636a2583cda34e)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10281004c81dd875a29d407f9c1df)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10280004c80935405b9fc8d69c3c2)
    CTxOutStandard(nValue=0.26024483, scriptPubKey=001437daf627f2b26cef430165e28f)

  CTransaction(hash=a3b5a4dec5, ver=2, vin.size=2, nLockTime=0)
    CTxIn(COutPoint(57bf6b6d87, 4), scriptSig=)
    CTxIn(COutPoint(e701fd2eeb, 10), scriptSig=)
    CScriptWitness(30440220284d4d2c469423d928bf041b055741ae4b68ee4791a3b15020c7c4231be16aad02207e1129b149841b30efbce2505b5a6b481bcd125a12a2e16482f165a1f2bb60b101, 0374fe30653a22dab8b72b178c5b8f8bc8a4f9a3355db2546c84f8e1603ee72ab2)
    CScriptWitness(304402203e444ac5e223fa360b81465922cd879109f7117e6c224909e1edab827ae208dd02203044ce2acea8746251a92a6ae35af41b9943a8d4250cba6b0a28543c942d7c4901, 0374fe30653a22dab8b72b178c5b8f8bc8a4f9a3355db2546c84f8e1603ee72ab2)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10281004c81f14f7c3773d9e548be)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10281004c81ef5b3c86b5c51a3e7f)
    CTxOutStandard(nValue=0.14648146, scriptPubKey=0014c6f2d4238bedc897b28b188271)

  CTransaction(hash=7b28929e16, ver=2, vin.size=1, nLockTime=0)
    CTxIn(COutPoint(f3952bfc10, 46), scriptSig=)
    CScriptWitness(3044022056e14e92edd55ec1dc856eb72ed9b95d8733c5e29e08324a7b2bb0b78dc69ff80220502ee1715ec922468aefc1668f20603cb3043780ebe22d74fd1ba6019ef6e0d201, 0374fe30653a22dab8b72b178c5b8f8bc8a4f9a3355db2546c84f8e1603ee72ab2)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10280004c800f791f185bd7afee19)
    CTxOutStandard(nValue=1.85202740, scriptPubKey=0014c6f2d4238bedc897b28b188271)

  CTransaction(hash=553d6feeea, ver=2, vin.size=1, nLockTime=0)
    CTxIn(COutPoint(9877ea6bc7, 0), scriptSig=)
    CScriptWitness(304402202ccdac3b31e9674097cd95f8f53160f0cc92c70862c3b64ca0610cf1f32c1d8b02203347120835219650d8b147e5aa36dcf5a55b0bfe16931d24361ee15118489c7601, 0374fe30653a22dab8b72b178c5b8f8bc8a4f9a3355db2546c84f8e1603ee72ab2)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10280004c80e1c70118ef65c516c3)
    CTxOutStandard(nValue=0.05683483, scriptPubKey=0014c6f2d4238bedc897b28b188271)

  CTransaction(hash=8a4eec374d, ver=2, vin.size=1, nLockTime=0)
    CTxIn(COutPoint(ba4c4fc830, 1), scriptSig=)
    CScriptWitness(3044022013a02134b391f780a8af1a7f2dcc1b6900fdf26268b1256a77d54855160cad1402202a93d49950dfcf8687ede344392ac4f548d21e68f935944695acca5c2cf3b8a201, 0307472553e9063f8ba59dd6419544f7464fd5f90f1758646b7359b3638368d54e)
    CTxOutStandard(nValue=100.00000000, scriptPubKey=c10280004c800932610cf2be995567)
    CTxOutStandard(nValue=6.90620583, scriptPubKey=0014e99a6bf4e2819ac760ad5d5d48)

  CTransaction(hash=371c35d8e2, ver=2, vin.size=2, nLockTime=0)
    CTxIn(COutPoint(2379462824, 0), scriptSig=)
    CTxIn(COutPoint(5cf48a5145, 1), scriptSig=)
    CScriptWitness(3044022074dde61d6989acf124718e73c822443f5d6d6dc844f91975c20f2ce7fa99404602206e6bff6dda65bf0ea5de36e579fc19edf19418de1921db738d73e27a968989fa01, 037ec41ff23fa8d1543f4b1156c822edef3c71a559075fb536fc32800ac7ee042a)
    CScriptWitness(3044022046907f1abed5752684bea4200061d6788adadae3debc878c35d53996534c0dc40220755d3b4267281b06707a46bcf7a92361cbf50f26a2d2613c8ee94cdd92953c8501, 0230e9ef848bbc23ec34b8b3133bbf6fea1d9d725aef4473fd77a6824fb52b9da0)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10281004c8161cdb47e2120b17084)
    CTxOutStandard(nValue=0.06870511, scriptPubKey=0014f1a5e185b9f9e7b919f3a2f83a)

  CTransaction(hash=2e9ed235d0, ver=2, vin.size=3, nLockTime=0)
    CTxIn(COutPoint(f706dbe24c, 1), scriptSig=)
    CTxIn(COutPoint(dbd844c7e3, 1), scriptSig=)
    CTxIn(COutPoint(8a4eec374d, 1), scriptSig=)
    CScriptWitness(304402200de99a88fe120b5f07a61623f1d255977716411f9739d7b439b3662a03f98475022024ff62cb962cc9ad4a90d761ce1b911da5a912372fb01a1f5b5428059e54c30e01, 0206f3de3185bccd41d006a830f7ac4f696d10483e8e0720b9799e276c9b037d45)
    CScriptWitness(304402201655f947d57d55317ef22e6b1371ee4df5c2d3866a1e3f566065b8ded9942ff70220645be93c9f5d354db1f2f3cdd810bb92256cfcf77603ad891b1fe92e83e0701b01, 02cdea6e4c384c6a6674d78c985438e1c5b4530930b0605843bac682b9b4b465fc)
    CScriptWitness(304402202512d45264ff3f3eecb5809fec78d480b9f9ebb9cd883c89304ab6298294afab022005c2ad9b9c1792a9d09fa50c44e712fdee938b08dbb8b466234508dc56f3352301, 0307472553e9063f8ba59dd6419544f7464fd5f90f1758646b7359b3638368d54e)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10280004c8099dce6b801a3ba9c5d)
    CTxOutStandard(nValue=0.01828866, scriptPubKey=0014e99a6bf4e2819ac760ad5d5d48)

  CTransaction(hash=b05d0a6202, ver=2, vin.size=3, nLockTime=0)
    CTxIn(COutPoint(b6cbb8f142, 1), scriptSig=)
    CTxIn(COutPoint(4e1ff23f8f, 0), scriptSig=)
    CTxIn(COutPoint(16308b2115, 0), scriptSig=)
    CScriptWitness(304402205bc306a6795e79132515c0d3c8b26aa5c8fbaf83f17755535b61abea13efe66a022039bce29e1cf2667498d83f04698a77e88f9e7377731dc41b6c8855e52dc989c401, 02cdea6e4c384c6a6674d78c985438e1c5b4530930b0605843bac682b9b4b465fc)
    CScriptWitness(304402202efa39b33e8b8b7e6e61b9e7a3d16b827bfe1f015739ad0104f800d3d301542b02201166a87748713230564da4bc9266aa3842018d8a8e2b8d3fcb6df0a87bd1505d01, 0268f286248bf3f1b8f7ba2a6fcd41be6b2b4002faba4efd0656e42cb8396c762e)
    CScriptWitness(3044022071496f25dab7187dc936b9ef8d354461a88b5eef8f565820e7f28b7ad009bcfb02204454487c3039dba1c77fbf621d06caa888044d880e41728aaff7c956d475ebc001, 02cdea6e4c384c6a6674d78c985438e1c5b4530930b0605843bac682b9b4b465fc)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10280004c80bd3f769fa43fc03181)
    CTxOutStandard(nValue=1.01994359, scriptPubKey=00147316d2ee5cc29b36cea743b722)

  CTransaction(hash=8d02f537de, ver=2, vin.size=5, nLockTime=0)
    CTxIn(COutPoint(29bc7f2c77, 1), scriptSig=)
    CTxIn(COutPoint(0a9be41d22, 6), scriptSig=)
    CTxIn(COutPoint(641efcfbcd, 1), scriptSig=)
    CTxIn(COutPoint(8c6488807f, 1), scriptSig=)
    CTxIn(COutPoint(0bb82ce35d, 1), scriptSig=)
    CScriptWitness(304402200b60930e1fe078d5a15892d9d58575c58f29c2e98575412a19a6dda3366a14ad02207717c6a85759a2d1132de73bfc7dad5007592fccd6b11c531bf2325791c7879c01, 0268f286248bf3f1b8f7ba2a6fcd41be6b2b4002faba4efd0656e42cb8396c762e)
    CScriptWitness(304402207edc1f767a1efea013b992aaa86829cf0f5c79774ec7cb3e754fa3b41b7404b302200e578916c38aaef1aa02c91f7da3294c0889cf0fb795df8bd3facd1d9f61541401, 0268f286248bf3f1b8f7ba2a6fcd41be6b2b4002faba4efd0656e42cb8396c762e)
    CScriptWitness(304402205b00b1a232e35990b741796e2be8607c2960ac63667f9817366aa9840bdf04ac0220150729100ac6c3d548225feeded0d3cc45475977e418717e4005750f69dc015b01, 0206f3de3185bccd41d006a830f7ac4f696d10483e8e0720b9799e276c9b037d45)
    CScriptWitness(304402200790722d1befcb8e73e2836647c68640528523ac850a8d8028905793d418376a022014a8d2db23d37e70430a1bd768839358008f7dfaee65bbd7b6943c61db33aa9f01, 0206f3de3185bccd41d006a830f7ac4f696d10483e8e0720b9799e276c9b037d45)
    CScriptWitness(3044022032fd28239d8a03b660bc5de41960c33316368827e06fd0dffc74de79728faa51022023df46a07d5a0647a8c4e0dd733b64c04f171d06dcd057fb9f5663f769b949ae01, 0268f286248bf3f1b8f7ba2a6fcd41be6b2b4002faba4efd0656e42cb8396c762e)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10281004c81c754bd939ba1b2014b)
    CTxOutStandard(nValue=0.06040208, scriptPubKey=0014220f818ea81bcadd4e6c46bfaf)

  CTransaction(hash=7152e04675, ver=2, vin.size=8, nLockTime=0)
    CTxIn(COutPoint(244a501864, 1), scriptSig=)
    CTxIn(COutPoint(de59aa05db, 0), scriptSig=)
    CTxIn(COutPoint(032532e7d1, 19), scriptSig=)
    CTxIn(COutPoint(ec42beab63, 0), scriptSig=)
    CTxIn(COutPoint(8d02f537de, 1), scriptSig=)
    CTxIn(COutPoint(dbb324d995, 1), scriptSig=)
    CTxIn(COutPoint(371c35d8e2, 1), scriptSig=)
    CTxIn(COutPoint(b05d0a6202, 1), scriptSig=)
    CScriptWitness(304402201d24b5e0f41803a431b51b178c4ac0143ed203c3c5c1aa758e6102ecb3eb67e9022044add8ce641204bca1ec34728f84f5ddc3cebcf3e35d960311381682b62a272701, 0268f286248bf3f1b8f7ba2a6fcd41be6b2b4002faba4efd0656e42cb8396c762e)
    CScriptWitness(3044022041da9ee9a4116b7c7539f110fd4e779fb06a292e12894c95fb70e1ba1cd4af090220765b3600d8b5aa4c74ce4f41cf19ab8be3015900335098f6c3410c2e8219013e01, 020325e0b5c701c192037688850a1c086cec5d082d7aeba297471f07437610980f)
    CScriptWitness(304402201c5758479e587fcf201e795813486c5ff4928974174735404e394ab5ac16182e02207f1c1bf96fb479c4319b7c00d5b1336967f4de02cfe404db63c0e34269dfddc701, 0268f286248bf3f1b8f7ba2a6fcd41be6b2b4002faba4efd0656e42cb8396c762e)
    CScriptWitness(30440220637836fc945df41bdeb6f69cb4327245f160bc648ca31742074a164592bf8cd4022053a637af30d85afbd3160e900f12309bd0d4c38f7fa515739178928a16a1485a01, 020325e0b5c701c192037688850a1c086cec5d082d7aeba297471f07437610980f)
    CScriptWitness(304402201df8838bb1ca188c9c61e1aa2a160ef42c108b131da130cb3e3b0710bc9c088a022047129649c5de91fb823f1472fca53bf25cd73bb9b17166049673b5886450e1d001, 0268f286248bf3f1b8f7ba2a6fcd41be6b2b4002faba4efd0656e42cb8396c762e)
    CScriptWitness(3044022021ad6fa65ca29226c1c365bb960b19624c12b39baef20e18a0dbe4bb6cefb4e9022012267b92798e2f3a77de9b26f80d5f58e304f7034cde3d1ca5cfc4844e296d7401, 0307472553e9063f8ba59dd6419544f7464fd5f90f1758646b7359b3638368d54e)
    CScriptWitness(304402202fcc6058b21c355aa3bddd0eb744b30ae82bac02aa2a047c8a6300e00512016c02200a47331a399c59934e8aad4fbb390c22d4539125c19f97a3b66f03f9235e983f01, 0230e9ef848bbc23ec34b8b3133bbf6fea1d9d725aef4473fd77a6824fb52b9da0)
    CScriptWitness(304402203d843fd3afc84725326a8ea6a6e1a4c5612cf4ea9958ef352690675f9736e40e02207a9ffe003972132bb5eb5360b777bf5ee8fc2e64f5bae7f874b8c688acb1aec101, 02cdea6e4c384c6a6674d78c985438e1c5b4530930b0605843bac682b9b4b465fc)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10281004c81a193bce36187a78a66)
    CTxOutStandard(nValue=0.03448371, scriptPubKey=0014220f818ea81bcadd4e6c46bfaf)

  CTransaction(hash=de69d2ffb5, ver=2, vin.size=1, nLockTime=5019)
    CTxIn(COutPoint(3b272f7663, 0), scriptSig=, nSequence=4294967294)
    CScriptWitness(304402201772cf10fe24551d9a414380538fc92215e06451ab50ea1c9ca26dc5e8e26a3b022030e2a1ce9685e8c011d32a8f9a0dd09a165bd09c70cbbe3b966473b4944d679001, 02ac0f17837cffe7f933787c2b8142775fc5cca67f978693678c4d590db99c5e07)
    CTxOutStandard(nValue=1.85705872, scriptPubKey=0014f3f6739ee9d097ee741b45e171)
    CTxOutStandard(nValue=5.06134324, scriptPubKey=001495f785eb1e710677011ab724ad)
    CTxOutStandard(nValue=4.02220677, scriptPubKey=0014d61d936e0ce37ab9cffb5998a4)
    CTxOutStandard(nValue=0.00991240, scriptPubKey=0014ee8cbd1d33022c1a7e30e360cf)
    CTxOutStandard(nValue=0.52310318, scriptPubKey=001431ac8beae8f5f07b9cc645b2d5)

**2019-01-06T10:27:47Z ERROR: ConnectBlock: Consensus::CheckTxInputs: 2b01c071b30d3fd9ac01dee54bc7be0aedf3879b8d7cbb7f3606741074c5a256, bad-txns-inputs-missingorspent, CheckTxInputs: inputs missing/spent **(code 16)**
2019-01-06T10:27:47Z ERROR: CreateNewBlock: TestBlockValidity failed: bad-txns-inputs-missingorspent, CheckTxInputs: inputs missing/spent (code 16)**
2019-01-06T10:27:47Z ERROR: CreateNewBlock: Clearing mempool because of error
2019-01-06T10:28:32Z SelectStakeCoins: FOUND 21 STAKABLE ZEROCOINS
2019-01-06T10:29:14Z [default wallet] CWallet::AutoZeromint(): Nothing minted because either not enough funds available or the requested denomination size (10) is not yet reached.
2019-01-06T10:29:14Z UpdateTip: new best=2e5f753410362b44216e77fabea3ee5968df7d8061cb48db13c1a272a902edfd height=5020 version=0x20000000 log2_work=22.606195 tx=14864 date='2019-01-06T10:28:30Z' progress=0.999877 cache=0.4MiB(2196txo)
2019-01-06T10:29:17Z SelectStakeCoins: FOUND 21 STAKABLE ZEROCOINS
2019-01-06T10:29:49Z [default wallet] CWallet::AutoZeromint(): Nothing minted because either not enough funds available or the requested denomination size (10) is not yet reached.
2019-01-06T10:29:49Z UpdateTip: new best=6443546f1f82a0947ce3c7ab9e19acb8fb6fa9a79447e02d9526275881aaf4c2 height=5021 version=0x20000000 log2_work=22.606385 tx=14866 date='2019-01-06T10:29:39Z' progress=0.999972 cache=0.4MiB(2198txo)
2019-01-06T10:29:52Z SelectStakeCoins: FOUND 21 STAKABLE ZEROCOINS
2019-01-06T10:30:00Z [default wallet] CWallet::AutoZeromint(): Nothing minted because either not enough funds available or the requested denomination size (10) is not yet reached.
2019-01-06T10:30:00Z UpdateTip: new best=5e05e84657b34722a9f75c4812e3232b8d1564d66cf2df21aad5b1d12d961f8f height=5022 version=0x20000000 log2_work=22.606595 tx=14868 date='2019-01-06T10:29:47Z' progress=0.999964 cache=0.4MiB(2200txo)
2019-01-06T10:31:02Z ListMints: added 0 zerocoinmints from DB
2019-01-06T10:31:02Z ListMints: added 28 dzpiv from DB
2019-01-06T10:31:02Z UpdateStatusInternal : Pending txid 7ba129a230b1cad066b39bc72434cdb905d04304eb2e86f60549a060ff2b8135 removed because not in mempool
2019-01-06T10:31:02Z UpdateStatusInternal : Set mint 9909c195c937c8eada227b43fe1c323bd1ab6d7df8c0793f7e710115f4d16dcc isUsed to 0
2019-01-06T10:31:02Z UpdateStatusInternal : Failed to find mint in zerocoinDB e1087f
2019-01-06T10:31:02Z Archive: archived pubcoinhash e1087f27ba4824b7c72937326a7abd129114de0e1bf9b4760915811e8006e50d
2019-01-06T10:31:02Z UpdateStatusInternal : Failed to find mint in zerocoinDB fb729e
2019-01-06T10:31:02Z Archive: archived pubcoinhash fb729ed598d8079580966a38864c257f4cde0d256e99fcd35038fcc900c341ab
2019-01-06T10:31:02Z UpdateStatusInternal : Failed to find mint in zerocoinDB a52662
2019-01-06T10:31:02Z Archive: archived pubcoinhash a5266262e1d8fef50fa4b6e3759429761bad76371cd1ba91912d50ed29284754
2019-01-06T10:31:02Z UpdateStatusInternal : Failed to find mint in zerocoinDB 6f49b6
2019-01-06T10:31:02Z Archive: archived pubcoinhash 6f49b65cd6a19c8ce231660630fcd487232c2508ca37d916f331dfc8abd56137
2019-01-06T10:31:02Z UpdateStatusInternal : Failed to find mint in zerocoinDB ab25b6
2019-01-06T10:31:02Z Archive: archived pubcoinhash ab25b60a7d901c4227ebdb66b46103fd9a853e57f397af2173554ad070691de7
2019-01-06T10:31:02Z UpdateStatusInternal : Failed to find mint in zerocoinDB 75f9d8
2019-01-06T10:31:02Z Archive: archived pubcoinhash 75f9d88633ea33d898600942433a57bbb45060bee367d0aad9a4875de037779c
2019-01-06T10:31:02Z SelectStakeCoins: FOUND 22 STAKABLE ZEROCOINS
2019-01-06T10:31:07Z ListMints: added 0 zerocoinmints from DB
2019-01-06T10:31:07Z ListMints: added 22 dzpiv from DB
2019-01-06T10:31:25Z [default wallet] CWallet::AutoZeromint(): Nothing minted because either not enough funds available or the requested denomination size (10) is not yet reached.
2019-01-06T10:31:25Z UpdateTip: new best=8fa38c957a878e98369c7a5bb7336863afbbf28de410e93787b70451b07ffad6 height=5023 version=0x20000000 log2_work=22.60682 tx=14871 date='2019-01-06T10:30:45Z' progress=0.999888 cache=0.4MiB(2210txo)
2019-01-06T10:31:27Z SelectStakeCoins: FOUND 22 STAKABLE ZEROCOINS
2019-01-06T10:31:48Z [default wallet] CWallet::AutoZeromint(): Nothing minted because either not enough funds available or the requested denomination size (10) is not yet reached.
2019-01-06T10:31:48Z UpdateTip: new best=11cd963c92c3c6cf92da3eec555d7bb9aa1168ee482baf271fbd0611d94d4995 height=5024 version=0x20000000 log2_work=22.607032 tx=14874 date='2019-01-06T10:31:28Z' progress=0.999944 cache=0.4MiB(2213txo)
2019-01-06T10:31:48Z SelectStakeCoins: FOUND 22 STAKABLE ZEROCOINS

**Comment by pmfrulez** [comment]
2019-01-06T10:27:43Z CreateNewBlock: FOUND STAKE!!
CBlock(hash=e73d6e7c541a4c31752fb61717265db26047223d920974a269bfb13dd84bd702 NO TX ON EXPLORER
2019-01-06T10:32:11Z CreateNewBlock: FOUND STAKE!!
CBlock(hash=aef25aaca8743b7d489cdea27a53220dcade3eb00947f3ac06faad4413317622 CONFIRMED +50 VEIL
2019-01-06T12:31:31Z CreateNewBlock: FOUND STAKE!!
CBlock(hash=09820573120b5d9bcaaf8554497fd598422265c0e2f6e7f1db5898bfb53ea1b4 NO TX ON EXPLORER
2019-01-06T14:05:30Z CreateNewBlock: FOUND STAKE!!
CBlock(hash=dc5cbac2a85b46d1c38dd463e231ea70c2959ba9fda2198ec2eb45f99724edcc NO TX ON EXPLORER
2019-01-06T15:05:23Z CreateNewBlock: FOUND STAKE!!
CBlock(hash=a67af989d8792d8013370cc2d5b513bf4a90d0c8a162bad8d576974b21aeaaaf NO TX ON EXPLORER
2019-01-06T15:42:21Z CreateNewBlock: FOUND STAKE!!
CBlock(hash=3a48e76369d075e121a9361b6b02dd2ca291b04cf7a4792e756bf5f06b8f0613 NO TX ON EXPLORER
2019-01-06T16:29:55Z CreateNewBlock: FOUND STAKE!!
CBlock(hash=a06520da605d08634ace9576c2dde23a90a9d884a1149338f1eca9fe7aa3b72c NO TX ON EXPLORER
2019-01-06T17:43:38Z CreateNewBlock: FOUND STAKE!!
CBlock(hash=957a8162884326181410143c44fcf0fc12d25ca4a87ba0c3c3fd00434cce3e4d NO TX ON EXPLORER
2019-01-07T05:01:52Z CreateNewBlock: FOUND STAKE!!
CBlock(hash=9e66c6a0010a88e70852b6bfcb536bf3466329454bbc14d8a6d41533bad0ec22 NO TX ON EXPLORER
2019-01-07T13:11:24Z CreateNewBlock: FOUND STAKE!!
CBlock(hash=e609483107f0379e73160c76465369696f4ef4358b8924282595ab250dd86280 NO TX ON EXPLORER
13 stakes /12invalid

2019-01-07T14:22:28Z CreateNewBlock: FOUND STAKE!!
CBlock(hash=fe2a2b23b9d94fae309a2b6524b6781fe7ea8e13c8f86fadfe0d4325e48da60a NO TX ON EXPLORER
2019-01-07T15:52:08Z CreateNewBlock: FOUND STAKE!!
CBlock(hash=785353d2b7ef7ec21c5872b32a5f8052a67295c73d428b60ee2a3ac124373e28 NO TX ON EXPLORER
2019-01-07T21:11:27Z CreateNewBlock: FOUND STAKE!!
CBlock(hash=3964fe4513a9176e3b62cc4482d28feaa83ceac2257993bb59663ca0c678a050 NO TX ON EXPLORER

**Comment by seanPhill** [comment]
With all of the messing around many people in #support were doing in the past couple of days, changing wallets, rescanning, importing zerocoins that might not be from that wallet, all of that, could this simply mean that those are not valid zerocoins for that wallet?
