### ISSUE TITLE
Opened port 58810 in router and listen=1 in conf now crazy peers/ports

### ISSUE THREAD

**Issue by JoenPool** [Veil-Project/veil#239]
I opened port 58810 in router because my connections where (in: 0 out: 6-10). Since then i get incomming connections, but also strange peers in the peerlist. Every single incomming connection results in a peer with a different port.
In the screenshot its 1 example of an peer(seed?) with an different port. I send (verstuurd) 412MB only to him?

Why do i see different ports, 1 seed already took more then 400MB, is the blockchain so big or how can he downloaded so many? Also, is it normall that incomming transactions show up with totally random ports? If its normall its fine by me i dont care about those mb's people are downloading from me (if its helping, its great), but i want to know if this port situation is normall (almost all people ban seeds with an different port).

When i ban one of this seeds with an different port, i will lose 1 incomming connection

1.0.0.6

![outgoing mbs](https://user-images.githubusercontent.com/46398822/50828181-eefe7900-1340-11e9-8c18-8ed4a59b4a13.png)

**Comment by JoenPool** [comment]
Well i think its not bad to use listen=1 then? I dont have seed=1.
How can i limit it to 12 or 16? Got like 40 connections incomming now 😁

**Comment by 4x13** [comment]
That is how it is supposed to work, those odd pirt humbers are exit ports from the peers from their network.
