### ISSUE TITLE
While mining (testnet) my node appears to get peer-banned and then forks off.

### ISSUE THREAD

**Issue by ianGre** [Veil-Project/veil#24]
# While mining (on testnet) my node appears to get peer-banned and then forks off. Veil from a previous testnet session (a week earlier) appear in the transaction list, even though the previous data folder was deleted, but the original wallet was restored from the Seed words, not from a wallet file.

I connected to a testnet peer ```addnode 145.239.0.50 add``` which then connected me to a total of four peers. (That peer node belongs to veil.suprnova.cc)

The blocks began loading from the genesis block, because I had deleted the previous data folder entirely, that had (a week earlier) generated many blocks without any connected peers.

After becoming fully synchronised I started mining ```generatecontinuous true 4```. This is on a MacPro with a 6-core 3.5GHz Intel Xeon E5 cpu and 32 GB of RAM.

My wallet _immediately_ began generating a surprising percentage of the blocks. Difficulty increased from about 3 to over 7. Later I realised that one of the four peers was no longer connected, and had fallen 1,000 blocks behind. I had over 11,000 Veil and I checked the transaction list and saw the Veil that had been generated previously by this wallet address, but the associated data folder, including the wallet file had been moved. This data folder was completely fresh!

I then realised that the other three peers had disconnected. Occasionally a peer would appear for a fraction of a second and then disappear. I checked the blockchaininfo and saw that the difficulty had reduced to about 0.0003 (from over 7). While connected, Zerocoin generation was also active, and I have to wonder whether appearing in the network and having (one or many) Zerocoin mintings rejected, might add to banscore and then get you disconnected from all of the peers, and then forking off, while generating blocks that will not be seen by other peers.

The only other hypothesis I have for how these basecoins and zerocoins could have been recovered (by seed words) is that maybe I had a connection when it appeared I did not??

**Comment by ianGre** [comment]
I closed the macOS wallet and then launched and added node to my Linux Veil wallet. This wallet never got a connection to the peer. I suspect that my IP address may have been peer-banned, for how long I do not know.

What I wanted to test this second session is the Linux wallet also had mined some days ago on testnet over 32,000 Veil, presumed invalid due to lack of  peer connections. This wallet, although it states that the latest block is zero, with the date of Friday, September 14th, shows in the transaction list the mining and zerocoin minting from the previous session, and the total of 32,580 _unspendable_ Zerocoin Veil. It shows zero RingCT and zero BaseCoin. It had been connected to my macOS wallet, before peer-banning it the other day, when a similar thing had happened, and both wallets went off generating coins separately. (In _that_ session the two peers had not synced past block 11, and the first computer had already generated coins before the connection. Only after synchronisation had stalled did I begin mining on the Linux VM.)

**Comment by ianGre** [comment]
**Next** I will do a completely new build and generate a fresh wallet and try mining after completing synchronisation.

**Comment by 4x13** [comment]
Progress? is this resolved?

**Comment by ianGre** [comment]
Having difficulty getting back to the top of the blockchain after deleting the Veil data. Will check back later "today".

**Comment by ianGre** [comment]
I don't think I/we have enough time to deal with this scenario. When the testnet blockchain is stable and then when the mainnet blockchain is up, it is going to be too low a priority to test an address that had a bunch of zerocoin on _a fork of_ the testnet chain. 

I am attributing this to an unstable testnet at the time.

I will close this.
