### ISSUE TITLE
It is unclear that "Open Configuration File" is clickable

### ISSUE THREAD

**Issue by gabrielnergaard** [Veil-Project/veil#240]
Version 1.0.0.6 on MacOS 10.14.2. In Advance → Preferences, it is unclear that "Open Configuration File" is a clickable action:

![](https://clipz.in/evvi8.png)

**Comment by seanPhill** [comment]
It is unclear that most things are clickable.

**Comment by presstab** [comment]
Bounty Price: 72.92
Estimated Hours: 1.16

**Comment by veilgets** [comment]
Developer: drag0ng
