### ISSUE TITLE
First-run background layer dimming issue on Mac

### ISSUE THREAD

**Issue by gabrielnergaard** [Veil-Project/veil#241]
Version 1.0.0.6 on Mac OS X 10.14.2.

Normally when the wallet is syncing, the modal overlay is highlighted, while the entire background is dimmed. In this version of the wallet, on this version of Mac OS, and **on the first-run only** the background around the QR code is not dimmed. This is reproducible (I've seen it on every first run).

![](https://clipz.in/epmp9.png)

**Comment by veildev** [comment]
#394 should solve this.
