### ISSUE TITLE
UI tweak to the balance labels

### ISSUE THREAD

**Issue by gabrielnergaard** [Veil-Project/veil#246]
To avoid potential confusion (which I've already seen within our own team members) that there are three coins (or states) in Veil, and to continue with the consistent presentation in all our documentation that the network supports "zerocoins" and "basecoins", let's modify these labels:

![](https://clipz.in/6bzu8.png)

To be:

- Zerocoin
- Basecoin (Shielded)
- Basecoin (Unshielded)

**Comment by gabrielnergaard** [comment]
Also, let's gray out the (?), since it's currently not a link.

**Comment by gabrielnergaard** [comment]
Note, I've made this change in a PR I'm working on.

**Comment by presstab** [comment]
NACK on the name change.

**Comment by veildev** [comment]
NACK too.

**Comment by 4x13** [comment]
Nack
