### ISSUE TITLE
Pre-fill the wallet backup save modal with the filename

### ISSUE THREAD

**Issue by gabrielnergaard** [Veil-Project/veil#247]
In other projects, problems have arisen when trying to restore wallets from backups which have been improperly named when created. In this wallet backup modal, we should pre-fill the filename with **wallet.dat** (or possibly a datestamped version like **wallet-2018-01-09-23-14.dat**).

![](https://clipz.in/uy0z4.png)

**Comment by StrontiumZ38** [comment]
I think this is a simple fix.

**Comment by veilgets** [comment]
Bounty: 247

**Comment by veilgets** [comment]
Developer: Alexeyneu
