### ISSUE TITLE
Add an "Automatic" option to the auto mint settings

### ISSUE THREAD

**Issue by gabrielnergaard** [Veil-Project/veil#248]
Currently we allow the user to only auto mint a single denomination:

![](https://clipz.in/hn0e1.png)

It would be good to add an "automatic" option that auto mints using the largest denominations first, and decrementing until the convert balance is exhausted.

**Comment by ianGre** [comment]
The only problem I see with this is that I think the larger denom will only be available after the confirmations _and_  after another of the same denom is minted, which might be a problem if no-one else, or few, are minting the large denomination.

**Comment by 4x13** [comment]
that is correct, which may freeze someones denom for a long time while they wait
