### ISSUE TITLE
Gtk "critical" warnings on Linux wallet in Terminal

### ISSUE THREAD

**Issue by ianGre** [Veil-Project/veil#25]
This wallet is still on the latest master branch.

$ ./veil-qt -testnet

(gedit:2137): GLib-GObject-WARNING **: 00:07:57.209: invalid unclassed pointer in cast to 'GeditOpenDocumentSelector'

(gedit:2137): Gtk-CRITICAL **: 00:07:57.209: gtk_list_store_clear: assertion 'GTK_IS_LIST_STORE (list_store)' failed

(gedit:2137): Gtk-CRITICAL **: 00:07:57.209: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(gedit:2137): Gtk-CRITICAL **: 00:07:57.209: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(gedit:2137): GLib-GObject-WARNING **: 00:07:57.209: invalid unclassed pointer in cast to 'GeditOpenDocumentSelector'

(gedit:2137): Gtk-CRITICAL **: 00:07:57.209: gtk_list_store_clear: assertion 'GTK_IS_LIST_STORE (list_store)' failed

(gedit:2137): Gtk-CRITICAL **: 00:07:57.209: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(gedit:2137): Gtk-CRITICAL **: 00:07:57.209: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed
vagrant@linux:/usr/local/bin$

**Comment by 4x13** [comment]
I just merged a branch to master, and I do not see this. please check again with the latest master please

**Comment by ianGre** [comment]
I recompiled the latest master on Linux and there was no error showing in Terminal when exiting the wallet.
