### ISSUE TITLE
update repository

### ISSUE THREAD

**Issue by Replicon1** [Veil-Project/veil#255]
necessary to update the main repository (https://github.com/Veil-Project/veil)
in the main repository source files of a purse of version 0.0.0.99 are still placed.
Peer v.0.0.99 - is in network and is connected to wallet.

**Comment by Replicon1** [comment]
in the main repository source files of a purse of version 0.0.0.99 are still placed.
Peer v.0.0.99 - is in network and is connected to wallet.

**Comment by 4x13** [comment]
v0.0.0.99 refers to wallets that are built from master. At any time master could be broken or not fully functioning. Users self compiling should only be building from the official release tags.
