### ISSUE TITLE
Cannot backup seed phrase according to Tutorials/FAQ in GUI

### ISSUE THREAD

**Issue by hoidsflute** [Veil-Project/veil#258]
Under "How do I backup/restore my wallet?" it says: 

![capture](https://user-images.githubusercontent.com/33523806/50987847-c27d6500-14d8-11e9-8a1a-df310f239c69.PNG)

When you click "Backup Wallet", it goes straight to a Save As window to save your wallet dat file, but no option for recovery of seed phrase.

v1.0.0.6 win64 unsigned, Windows 7

**Comment by 4x13** [comment]
will be fixed in v1.0.0.10 release
