### ISSUE TITLE
Error on quitting macOS Veil wallet

### ISSUE THREAD

**Issue by ianGre** [Veil-Project/veil#26]
The error on quitting the macOS version of the Veil Qt wallet (this time using branch convert-gui-png, but _built before_ the "faq crash fixed") has changed.

$ ./veil-qt -testnet
veil-qt(92912,0x7fff9ff02380) malloc: *** error for object 0x7fc072c04150: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

**Comment by dickvalis** [comment]
also saw something similar with source build

**Comment by 4x13** [comment]
please try with the latest source, and run gdb if possible with the binary.

**Comment by H7USHKA** [comment]
Seeing the same on macOS (Mojave 10.14.2) on the latest release

System Integrity Protection: enabled

Crashed Thread:        10  QThread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

**Comment by ianGre** [comment]
No error on the most recent exit from updated Mac wallet.

**Comment by ianGre** [comment]
In macOS wallet I got the old crash message again.

In the GUI: ... unexpectedly

Process:               veil-qt [34269]
Path:                  /usr/local/bin/./veil-qt
Identifier:            veil-qt
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        bash [3679]
Responsible:           veil-qt [34269]
User ID:               501

Date/Time:             2019-01-03 14:18:57.844 +1100
OS Version:            Mac OS X 10.13.6 (17G3025)
Report Version:        12
Anonymous UUID:        D750EEFA-64FE-DEC8-D1E0-886CA5371378


Time Awake Since Boot: 21000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called
*** error for object 0x7fa441d042d0: pointer being freed was not allocated
 


in the Terminal:

objc[34269]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8e557c90) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1182c4cd8). One of the two will be used. Which one is undefined.
veil-qt(34269,0x7fff919da380) malloc: *** error for object 0x7fa441d042d0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

**Comment by ianGre** [comment]
I exited the released MacOS binary 1.0.0.4 today and it did not produce the crash. I wonder if this only effects the ones compiled on my computer. Closed it again just now, and no crash.

**Comment by ianGre** [comment]
Found that it affects the released binary IF launched from the Terminal, such as when using the testnet startup switch. When launched in the GUI it seems fine.

**Comment by seanPhill** [comment]
Verified this crash again (on v1.0.1.2) affecting only when launched from Terminal. No crash, as previously mentioned, when launching from the GUI.

**Comment by seanPhill** [comment]
This one is completely different to what happened with #338, which I don't get any more, since loading a snapshot.

This error only happens after quitting when the wallet is launched from the command line, and has no effect whatsoever on operation. The debug log indicates it successfully closed, before MacOS generates the crash report, so it is a minor error.

I think it should remain, but be given a low priority.
