### ISSUE TITLE
PoW producing empty blocks

### ISSUE THREAD

**Issue by Iconoclasta** [Veil-Project/veil#262]
Following an approximate analysis of the VEIL mainnet, I have noticed that from block 9820 onward most if not all blocks mined via PoW do not include the network transactions. All 1st confirmations are rather given by blocks produced by stakers via PoS.
This has caused the mempool to fill up and significant delay in transaction confirmations to the point that transactions get dropped from the mempool and reversed to the sender.

**Comment by presstab** [comment]
Mining pools have begun doing this intentionally while we fix some items that have been causing them trouble.
