### ISSUE TITLE
Staking is not working with tag 1.0.0.8 or master compiled in linux

### ISSUE THREAD

**Issue by reb0rn21** [Veil-Project/veil#264]
As stated master or tag 0.0.8 compiled in linux
staking is on but Getwalletinfo:
"staking_active": false

Also CPU use why staking is enebled in GUI use 30% + of CPU

**Comment by seanPhill** [comment]
Can you please check again? My wallet is staking fine on testnet and '"staking_active": true'.

**Comment by n1njam1rko** [comment]
Same problem here, staking_active: false. Linux. In my case cpu usage is insignificant. Tried just using new wallet with old chain, also tried deleting everything and recovering from seed, zero coins are there, but staking is "false", although gui shows that it's active.

**Comment by JoenPool** [comment]
On Win 10 64 the same with an compiled qt 0.8

**Comment by Iconoclasta** [comment]
On Cli 0.8 I am experiencing the same issue `  "staking_active": false`
This issue was reported in discord since 09e2a45

**Comment by presstab** [comment]
See the same problem for me overnight. Debugging now.
