### ISSUE TITLE
Disappearing Text in 1.0.0.9

### ISSUE THREAD

**Issue by Larcea** [Veil-Project/veil#270]
I have this issue with 1.0.0.9.

However I have pegged it to the "Dark" appearance for the MacOS Theme.

When I switch to "Light" the text all comes back.

Dark Theme:
![screen shot 2019-01-11 at 3 47 23 pm](https://user-images.githubusercontent.com/38234120/51061819-29bf1600-15ba-11e9-9689-171a003376d1.png)

Light Theme:
![screen shot 2019-01-11 at 3 52 03 pm](https://user-images.githubusercontent.com/38234120/51061840-3ba0b900-15ba-11e9-921c-12357dd890f9.png)

Issue: Text visually disappears.
OS: MacOS (Mojave)
Build: 1.0.0.9
Workaround: Change from Dark to Light theme.
Related Issue: #60

Additional Information:
- Compiled wallet with `Make Deploy` option.

Attempted resolutions:
- Recompiled wallet
- Recompiled wallet with `sudo` rights
- Opened wallet with `-resetguisettings` command line.

**Comment by seanPhill** [comment]
This has now also been observed by an Arch Linux user who had Dark Mode enabled. The wallet displayed white text on a white background and was therefore illegible.

The user will try the CLI wallet instead.

**Comment by codeofalltrades** [comment]
Bitcoin core disabled the dark setting on macOS
https://github.com/bitcoin/bitcoin/commit/df5131bd41ea86c5b404cd6091284d9ac62368e7
