### ISSUE TITLE
Send Zerocoin spends amount without confirming spend (cancel not possible)

### ISSUE THREAD

**Issue by MisterKangaroo** [Veil-Project/veil#272]
Send Zerocoins and canceled the tx in the "Send confirmation"-dialog...
the zerocoin balance was subtracted from my wallet balance even when (before) clicking cancel button.
Here are screenshots from before spending and after clicking send in the send tab:

![beforeselftx](https://user-images.githubusercontent.com/43561981/51068876-f2398380-1624-11e9-8a28-4063ed843de1.PNG)

![afterselftxbeforeconfirmation](https://user-images.githubusercontent.com/43561981/51068877-f4034700-1624-11e9-9ae1-cca9e748af74.PNG)

Additional info about the context:
Win 10 x64
GUI
Version 1.0.0.9

This issue has been confirmed by multiple people including myself

**Comment by CryptoSifu** [comment]
I had the same issue of not being able to cancel the transaction after hitting send the first time. My transaction arrived in my other wallet but the spent change was not returned to RingCT. It has disappeared. I sent a total of two transaction totalling 0.66 +- and am missing the change from 20 zerocoins. I tried all the same commands above but my balance is still missing.

**Comment by MisterKangaroo** [comment]
my issue would need further investigation... perhaps these zerocoins were minted before the testnet restart

**Comment by seanPhill** [comment]
Likewise, the recipient confirmed receipt while the Confirm - Send button (in windows 10) was still there waiting to click! (After a long lag of "not responding", which would be when other users insist their wallet or computer has crashed, when they only have to wait.) 

**However**, I tried this earlier on MacOS and I got a pop up dialog with no words, and red warning symbol. I tried to screenshot it but my screenshot keys would not respond. One of the key combinations included the spacbar, which initiated the button click, which then proceeded to a transaction failed dialog! (The recipient did not receive the funds at that time, so I decided to try in the Windows VM, where the spend without confirmation took place.)
![virtualbox_windows 10 dev trial_13_01_2019_11_31_37](https://user-images.githubusercontent.com/46495592/51080021-e8e50f80-1727-11e9-8bc6-836e8011df66.png)

**Comment by seanPhill** [comment]
Regarding the failed transaction on the Mac wallet, I tried again with a thousand tVeil some time later and it worked! Without a great, long pause either.
![screen shot 2019-01-13 at 12 18 20 pm](https://user-images.githubusercontent.com/46495592/51080324-a4f50900-172d-11e9-8814-b6541dee252b.png)

**Comment by seanPhill** [comment]
But, and one last note. I followed this up with a payment to the same account (on the Mac wallet) for 1349.451 and the Mac wallet has been frozen for more than an hour. (Not sure which other issue number to put that to.)

**Comment by presstab** [comment]
Will fix this.
