### ISSUE TITLE
Error message when sending fractional zerocoin amounts (18 zerocoins) 

### ISSUE THREAD

**Issue by MisterKangaroo** [Veil-Project/veil#273]
Get an empty error message when sending fractional zerocoin amounts (18).

![error fractional zerocoin amount](https://user-images.githubusercontent.com/43561981/51069130-60804500-1629-11e9-9260-dfbbe5a207a1.PNG)

![tx failed](https://user-images.githubusercontent.com/43561981/51069182-590d6b80-162a-11e9-8fe8-65e6dcfde197.PNG)

On a second attempt the wallet crashed.

Win 10 x64
Version 1.0.0.9
[debug_crash.log](https://github.com/Veil-Project/veil/files/2751692/debug_crash.log)
[debug_errormessage.log](https://github.com/Veil-Project/veil/files/2751694/debug_errormessage.log)

**Comment by presstab** [comment]
Should be fixed with #327 . Reopen if not.
