### ISSUE TITLE
RingCT Change Missing from Zerocoin Spend

### ISSUE THREAD

**Issue by CryptoSifu** [Veil-Project/veil#275]
I sent two fractional transactions of approx 0.33 veil (zerocoin) each from one wallet to another. 
I was unable to cancel the transaction once it was initiated but before I confirmed it with the final send (issue #272). The transaction processed without requiring any further confirmation. 
The transactions did confirm on the blockchain and arrived in my other wallet but the spent change was not returned to RingCT. It has disappeared from my balance. I tried all the commands I could think of to recover the missing RingCT coins (rescanblockchain etc), but I am still missing 20 veil from my balance (less the transaction amounts).
Win 10 x64 OS wallet v1.0.0.9

**Comment by presstab** [comment]
So none of your transactions confirmed?

**Comment by CryptoSifu** [comment]
The transactions confirmed but the change is gone. It spent 10 zerocoin. I received .3 in the receiving wallet for each transaction but there is no sign of the remainder (change). 
I was told it should have gone to RingCT but it’s not there. 
My sending wallet is exactly -20 zerocoin and my receiving wallet is exactly +0.61353320 RingCT. 
Where is the difference?

**Comment by CryptoSifu** [comment]
Update: on a seperate wallet and machine I sent ct to basecoin and there was some change left in ct. the transaction went through, but the change in ct has disappeared. I suspect it is the same issue as the one noted above. 
Something is wrong with the ct balance in wallet.

**Comment by presstab** [comment]
8937e0e4bceac463c0548216f19b86aead1debaa

**Comment by CryptoSifu** [comment]
Issue not resolved. 
I am unable to recover my lost spent change.

**Comment by seanPhill** [comment]
Please show the steps you have taken to recover or detect the CT or RingCT balance. (Transaction IDs?)

Did you try ```rescanblockchain``` ?

**Comment by CryptoSifu** [comment]
I did a fresh install and restored from seed the. used the following commands to recover missing ct coins without success. 

getbalances
getzerocoinbalance
listzerocoinamounts
getarchivedzerocoin
reconsiderzerocoins
resetspentzerocoin
resetmintzerocoin true
searchdeterministiczerocoin 0 5000 2
getbalances
getzerocoinbalance
listzerocoinamounts 

There are approx 19.4 ct coins missing from spent change over two transactions.

**Comment by CryptoSifu** [comment]
I see the issue is closed. Has it been fixed for next update?
