### ISSUE TITLE
Veil Qt wallet tray icon incorrectly coloured

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#28]
**Describe the issue**
Veil Qt wallet tray icon is incorrectly coloured. Note this is not reflective of the incomplete test binaries which had no icon.

**Can you reliably reproduce the issue?**
Yes per CryptoMax

**If so, please list the steps to reproduce below:**
Run Veil Qt wallet and look to system tray.

**Expected behavior**
The wallet tray icon should be blue-coloured, in accordance to the brand.

**Actual behavior**
The tray icon is purple-coloured rather than blue.

**Comment by StrontiumZ38** [comment]
On investigation, this may simply be a case of purple representing testnet in newer build, where blue is used for mainnet still. If this is the case by design please disregard.

**Comment by 4x13** [comment]
Yes, Testnet icon is Purple to shoiw that you are not on testnet.
