### ISSUE TITLE
GUI address ownership mix-up - displaying address not owned by wallet 1.0.0.9

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#284]
**Explain issue**
(From Rock-N-Troll) This is a GUI visual issue in the Veil QT wallet.

In basecoin transactions where there are 2 outputs with at least 1 of them being the recipient's (my own)
The wallet has a visual bug that, suspectedly, displays the string of the first basecoinaddress as the receiving address (might possibly be because of the order they appear in the transaction output).
Appears to occur when the wallet recipient's basecoin address is actually the 2nd output address in the transaction.
The wallet displays the CORRECT received amount by my actual basecoin address, BUT displays the wrong basecoin address as the address that received the funds.

**Can you recreate it?**
Yes

**Steps to recreate**
Receive a transaction where there are at least 2 basecoin addresses in the output and 1 of those basecoin addresses is your own. This is a common type of transaction that occurs when mining pools send to  miners' wallets and then back to their own with the change.

**Expected behaviour**
The wallet should display the user's basecoin address and not an address the wallet does not own. Displaying someone else's address is confusing and can lead to incorrectly sending funds to that address later even though the user does not own that address.

**Actual behaviour**
In basecoin transactions where there are 2 outputs with at least 1 of them being the recipient's (my own)
The wallet has a visual bug that, suspectedly, displays the string of the first basecoinaddress as the receiving address (might possibly be because of the order they appear in the transaction output).
Appears to occur when the wallet recipient's basecoin address is actually the 2nd output address in the transaction.
The wallet displays the CORRECT received amount by my actual basecoin address, but displays the wrong basecoin address.

**Comment by JoenPool** [comment]
Yep i also reported this to support, same bug is in 0.8
