### ISSUE TITLE
Module layering mess on first run Qt wallet

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#30]
**Describe the issue**
Veil Qt wallet on first run has a mess of poorly overlapped modules that produce an unsightly result.

**Can you reliably reproduce the issue?**
Yes

**If so, please list the steps to reproduce below:**
Run Veil Qt wallet for the first time and progress past seed and password setup.

**Expected behavior**
The wallet modules should correctly layer and produce an aesthetically pleasing result.

**Actual behavior**
The wallet modules poorly overlap and create rough edges and poor overlay with black transparent box.

**Platform/OS**
Windows

![image](https://user-images.githubusercontent.com/38264865/50471055-67d30c00-09f6-11e9-8599-491a124e4081.png)

**Comment by veildev** [comment]
Solved. `gui-fixes` branch.
