### ISSUE TITLE
v1.0.0.10 wallet seems to sleep when not in foreground.

### ISSUE THREAD

**Issue by seanPhill** [Veil-Project/veil#305]
This did not happen on earlier versions, but just the past couple of days when I bring the wallet to the foreground **then** it decides to catch up the remaining few hundred blocks!

In the case of my testnet wallet, this means that I have not been staking most of the time since the upgrade.

This has happened overnight, and during the day when I have been out, and just while the other wallet or Discord or any other Mac app has been in the foreground, or maybe only while the wallet has been in the background for a long time.

v1.0.0.10 self-compiled.

MacOS 10.13 High Sierra.

Mac Pro Xeon 3.5GHz 6-cores, 32 GB RAM. SSD.

In the below attached debug log I brought the mainnet wallet to the foreground after being in the background for not too long, at about time (UTC) 23:24 or 23:25 (not sure which, exactly). 

[debugLog(portion).txt](https://github.com/Veil-Project/veil/files/2766505/debugLog.portion.txt)

**Comment by seanPhill** [comment]
I don't know if this is some kind of weird coincidence, or just after a certain amount of time. After checking the mainnet wallet, and this issue, and then going back to the testnet wallet, I verified that both still had a block within the past minute or two. The main potential issue this could cause is not staking.

**Comment by seanPhill** [comment]
Tested with daemon=1 at the start of the veil.conf configuration file, and it actually appears to have solved this. (I have not won (testnet) stake in that time, but the debug.log indicates activity in the couple of hours I kept the wallets minimised.

**Comment by Veil-Project** [comment]
u may have you sleep settings on, which should be turned off
