### ISSUE TITLE
ERROR: TestBlockValidity: Consensus::ContextualCheckBlockHeader: time-too-old, block's timestamp is too early (code 16)

### ISSUE THREAD

**Issue by toptim** [Veil-Project/veil#306]
How to fix?
ver 1.0.0.10
time UTC
seed=0
ubuntu 16

**Comment by seanPhill** [comment]
Possibly a VM configuration issue? (If so, please see below.) 

Toptim, is this a Virtual Machine on a Windows host?

Windows expects local time in the BIOS clock while Linux may expect UTC (GMT).

Your Virtual Machine software may have a setting to fix this, or your Linux may be able to be told that the machine time is (whichever time zone). 

(I had to deal with this a few years ago with a lab of Macs occasionally running Windows in bootcamp, setting the wrong time when booted on Windows.)

**Comment by toptim** [comment]
no VM, clear ubuntu server 16
