### ISSUE TITLE
Unable to spend CT "still AddBlindedInputs failed: ringctwallet Insufficient funds.. (code -4)"

### ISSUE THREAD

**Issue by Veil-Grumpy** [Veil-Project/veil#307]
Unable to spend CT trough debug console:

"basecoin_spendable": "1.76459354",
  "basecoin_unconfirmed": "0.00",
  "basecoin_immature": "0.00",
  "ct_spendable": "365.12",
  "ct_unconfirmed": "0.00",
  "ct_immature": "0.00",
  "ringct_spendable": "22.2407984",
  "ringct_unconfirmed": "0.00",
  "ringct_immature": "0.00",
  "zerocoin_spendable": "450.00",
  "zerocoin_unconfirmed": "0.00",
  "zerocoin_immature": "0.00"

![image](https://user-images.githubusercontent.com/46780798/51314507-1f849800-1a50-11e9-9ea7-78201af93c9a.png)

Spending with sendstealthtobasecoin <address> <amount> returns this error:
still AddBlindedInputs failed: ringctwallet Insufficient funds.. (code -4)

I've already tried to:
rescanblockchain
change sending amount to 360

No change..

System:
Windows 7
Veil v1.0.0.10-37615030e

**Comment by CryptoSifu** [comment]
I have the same issue. CT Spendable balance that cannot be spent. error refers to ringctwallet insufficient funds

**Comment by presstab** [comment]
Should be resolved with latest rescanning commands. `rescanringctwallet` and `rescanblockchain`.
