### ISSUE TITLE
Wrong fee zerocoin mint 0.01755811 instead of 0.01

### ISSUE THREAD

**Issue by Veil-Grumpy** [Veil-Project/veil#308]
Windows 10 Pro
Version 10.0.17763 build 17763

Wallet version:
Veil Core version v1.0.0.10-37615030e (64-bit)

Problem description:
One transaction used more fee then it should have done.
Below is 3 transactions where I have done manual minting och coins from basecoins to zerocoins:
First one is before, second is the transaction with wrong fee, third is transaction after.

Transaction with correct fee:
https://explorer.veil-project.com/tx/d3ba60dca8d1621dcf02674d42e14868cbb0efbfde01b9c7085f23b7f21e974b

Transaction with wrong fee:
https://explorer.veil-project.com/tx/5c00628a0916a7288d0a37dbf6b1247e68ca19a281c668df4f96698c2e434ec7

Transaction with correct fee:
https://explorer.veil-project.com/tx/711142fd7a14e26c0d476566675b4e2c109bc2ddc4798ef2eeeca380ea0df5f3

![wrongfee](https://user-images.githubusercontent.com/46780798/51318315-53fd5180-1a5a-11e9-8e23-7a4a64e2c444.png)

**Comment by seanPhill** [comment]
I noticed that the higher fee one has seven inputs. Neither of the others do. 0.01 might be the **minimum** fee. I think that calculated fees should always be displayed to the user though, especially as one of the inputs was very small.

**Comment by presstab** [comment]
3dff9fb3c57bd2ee84a9372117a6c8f402101e5d
