### ISSUE TITLE
veil.conf not automatically created in MacOS wallet (released executable) on testnet

### ISSUE THREAD

**Issue by ianGre** [Veil-Project/veil#31]
The veil.conf file was not automatically created in the MacOS wallet (released "Veil wallet.app" executable) on testnet.

I checked back in my archives of old data folders and it was not created on the previous build (convert-gui-to-png branch), but it did exist in the earlier master branch build.

**Comment by 4x13** [comment]
the veil.conf file has to exist in the veil directory regardless of whether it is mainnet or testnet. the wallet will ignore the peers added that reside on testnet and vs versus.

**Comment by ianGre** [comment]
I was just testing the latest Win64 wallet and noticed that it also is not created at the time of installation or of first use. So this is exactly the same as the Mac wallet.

However, veil.conf _is_ created when you click "Open Configuration File" in the Options window.

It seems that maybe this is _by design_ and is not actually a bug, although it is not what people expected, and maybe should be changed, so that veil.conf is already there when you look for it. 

In any event it is not a critical problem.

**Comment by ianGre** [comment]
I guess I can close this now. The only thing to note, if creating veil.conf at first launch is to not overwrite one if it is already there.
