### ISSUE TITLE
Sign message function is not working.

### ISSUE THREAD

**Issue by seanPhill** [Veil-Project/veil#311]
The sign message function was unable to sign a message with an address chosen in its interface.

I expected, when I chose an address from the list provided, that I could sign the message I typed.

It displayed an error message. ```The entered address does not refer to a key. Please check the address and try again.```

I tried this on basecoin and stealth addresses and it happened each time. I also tried it on my testnet wallet, which contained funds. I only had a stealth address in this, and got the same message.

To get to the Sign Message or Verify Message window, (in MacOS) click and hold the mouse on the Veil wallet's Dock icon, then it gives you a number of choices, including "Sign message" and "Verify message". 

1.0.0.10

Mac Pro (3.5GHz 6-core Xeon, SSD, 32 GB RAM)

Also in the address chooser it refers to **Bitcoin** address, so I'm wondering if this feature was not looked at by the Veil team. This is a different address chooser than you get in the main Veil wallet window. 

I didn't find anything in the debug log that referred to the error message.

**Comment by 4x13** [comment]
I believe you will only be able to sign a basecoin address?? but having the ability to sign other address types would be cool as well.

**Comment by presstab** [comment]
Bounty Price: 187.5
Estimated Hours: 3
