### ISSUE TITLE
Why do received zerocoins need to be re-minted?

### ISSUE THREAD

**Issue by hoidsflute** [Veil-Project/veil#314]
I admit that I still don't understand CT/RCT/Zerocoin so that could play into this but here's the issue-

A user sent me 50 zerocoins.  On his console, `getbalance` confirmed that those 50 coins were zerocoins.  When I receive them, they go to my CT balance and need to be reminted, even though he already minted them.  This can't be right, correct?

**Comment by StrontiumZ38** [comment]
It's exactly right. When you send with Zerocoin you're not sending the actual zerocoins to the receiver. Check this out for an easy explanation https://medium.com/@turtleflaxpivx/how-zerocoin-works-in-5-minutes-a88d0144fff0

@4x13 this can be closed.
