### ISSUE TITLE
Console allows for spending while wallet is unlocked for staking only.

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#315]
> "Hello all, I am not sure who to notify about something I noted when using the GUI wallet in Linux, I have not tried this in any other iteration of the wallet. 
> 
> I found that after having used the upper staking button and entering password for "staking only" per the FAQ's on freshdesk, that I was able to send coins from
> 
> the console with commands without being prompted to enter a password. I did this once accidentally so I tried it again intentionally after locking  + repeating the
> 
> staking unlock procedure and verifying that lock symbol at bottom right indicated locked.
> 
> Could someone else using this same wallet and perhaps others please try and repeat this and notify the proper individuals if I am correct, thanks."

This has been confirmed by Max and Rock-N-Troll. I have no bothered to replicate due to this.

**Comment by 4x13** [comment]
Yes, I agree, the wallet should prompt the user to enter a password again after the wallet is unlocked for staking only in order to spend or access certain console functionality.

**Comment by presstab** [comment]
Bounty Price: 166
Estimated Hours: 2
