### ISSUE TITLE
getnewaddress addresstype=legacy

### ISSUE THREAD

**Issue by goodthebest** [Veil-Project/veil#316]
Well issue is linux daemon wallet isn't issuing legacy address, even though I've started the wallet with **addresstype=legacy**

Expected behaviour is to get a legacy address.

Current wallet behavior is, 

![image](https://user-images.githubusercontent.com/1715740/51433920-7ddb9180-1c6f-11e9-8460-43180260fdbd.png)

I'm using headless wallet, version v1.0.0.10 for linux

v1.0.0.10 and it was pre compiled download from github repo

I'm running it on on linux ubutnu 16.04.5

**Comment by presstab** [comment]
Use `getnewbasecoinaddress` to interface as you would expect to interface with bitcoin.
