### ISSUE TITLE
walletpassphrase with an unlock time of 0 does not work or print an error message

### ISSUE THREAD

**Issue by CryptoMaximalist** [Veil-Project/veil#317]
When using "veil-cli walletpassphrase" to unlock the wallet, input of 0 for the timeout does not print any message, as if it had worked, but it does not unlock the wallet.  I'm aware of another coin which uses this value to specify indefinite unlock time.  However if it is out of range, the RPC description should specify this and an error should be printed

veil-cli walletpassphrase MyPassphraseIsNowPublicOnGithub true 0

The linux x64 1.0.0.10 wallet binary

Linux 64, NVMe SSD

The debug file shows the zerocoin hash when the command is run, but does not indicate any issues

**Comment by presstab** [comment]
This does work. But you specified to have your wallet unlocked for 0 seconds and then relocked.
