### ISSUE TITLE
Problems with 'maturity' field in GUI balance display and getbalances command output for all coin types

### ISSUE THREAD

**Issue by CryptoMaximalist** [Veil-Project/veil#318]
I'll include 2 types of issues here:

A) As I understand it, maturity refers to staking eligibility.  Given that basecoin, CT, and RingCT do not stake, there should be no concept of Maturity for those coins and no reason to list this

B) The Zerocoin maturity (or rather "Immature") field tends to always show the same value as the Unconfirmed field.  I would expect receiving a zerocoin of size 10 would show as 10 unconfirmed, 0 immature for 6 blocks (or whatever it is), then once confirmed it would show as 10 immature, 0 unconfirmed.  Then of course after 200 blocks it all goes to confirmed/spendable balance

Currently it would show 10 in both immature and unconfirmed for a few blocks, then it all transfers to confirmed/spendable

The staking and maturity does work correctly in the background.  It finds the correct amount of stakeable zerocoins according to confirmations/maturity and automatically adds in mature ones as they hit 200 confirms

Reproduces reliably upon receiving one or more zerocoins

1.0.0.10 ubuntu 18.04 x64

**Comment by StrontiumZ38** [comment]
@4x13 @presstab can this please get labels.

**Comment by presstab** [comment]
325d7c12ac6856acdb9fd3198ca36a3db469ac31
