### ISSUE TITLE
Difficulty wildly varying! Is reporting error or is it real?

### ISSUE THREAD

**Issue by ianGre** [Veil-Project/veil#32]
The mining difficulty is varying wildly! Is this a reporting error or is it real?

getmininginfo -->
```
  "blocks": 7576,
  "currentblockweight": 4000,
  "currentblocktx": 0,
  "difficulty": 0.004190474607137011,
  "networkhashps": 568466053402.7554,```

```
"blocks": 7593,
  "currentblockweight": 5244,
  "currentblocktx": 1,
  "difficulty": 17916.17690491486,
  "networkhashps": 651041536223.8818,
  "pooledtx": 1,
  "chain": "test",```

```
  "blocks": 7595,
  "currentblockweight": 6488,
  "currentblocktx": 2,
  "difficulty": 0.004467099896173242,
  "networkhashps": 611342315891.5979,```

Is it normal that difficulty would adjust by an order of millions? (And back again?) Surely it should be the higher figure.

**Comment by ianGre** [comment]
I have a theory. Please confirm.

Does the difficulty work out to a completely different number, depending on the algorithm for that block?

Secondly, are people getting banned by other peers after they have a problem getting the proper choice of algorithm? And then once you get one wrong, you never catch up?

**Comment by presstab** [comment]
Proof of Stake and Proof of Work both have their own independent difficulty. More likely though is just a normal adjustment in difficulty. With so few on the network, it is easy to make diff change fast.

**Comment by ianGre** [comment]
Thanks! Yes, I was just going to do a block by block comparison to see when it changes.
