### ISSUE TITLE
Adressbook in Send tab doesnt generate new adresses

### ISSUE THREAD

**Issue by MisterKangaroo** [Veil-Project/veil#324]
Addressbook in Send tab doesnt generate new adresses when clicking "NEW" adress,
instead it asks to enter an address.

![doesntgenerate](https://user-images.githubusercontent.com/43561981/51583213-c5605880-1ecf-11e9-8d6b-8217b8a7f3c4.png)

When pasting an existing adress from the Adressbook it gives an error... see below:

![pasted](https://user-images.githubusercontent.com/43561981/51583282-1e2ff100-1ed0-11e9-9937-30054e874d59.png)

Compiled from master.
Ubuntu 18.04LTS

**Comment by furszy** [comment]
What is the issue here?.

The UI is telling you on the first screenshot that you haven't wrote any address and in the second screen is telling you that the address already exist.

**Comment by MisterKangaroo** [comment]
The first screenshot show what happens if you enter no address. But it doesn't generate one afterwards.

The second screenshot of the response of you enter a already (in the address book or console) generated address.

Beside that the address lusty first show any addresses in the window, not even already existing addresses.

**Comment by furszy** [comment]
It's a contacts dialog, you are entering there from the send screen. It's to ** send ** to someone, not to create own addresses.

**Comment by MisterKangaroo** [comment]
Ah ok... Makes sense.
Sorry, my fault.

Beside that I think it still would make sense to have the ability to generate own addresses there for sending to the own wallet (like re-minting).
But that's more a feature request than an issue.

**Comment by furszy** [comment]
If you want to manually mint coins there is a dialog created specifically for that purpose on the settings screen. Maybe have a shortcut here is not bad but well, that is another topic.

Closing this issue.
