### ISSUE TITLE
Inconsistencies in font sizes (GUI)

### ISSUE THREAD

**Issue by MisterKangaroo** [Veil-Project/veil#325]
There are some inconsistencies in font sizes on the new master.

![fontsizes01](https://user-images.githubusercontent.com/43561981/51583474-073dce80-1ed1-11e9-8bcc-062d5d7b93f8.png)
![fontsizes02](https://user-images.githubusercontent.com/43561981/51583476-09079200-1ed1-11e9-8527-781a6cd6c7de.png)

Ubuntu 18.04LTS
Compiled from master

**Comment by StrontiumZ38** [comment]
@4x13 @presstab can this please get labels.

**Comment by presstab** [comment]
Bounty Price: 250
Estimated Hours: 4

**Comment by codeofalltrades** [comment]
Commit cbb057f - Fixes screenshot 1 - Settings
Commit 52eee7a - Fixes screenshot 2 - Address Book
