### ISSUE TITLE
Transaction Detail data is incorrect

### ISSUE THREAD

**Issue by ianGre** [Veil-Project/veil#33]
In macOS wallet (released Veil wallet.app version) on testnet, the Transaction Detail view has incorrect data.

If clicking on a Zerocoin Mint item, the details seem okay, except for the date, which is always 25/10/18. (I reported this early on, but didn't put it directly into Github.)

If clicking on a Basecoin Mined item, in addition to the date problem, the Fee amount shows in the order of positive or negative _billions_ of Veil or thereabouts!

![screen shot 2018-12-28 at 12 27 36 am](https://user-images.githubusercontent.com/36124423/50481945-6cb8af80-0a38-11e9-8718-25edb55bb5bf.png)
![screen shot 2018-12-28 at 12 28 06 am](https://user-images.githubusercontent.com/36124423/50481946-6cb8af80-0a38-11e9-9f50-61db8cb3e19e.png)

**Comment by ianGre** [comment]
I have a confirmed transaction for comparison of certain details.

gettransaction 49f5495eaa7de5c2d3200b4be017146fd8905c5e36da0728fd3c9a39242a27d7

```{
  "amount": 0.00000000,
  "creditbase": 0.30796280,
  "debitbase": 9.96000000,
  "creditanon": 0.00000000,
  "debitanon": 0.00000000,
  "fee": -9.65203720,
  "confirmations": 64,
  "blockhash": "299434f239ab2a064c53b658670177940cca6263f37fc31f0cf13efd3676c67b",
  "blockindex": 3,
  "blocktime": 1546044574,
  "txid": "49f5495eaa7de5c2d3200b4be017146fd8905c5e36da0728fd3c9a39242a27d7",
  "walletconflicts": [
  ],
  "time": 1546044349,
  "timereceived": 1546044349,
  "bip125-replaceable": "no",
  "details": [
    {
      "address": "tps1q65355gq228g38hnmpdurr4u9pe5nqxn83cgg2h",
      "category": "send",
      "amount": -9.65200000,
      "vout": 0,
      "fee": -0.00003720,
      "abandoned": false
    }
  ],
  "hex": "020000392200000121010ef12faef7f58cd4c0df0d9b88151c10a215cdca0251115b355b843f5ff30100000048473044022016700b6a9065eeae72e40337fdc96c0c9705af0002b7b007bdb0949a0ab55c2602204495f0ba8d3b7da9141e7c5f2f2d79ddf7d19d66144f8d7ae5bd67c8ab29cc5b01feffffff020180c8873900000000160014d5234a200a51d113de7b0b7831d7850e69301a6701f8e9d501000000001600141246193b67281178a98d98d1577e14dcc9f13345"
}
```

Note that the above transaction fee in two different places is about vastly different. In fact, when I made the transaction in the Spend dialog it told me the fee was going to be 0.3... Veil, so I edited the amount to allow for that. The first mention of fee above, -9.65203720, is (in inverse) really the amount the recipient would have received. The second mention of fee above, -0.00003720, maybe is the actual fee, because I think I received 0.30796280 Veil in change (from the 9.96000000 coin spent), even though I had to add that 0.3 to allow for a fee about 0.3... at spend time.

If you look this up in the Veil Testnet block explorer at https://159.69.223.84:19147/tx/49f5495eaa7de5c2d3200b4be017146fd8905c5e36da0728fd3c9a39242a27d7 you will see 0.3079628 tVeil being returned to tb1qzfrpjwm89qgh32vdnrg4wls5mnylzv69xyfrk8 (but I see in my Coin Control that I received 0.30796280 to address tps1qzfrpjwm89qgh32vdnrg4wls5mnylzv697vdklx (you can see some similarity with those addresses) on txid: 49f5495eaa7de5c2d3200b4be017146fd8905c5e36da0728fd3c9a39242a27d7 (the same). And the block explorer shows the fee as 0.0000372 tVeil.
The Block explorer is correct in the way it displays the transaction.
Mined Time | Sat, 29 Dec 2018 01:49:34 CET
-- | --
In Block |  
In Block Height | 8783
Total Input | 9.96 tVeil
Total Output | 9.9599628 tVeil
Fees | 0.0000372 tVeil

In the wallet's transaction list it shows as Basecoin sent to tps1q65355... -9.65203720 VEIL 12/28/2018 16:45 and in the Transaction Details view it shows the fee as 0.3720 VEIL (probably the amount that was shown in the spend dialog). As mentioned earlier, the date shows a default 25/10/18 and Size shows 0.00 Kb, and Inputs shows 0.

**Comment by 4x13** [comment]
moved to a new issue
