### ISSUE TITLE
Need help with add support Veil in BTCPayServer. 

### ISSUE THREAD

**Issue by grigorov** [Veil-Project/veil#334]
Hi, i think add support Veil in BTCPayServer - https://github.com/btcpayserver/btcpayserver/
but i not find documentation or sample code work with veil... Need add support to https://github.com/MetacoSA/NBitcoin/tree/master/NBitcoin.Altcoins  and https://github.com/dgarage/NBXplorer

Maybe who is anybody help me?

**Comment by StrontiumZ38** [comment]
@4x13 may want to investigate this and help you out grigorov. I'm sure he'll see this soon.

**Comment by grigorov** [comment]
C++ i'm not know. I need protocol implementation in programming languages (C# or  python or Erlang(elixir) or java/kotlin). Protocol specification. Maybe algoritm specifiaciton X16RT? i can't find in github.

**Comment by StrontiumZ38** [comment]
@grigorov looks like you didn't hear back here. I suggest you head onto Discord if you haven't already with this.

**Comment by StrontiumZ38** [comment]
@presstab might want to close this to help clear up issues. I assume this has/can be followed up on Discord if necessary.

**Comment by StrontiumZ38** [comment]
@4x13 @presstab probably best to close this to clear issues.
