### ISSUE TITLE
Staking not confirmed

### ISSUE THREAD

**Issue by pcarballeda** [Veil-Project/veil#344]
After two last wallet updates my stake is not confirming anymore as usual. I am not sure if this is the usual behaviour now but before I updated my wallet it didn't work by this way, as you can see I have other stakes confirmed and it was before I updated the wallet.

I am using Veil Core version v1.0.1.3-3330b4a61 (64 bit) on Windows 10. I updated my wallet as other times: uninstall previous version, backing up my wallet.dat and installing veil-1.0.1-win64-setup-unsigned.exe.

![image](https://user-images.githubusercontent.com/4659020/51895743-352c8280-23ab-11e9-8e2d-fe9427721fd5.png)

**Comment by 4x13** [comment]
Those are called orphans and are typical in both PoW as well as PoS consensus systems
