### ISSUE TITLE
Missing pending zerocoin denoms after running recovery command

### ISSUE THREAD

**Issue by chainlayer** [Veil-Project/veil#345]
Been missing zerocoin mints after running these recovery commands during a mint is pending when used in a stake reward. This have happend atleast 4 times on different wallet versions during the last 10 days.

With some help from presstab i managed to get some more infomation out of one of the tx that might been involved

presstab knows how to reach me if there is any more digging needed.

Lost atleast 4x 1k denoms, and might have lost more in 10 and 100 denoms that i didnt catch.

Fresh seed recovery and also wallet backups have been tried to get further into finding the missing one in question, without any luck

**TX with a zeromint spend that that is lost:**
https://explorer.veil-project.com/tx/a834a0c5c9522744ddd3f2b87f79946a959f11971fcaa4a6a5c3d013a52f91aa

**Zeromint spend used in this TX is:** fad5cf5be34e4f69f62437e66b48db8cd3cc0f0fe7a6233259ab0415dab9facc

./veil-cli findserial fad5cf5be34e4f69f62437e66b48db8cd3cc0f0fe7a6233259ab0415dab9facc
```
{
  "success": true,
  "txid": "a834a0c5c9522744ddd3f2b87f79946a959f11971fcaa4a6a5c3d013a52f91aa",
  "serial": "fad5cf5be34e4f69f62437e66b48db8cd3cc0f0fe7a6233259ab0415dab9facc"
}
```

**New zeromint spend produced in this TX is:**
./veil-cli gettransaction a834a0c5c9522744ddd3f2b87f79946a959f11971fcaa4a6a5c3d013a52f91aa
```
    "vout": [
      {
       "type": "zerocoinmint",
        "metadata": {
          "is_mine": true,
          "denom": 1000,
          "pubcoinhash": "d3627bf9b32a931b1518c0777339a4feff14086ecfac1fbb786e13d254ea88c1",
          "txid": "a834a0c5c9522744ddd3f2b87f79946a959f11971fcaa4a6a5c3d013a52f91aa",
          "height": 35926,
          "serialhash": "701cca5aba41194695a6455abaac681a942cf527030157c17c5108f6265ed513",
          "is_spent": false
        },
        "amount": "1000.00",
        "is_mine": true,
        "has_tx_rec": false
      },
```
**Running getarchivedzerocoin shows that it exist in the system**
./veil-cli getarchivedzerocoin | grep 701cca5aba41194695a6455abaac681a942cf527030157c17c5108f6265ed513
Output:
`    "serialhash": "701cca5aba41194695a6455abaac681a942cf527030157c17c5108f6265ed513",`

**While its not found here:**
./veil-cli exportzerocoins false 1000 | grep 701cca5aba41194695a6455abaac681a942cf527030157c17c5108f6265ed513
`Output is blank`

**And not found here:**
./veil-cli listmintedzerocoins true | grep 701cca5aba41194695a6455abaac681a942cf527030157c17c5108f6265ed513
`Output is blank`

**Also not found here:**
./veil-cli findserial 701cca5aba41194695a6455abaac681a942cf527030157c17c5108f6265ed513
```
{
  "success": false,
  "txid": "0000000000000000000000000000000000000000000000000000000000000000",
  "serial": "701cca5aba41194695a6455abaac681a942cf527030157c17c5108f6265ed513"
}
```

**Reference to recovery commands:**
```
./veil-cli rescanblockchain
./veil-cli getarchivedzerocoin
./veil-cli reconsiderzerocoins
./veil-cli resetspentzerocoin
./veil-cli resetmintzerocoin true
./veil-cli searchdeterministiczerocoin 0 10000 6
./veil-cli rescanzerocoinwallet
```

**Comment by chainlayer** [comment]
Adding the solution here for others to read
Problem was fixed with either one of these 2 things, or both
1. Did not reuse chaindata (blocks, chainstate and zerocoin folder) from earlier .veil folder. Used snapshot from 26th Jan.
2. Did only run the rescanblockchain, rescanzerocoinwallet, searchdeterministiczerocoin 0 10000 6 commands instead of running these ones mention below
getarchivedzerocoin, reconsiderzerocoins, resetspentzerocoin, resetmintzerocoin true

Using latest master source f8e0e3c

**Comment by presstab** [comment]
Just fyi:
`rescanzerocoinwallet` is just `reconsiderzerocoins` + `resetspentzerocoin` + `resetmintedzerocoins` all in one command, and nothing additional.
