### ISSUE TITLE
CT Spendable Balance is NOT Spendable

### ISSUE THREAD

**Issue by CryptoSifu** [Veil-Project/veil#347]
I recovered a missing balance by creating new addresses and rescanning blockchain. Two transactions were missing. One has reappeared.

Now I cannot spend it or do anything with it. It's just sitting there.

 I should be able to spend or mint these coins

Coind control doesn't allow me to select coins and console doesn't allow me to spend them. Mint doesn't work either.

 Nothing works, so everytime

wallet is windows qt v 1.0.1.4

Win OS x64

gettransaction 8ab7f292530c9dd01b1a97023e98d3c170a1986a2bf9e8eb8ab6596df0c86334

Debug:{
  "amount": 9.69323250,
  "creditbase": 9.69323250,
  "debitbase": 0.00000000,
  "creditanon": 9.69323250,
  "debitanon": 0.00000000,
  "confirmations": 24473,
  "blockhash": "0983689159a78cfb8bf191e7059c154719e00f29f0d085b1deb4937766c8bd87",
  "blockindex": 3,
  "blocktime": 1547264057,
  "txid": "8ab7f292530c9dd01b1a97023e98d3c170a1986a2bf9e8eb8ab6596df0c86334",
  "walletconflicts": [
  ],
  "time": 1548536193,
  "timereceived": 1548550672,
  "bip125-replaceable": "no",
  "details": [
    {
      "category": "receive",
      "amount": 0.00000001,
      "vout": 1
    },
    {
      "category": "receive",
      "amount": 0.00000001,
      "vout": 2
    },
    {
      "category": "receive",
      "amount": 9.69323250,
      "vout": 3
    }
  ],
  "debug": {
    "vin": [
      {
        "from_me": false,
        "type": "zerocoinspend"
      }
    ],
    "vout": [
      {
        "type": "data",
        "ct_fee": "0.00",
        "data": "0600",
        "is_mine": false,
        "has_tx_rec": true
      },
      {
        "type": "ct",
        "is_mine": false,
        "has_tx_rec": true,
        "output_record": {
          "type": 2,
          "flags": 0,
          "n": 1,
          "scriptPubKey": "",
          "amount": "0.00000001"
        }
      },
      {
        "type": "ct",
        "is_mine": false,
        "has_tx_rec": true,
        "output_record": {
          "type": 2,
          "flags": 0,
          "n": 2,
          "scriptPubKey": "",
          "amount": "0.00000001"
        }
      },
      {
        "type": "ct",
        "is_mine": true,
        "has_tx_rec": true,
        "output_record": {
          "type": 2,
          "flags": 1,
          "n": 3,
          "scriptPubKey": "76a914e12f4101b2eff24210b680bd1c4e7962666f35e988ac",
          "amount": "9.6932325"
        }
      }
    ]
  },

**Comment by seanPhill** [comment]
I don't know what your problem is with this transaction, ID 8ab7f292530c9dd01b1a97023e98d3c170a1986a2bf9e8eb8ab6596df0c86334 that you have posted. It is showing fine in the block explorer.

Please raise a ticket at **https://veil.freshdesk.com/support/home** and supply supporting information and state what is actually happening with your attempted transaction.

Github issues is for faults with the Veil code that require a developer to make changes to the code, not for individual technical support.

Thanks.

**Comment by CryptoSifu** [comment]
It is not accessible in my wallet. 
It shows as ct spendable but wallet will not allow it to be spent through with GUI or console, or minted.

**Comment by CryptoSifu** [comment]
This seems to be a dev issue as the coin control does not select these specific coins and they cannot be accessed or spent through the windows wallet. 
When you’re recover coins they will not appear until I have created min 100 new addresses and rescanned the section of the blockchain that holds the balance. 
Even after all that they cannot be used for nothing.

**Comment by seanPhill** [comment]
I will reference this in a "Coin Control is not working" issue that I am working on testing.

**Comment by hubgitacc** [comment]
I also have this issue. 1000 CT coins I can do nothing with.

**Comment by hubgitacc** [comment]
My windows wallet also has spendable valid CT. As per "getbalances" yet nothing can be done with them.

I am unable to mint coins into zerocoin in any denomination, and and get this >>

"Error failed to create transaction: failed to add ringct inputs. Ringctwallet dummy signature failed".

I've also tried to 'sendstealthtobase bv(myrealbasecoinaddress)' amount and that does not work either and I get this error >>

AddBlindedInputs failed: ringctwallet Dummy signature failed.. (code -4)

Also tried to 'sendstealthtoringct sv.. amount' which does not work. And I can't send stealth in any number from gui to another wallet and get error >> transaction failed no inputs.

(Been through this with Gets, Grumpy and Sean and provided further info and screenshots there -- so now here posting as requested).

**Comment by presstab** [comment]
This output has in fact been spent, but was just improperly labelled. After using @CryptoSifu 's wallet.dat to do some digging:

```
{
        "type": "ct",
        "is_mine": true,
        "has_tx_rec": true,
        "output_record": {
          "type": 2,
          "flags": 9,
          "n": 3,
          "scriptPubKey": "xxx",
          "have_address": true,
          "stealth_address": "xxx",
          "stealth_destination": "xxx",
          "amount": "9.6932325",
          "is_spent": true
        }
      }
```
