### ISSUE TITLE
CT to Zerocoin Mint Missing

### ISSUE THREAD

**Issue by CryptoSifu** [Veil-Project/veil#348]
Minted in wallet v 1.0.0.9 Mint disappeared and has never been recovered

 Mint should show in balance

Balance disappeared

It's still missing

Wallet 1.0.1.4 from veil github

Win OS x64

pretty sure this is the transaction hash and debug?

8ab7f292530c9dd01b1a97023e98d3c170a1986a2bf9e8eb8ab6596df0c86334
11:09:15
￼
{
  "amount": 0.00000000,
  "creditbase": 0.00000000,
  "debitbase": 0.00000000,
  "creditanon": 0.00000000,
  "debitanon": 0.00000000,
  "confirmations": 14906,
  "blockhash": "4a25865666b98ed85d277cbe8d4d1fb56be868640e5344f2fad439fd09a2565a",
  "blockindex": 1,
  "blocktime": 1547547443,
  "txid": "6e0d988c617677bfce83f15b0d8b60b163216ec60750ba03fa6b7c8d7bb2bb7b",
  "walletconflicts": [
  ],
  "time": 1548296284,
  "timereceived": 1548301649,
  "bip125-replaceable": "no",
  "details": [
    {
      "category": "receive",
      "amount": 10.00000000,
      "vout": 2
    }
  ],
  "debug": {
    "vin": [
      {
        "from_me": false,
        "prevout": "COutPoint(186156a34c, 2)",
        "type": "ct"
      },
      {
        "from_me": true,
        "prevout": "COutPoint(8ab7f29253, 3)",
        "type": "ct",
        "has_tx_rec": true,
        "output_record": {
          "type": 2,
          "flags": 1,
          "n": 3,
          "scriptPubKey": "76a914e12f4101b2eff24210b680bd1c4e7962666f35e988ac",
          "amount": "9.6932325"
        }
      }
    ],
    "vout": [
      {
        "type": "data",
        "ct_fee": "0.09380438",
        "data": "06d6c4bc04",
        "is_mine": false,
        "has_tx_rec": false
      },
      {
        "type": "ringct",
        "ephemeral_pubkey": "028f81a7e112487e9695eea08f616244d859597d513469c39792d7f1bcd0566b85",
        "is_mine": false,
        "has_tx_rec": false
      },
      {
        "type": "zerocoinmint",
        "metadata": {
          "is_mine": true,
          "denom": 10,
          "pubcoinhash": "deda39400a3acbea87ca1f04f541a32a3da8dacdb6a901c9b90d2b651b2e810e",
          "txid": "6e0d988c617677bfce83f15b0d8b60b163216ec60750ba03fa6b7c8d7bb2bb7b",
          "height": 17087,
          "serialhash": "88a7ac028fa0df9a3c205a1b7ecfbe70580178d5fd431a2ff5bf5489e70ffe91",
          "is_spent": false
        },
        "amount": "10.00",
        "is_mine": true,
        "has_tx_rec": false
      }
    ]
  }

**Comment by seanPhill** [comment]
Please, if this has not already been solved, submit your support requests to https://veil.freshdesk.com/support/home

**Comment by presstab** [comment]
I was able to get this wallet.dat from @CryptoSifu 
After running a rescan, the metadata of the zerocoin shows it at spent. So looks like there was not an issue here, maybe just confusion or incorrectly labelled coins.

```
"type": "zerocoinmint",
        "metadata": {
          "is_mine": true,
          "denom": 10,
          "pubcoinhash": "deda39400a3acbea87ca1f04f541a32a3da8dacdb6a901c9b90d2b651b2e810e",
          "txid": "6e0d988c617677bfce83f15b0d8b60b163216ec60750ba03fa6b7c8d7bb2bb7b",
          "height": 17087,
          "serialhash": "88a7ac028fa0df9a3c205a1b7ecfbe70580178d5fd431a2ff5bf5489e70ffe91",
          "is_spent": true
        },
```
