### ISSUE TITLE
Overlapping GUI transaction font

### ISSUE THREAD

**Issue by leto1981** [Veil-Project/veil#354]
1.0.1.4

win 64 GUI wallet

4k monitor
<img width="1152" alt="veil issue" src="https://user-images.githubusercontent.com/47224678/52077533-75783600-254e-11e9-990d-768a8eafd498.png">

**Comment by Panther107th** [comment]
Could this be a Windows 10 bug depending on how the screen scaling is set? On high res displays Windows automaticly sets the screen scale to 125% or even 150% so text is blown up. Please check your screen scale settings and set it to 100%, and reboot. Does it fix the problem?
![schaal](https://user-images.githubusercontent.com/47520276/52554104-146e1f00-2de6-11e9-9a78-eb9e81fd0de4.jpg)

**Comment by StrontiumZ38** [comment]
Similar issue to #385 and could probably be tackled simultaneously.

**Comment by presstab** [comment]
Bounty Price: 250
Estimated Hours: 4
