### ISSUE TITLE
Failed to find Zerocoins in wallet.dat (code -4) in 32-bit version although listable (works in 64-bit version)

### ISSUE THREAD

**Issue by subarist004** [Veil-Project/veil#355]
Wallet 1.0.1.4
Windows 10
With Grumpy we did several efforts and nothing helped. Same issue with SV wallet. The last attempt log:

Restored from seed.

15:21:53
￼
rescanblockchain

15:26:50
￼
{
  "start_height": 0,
  "stop_height": 41140
}

15:27:07
￼
rescanzerocoinwallet

15:27:07
￼
[
]

15:27:19
￼
rescanringctwallet

15:27:19
￼
null

15:27:27
￼
searchdeterministiczerocoin 0 25000 2

19:00:07
￼
done

19:25:13
￼
spendzerocoin 10 false true 42 bv1qd547d754u6aavrd5q8pjql8hw2ahz02ca5x407

19:25:13
￼
Failed to find Zerocoins in wallet.dat (code -4)

19:25:26
￼
resetmintzerocoin

19:25:26
￼
{
  "updated": [
  ],
  "archived": [
  ]
}

19:25:33
￼
resetspentzerocoin

19:25:34
￼
{
  "restored": [
  ]
}

19:25:43
￼
spendzerocoin 10 false true 42 bv1qd547d754u6aavrd5q8pjql8hw2ahz02ca5x407

19:25:43
￼
Failed to find Zerocoins in wallet.dat (code -4)

19:46:57
￼
spendzerocoin 10 false true 100 bv1qd547d754u6aavrd5q8pjql8hw2ahz02ca5x407

19:46:57
￼
Failed to find Zerocoins in wallet.dat (code -4)

**Comment by seanPhill** [comment]
Can you please: ```listmintedzerocoins```
I don't see anything above showing that you have any zerocoins.

**Comment by seanPhill** [comment]
Thanks. You've definitely got zerocoins! Will look into the error message.

Can we change the title of this issue?
From: Failed to Spend Zerocoins.
To: Failed to find Zerocoins in wallet.dat (code -4) although listable!

**Comment by supernyner** [comment]
i do have the same issue after a wallet seed restore from scratch. if you need someone to test, i'm willing. thanks

**Comment by seanPhill** [comment]
I have a 1.0.1.4 testnet wallet on Linux that now has exactly the same problem. If I try to spend even ten or fifty tVeil (to ensure it does not choose the 100 denoms) in the GUI it gives an error box with no error description, and only a red circle with a white dash in it!

![virtualbox_ubuntu mate_04_02_2019_22_23_38](https://user-images.githubusercontent.com/46495592/52207030-41936c80-28d0-11e9-89e0-a6ee3c506261.png)

and _then_ another dialog box with the same icon and "Transaction creation failed! and an "OK" button.

![virtualbox_ubuntu mate_04_02_2019_23_00_54](https://user-images.githubusercontent.com/46495592/52207334-3bea5680-28d1-11e9-9f69-eb612c756594.png)

If I use the Debug Console with ANY amount of zerocoins in the command 
```spendzerocoin 50 false true 42 ( "tps1qqpqflrprregnh2hetfxlvhefe6vzygxk5axpyyjnfc7rrqu38fhlmspq2hvahmlve3pdc7xaqgwtxsfsdz5mn6huz4uwu356d2tw3x2f3c72qqq300k6l" 10)``` it returns 
```Failed to find Zerocoins in wallet.dat (code -4)```

**Comment by seanPhill** [comment]
AND this is after spending 8.5 hours running ```searchdeterministiczerocoin 0 20000 2```

**Comment by seanPhill** [comment]
There are spendable amounts also in Basecoin and RingCT, but a GUI send (attempt) of even ten Veil (without specifying zerocoins in the Console) fails the same, any time. Maybe it is because the wallet tries available zerocoins by default, so it never tries the RingCT or Basecoin.

**Comment by seanPhill** [comment]
We just discovered one thing in common between these two failing wallets (that cannot spend)!
32-bit OS. (One is Linux Ubuntu Mate 32-bit. The other is Windows 10 32-bit.)

**Comment by seanPhill** [comment]
Please update this title to add "in 32-bit version".

**Comment by veilgets** [comment]
Bounty: 1500

**Comment by seanPhill** [comment]
Recommending to close this as a zerocoin-related issue, that will be automatically redundant as zerocoin is replaced, and as anyone suffering this likely has already moved to a 64-bit OS.
