### ISSUE TITLE
Coin control is not working (basecoin and CT/RingCT)

### ISSUE THREAD

**Issue by seanPhill** [Veil-Project/veil#356]
Reported by a user in Discord. Coin Control was opened and a basecoin UTXO of 1 Veil was selected, and then the spend was done, but it chose a (staked) zerocoin to make the spend!

Reported in "CT Spendable Balance is NOT Spendable #347" the user tried to select a CT or RingCT balance, but was unable, and subsequently also had troubles trying to make the spend in the Debug Console.

Further testing in MacOS wallet "Veil Core version v1.0.1.4-3279c67fa-dirty (64-bit)" on testnet on a late 2013 Mac Pro with 32GB RAM.

**Comment by seanPhill** [comment]
Tested on a VM with Linux Ubuntu Mate 32-bit. (1.0.1.4-3279c67fa) and on macOS as mentioned above.

Coin Control is not adding up the amounts into the totals and is not passing the amount to the spend window, and as the spend window is spending without confirmation, it is taking nothing from Coin Control and spending from funds in the default manner.

I have not proceeded with the actual spend, because the observed behaviour is enough to see that Coin Control / Coin Selection is no longer working! (I say no longer, because I was sure that from an early report of this issue I could remember seeing it showing the totals at one point, whether in a release or in a master build.
![virtualbox_ubuntu mate_02_02_2019_11_42_47](https://user-images.githubusercontent.com/46495592/52157349-7772fe00-26e2-11e9-9d34-5ed9631cf39d.png)
![virtualbox_ubuntu mate_02_02_2019_11_48_01](https://user-images.githubusercontent.com/46495592/52157355-835ec000-26e2-11e9-84de-cfb426dc6820.png)
![virtualbox_ubuntu mate_02_02_2019_11_48_42](https://user-images.githubusercontent.com/46495592/52157358-8954a100-26e2-11e9-8cfb-7b11bf35c605.png)
![virtualbox_ubuntu mate_02_02_2019_11_49_21](https://user-images.githubusercontent.com/46495592/52157359-8f4a8200-26e2-11e9-98b8-1a2208fc0f38.png)
![virtualbox_ubuntu mate_02_02_2019_11_50_18](https://user-images.githubusercontent.com/46495592/52157361-96719000-26e2-11e9-90c5-3441acb608aa.png)

**Comment by seanPhill** [comment]
Here is the original 0.9 Veil that arrived from the user on Github.
![screen shot 2019-02-02 at 9 07 53 am](https://user-images.githubusercontent.com/46495592/52157439-21eb2100-26e3-11e9-94af-9f6ad9298e41.png)

Here is the txid and testnet explorer showing the original transaction test coming from zerocoin instead.
https://explorer.veil-project.com/tx/faf8165832dba6a11fe88ebc433cdb239f776da82d4aa48a7b902a5f996e19bf

**Comment by seanPhill** [comment]
Was: 
Coin selection sum of coins and calculation of fee is not working (in Win64 at least) #70
Closed and transferred to a new issue.

3.) Coin Control needs to be functional #111

referenced in pull request: https://github.com/Veil-Project/veil/pull/233
And as I mentioned at the beginning, a factor in:
CT Spendable Balance is NOT Spendable #347

**Comment by seanPhill** [comment]
I just stumbled back on this one, while looking for a subsequent issue in master branch (crash in coin control), but I remember noticing that all (or most) of this has been fixed at least by wallet version 1.0.3. I'll leave this open to be verified, in case there is some small part of this that has not been fixed.

**Comment by veilgets** [comment]
if this is fixed can we close it, if not can a dev confirm please
