### ISSUE TITLE
Cannot spend full amount of Veil zerocoin in the GUI

### ISSUE THREAD

**Issue by seanPhill** [Veil-Project/veil#357]
I tested a spend of 1990 testVeil (zerocoin), which exactly equalled my available to spend zerocoin balance. A stealth address was the target.

I expected that zerocoin spend would be fee-free, but it rejected processing it, with the message "The amount exceeds your zerocoin balance, only zerocoins accepted on stealth addresses" popping up for a couple of seconds, with no log reaching the debug log, I suppose, because the GUI did not pass anything to the underlying wallet to process. 

The commit "wallet confirmed balance + no zerocoin balance fix #217" (with the changes in ```src/qt/sendcoinsdialog.cpp``` seems to have supplied the message by ```case WalletModel::AmountExceedsBalance_NoBasecoinBalanceAccepted:```, but if accounting for a potential fee (which should not be there anyway) caused it to 'believe' there were not enough zerocoin funds, it still did not choose the alternative message _"The total exceeds your balance when the %1 transaction fee is included."_ from ```case WalletModel::AmountWithFeeExceedsBalance:``` and it did not consider using the sufficient balances in RingCT, CT, **and** Basecoin.

Given this behaviour this contradicts the Veil standard of allowing people to simply send an amount, and that amount will be sent and arrive, with any fees taken from another balance. This also reminds me of the contradiction in the mainnet transaction I mentioned earlier today (in another issue), where 1 Veil was sent, but 0.9 Veil arrived (selected from zerocoin), with a 0.1 Veil fee!
https://explorer.veil-project.com/tx/faf8165832dba6a11fe88ebc433cdb239f776da82d4aa48a7b902a5f996e19bf

This behaviour forces people to mentally calculate a fee (that should not be there on a zerocoin spend) before setting the amount to send.

Assuming that zerocoin is supposed to be fee-free, some code in this area needs to be made aware of that, and to not prevent this transaction for a non-existant fee, and some other code needs to make sure that the fee that should not exist, also is not actually taken, when spending zerocoin in the GUI.

**Comment by seanPhill** [comment]
![screen shot 2019-02-02 at 1 43 30 pm](https://user-images.githubusercontent.com/46495592/52159204-de99ae00-26f4-11e9-83cc-4b54eb0c8b7a.png)

**Comment by seanPhill** [comment]
I was looking at the Coin Control today, while selecting only zerocoins, and indeed it calculated a fee. 
I went back to the Debug Console to do the spend instead.

**Comment by seanPhill** [comment]
Again? It says I "unassigned veildev just now".

How is that so? All I did was add a comment. (It seems like a Github bug.)

**Comment by veilgets** [comment]
Bounty: 250

**Comment by seanPhill** [comment]
Closing this as zerocoin-related issue. It evidently did not affect many people, so it has not been a priority and no-one took it up to solve it.
