### ISSUE TITLE
Error when starting up Veil in Windows 10

### ISSUE THREAD

**Issue by VeilDango** [Veil-Project/veil#36]
https://imgur.com/cKWoGGV

Get this error each time I start up Veil. I can click Ignore and continue on.

Reproducibility:

I can reliably reproduce the issue. Refer to screenshot.

Version used:

https://github.com/Veil-Project/veil/releases/download/testnet-1/veil-0.0.9-win64-setup-unsigned.exe

Hardware and OS:

6700k Intel CPU
Pro 970 SSD
32GB RAM
Windows 10 Pro

Debug.log:

https://cdn.discordapp.com/attachments/507024857847037962/527898028942688256/debug.log

**Comment by presstab** [comment]
Some non-backwards compatible changes were made. You need to generate a new wallet.dat file and delete the old one.
