### ISSUE TITLE
Changes to auto mint setting do not persist a wallet restart

### ISSUE THREAD

**Issue by gabrielnergaard** [Veil-Project/veil#361]
Running the 1.0.1.4 wallet on Mac OS X Mojave, there are some problems with changing the auto mint setting. 

First, there is no "Save Setting" button to click once you make a change. So I presume simply changing the setting and closing the window with "X" is sufficient.

However, after changing the setting, and restarting the wallet, the setting is back at "10", so my change doesn't persist.

Also, while trying to troubleshoot this,  I once clicked on the settings screen and found *nothing* selected:

![](https://clipz.in/qa32t.png)

**Comment by StrontiumZ38** [comment]
Related to #197

**Comment by furszy** [comment]
#372 done.
