### ISSUE TITLE
Setting the auto mint setting to 10k, closing and reopening the windows result in NO SETTING being shown.

### ISSUE THREAD

**Issue by gabrielnergaard** [Veil-Project/veil#366]
Mac OS X Mojave. Veil 1.0.1.4

Setting the auto mint setting to 10k, closing and reopening the windows result in NO SETTING being shown.

If I set automint to 10k, close the window and reopen, I see this:

![](https://clipz.in/ys13l.png)

**Comment by gabrielnergaard** [comment]
Many people have confirmed this in Discord, so it doesn't seem to be OS specific.

**Comment by furszy** [comment]
Why are you repeating the same issue over and over? just closed #197 #361..

**Comment by gabrielnergaard** [comment]
I did a search on what I expected to find in the title of a similar issue, and nothing came up, so I didn’t realize it had already been reported.
