### ISSUE TITLE
Cannot do anything with CT balance

### ISSUE THREAD

**Issue by hubgitacc** [Veil-Project/veil#367]
My windows wallet; (v1.0.1.4) has spendable valid CT as per "getbalances" yet nothing can be done with them.

I am unable to mint the CT coins to Zerocoin in any denomination, and and get this error >>

"Error failed to create transaction: failed to add ringct inputs. Ringctwallet dummy signature failed".

I've also tried to 'sendstealthtobase bv(myrealbasecoinaddress) amount' and that does not work either and I get this error >>

AddBlindedInputs failed: ringctwallet Dummy signature failed.. (code -4)

Also tried to 'sendstealthtoringct sv.. amount' which also does not work and produces error >>

AddBlindedInputs failed: ringctwallet Dummy signature failed.. (code -4)

I also can't send stealth in any number from GUI to another wallet and get error >> transaction failed no inputs.

**Comment by presstab** [comment]
Do you have more than one CT outputs? Can you go to the coin control dialog on the sendcoins page, open it up and manually select one CT output and send it to yourself?

**Comment by hubgitacc** [comment]
Yes, in coin control the two CT outputs are there; (as per screenshot).

I tried to send to myself by selecting / ticking the 480 amount in coin control and right clicking / copying its sv address and pasting into the GUI send address area and trying to send amount 480. It didn't work and produced: "Failed to add inputs" error; (as per screenshot). I also tried to send amount 480.38 and 100 which also didn't work with same error.

![367](https://user-images.githubusercontent.com/47358796/52335653-7e2ca880-2a35-11e9-90e8-89ac78c164c2.jpg)

**Comment by hubgitacc** [comment]
oops, meant to comment; (not close & comment).

**Comment by hubgitacc** [comment]
Presstabs,

Anything else you want me to try?

**Comment by presstab** [comment]
@hubgitacc I think I have this resolved, but you will need to either build the wallet from the master branch or wait until the next release to try it out (I am trying hard to get that finished up soon).

**Comment by hubgitacc** [comment]
Thanks for the update. I'll build Win wallet from master branch and let you know if it works.

**Comment by hubgitacc** [comment]
I've built wallet from master as per >> https://github.com/Veil-Project/veil/blob/master/doc/build-windows.md

Is it normal for the binary version of veil-qt.exe to be build version: Veil Core version v0.0.0.99-2b32884db (64-bit) ?

Also, does it matter if I just copy over wallet.dat after fully syncing new wallet I've built, or should I attempt recovery from seed ?

**Comment by hubgitacc** [comment]
Did not work. Every error just the same as initially stated.

**Comment by hubgitacc** [comment]
Is there anything else I can try?

**Comment by hubgitacc** [comment]
Presstab,

Trying your official v1.0.1.5 just now to see if that fixes the problem.

**Comment by hubgitacc** [comment]
Running your latest official release binary and done as you suggested in discord:

rescanblockchain
rescanringctwallet 
gebalances

￼
{
  "basecoin_spendable": "2.8318055",
  "basecoin_unconfirmed": "0.00",
  "basecoin_immature": "0.00",
  "ct_spendable": "1001.00",
  "ct_unconfirmed": "0.00",
  "ct_immature": "0.00",
  "ringct_spendable": "0.00",
  "ringct_unconfirmed": "0.00",
  "ringct_immature": "0.00",
  "zerocoin_spendable": "0.00",
  "zerocoin_unconfirmed": "0.00",
  "zerocoin_immature": "0.00"
}

It hasn't made a difference. These coins are trapped in CT and errors are just the same as above trying to send to base, send sv  or mint.

**Comment by presstab** [comment]
This is fixed now. I have not yet moved the commit over to the master branch yet though.

**Comment by hubgitacc** [comment]
Ok great thanks.

**Comment by N8Thrasher** [comment]
Using the latest wallet Ct_spendable locked, I tried all that are mentioned here but still error
