### ISSUE TITLE
Overview section splits non-available balance into Unspendable and Immature instead of merging into Unspendable.

### ISSUE THREAD

**Issue by VeilDango** [Veil-Project/veil#37]
https://imgur.com/TrPV6ME

3a. Right now the overview section splits non-available balance into Unspendable and Immature. Unless the team decided to switch to that, the team wanted it to be combined into Unspendable, and hover/clickable tooltip should show Unconfirmed and Immature. If switching, make it Unconfirmed and Immature.

Reproducibility:

I can reliably reproduce the issue. Refer to screenshot.

Version used:

https://github.com/Veil-Project/veil/releases/download/testnet-1/veil-0.0.9-win64-setup-unsigned.exe

Hardware and OS:

6700k Intel CPU
Pro 970 SSD
32GB RAM
Windows 10 Pro

Debug.log:

https://cdn.discordapp.com/attachments/507024857847037962/527898028942688256/debug.log

**Comment by 4x13** [comment]
Address types will be fixed shortly

**Comment by 4x13** [comment]
changed to Unconfirmed
