### ISSUE TITLE
Cannot sendstealthtobasecoin (MAC wallet - v1.0.1.4)

### ISSUE THREAD

**Issue by hubgitacc** [Veil-Project/veil#370]
Was hoping to try a re-mint in order to get some stakes on my main Mac wallet. Not able to do so in any denomination having tried the following:

sendstealthtobasecoin bv1.. 1000

Insufficient blinded funds (code -6)

￼sendstealthtobasecoin bv1.. 100

insufficient blinded funds (code -6)

￼sendstealthtobasecoin bv1.. 10

Insufficient blinded funds (code -6)

**Comment by seanPhill** [comment]
If your funds are already in stealth (CT or RingCT) then you can mint directly from there. There is a 0.1 fee for sending between wallet addresses, but only a 0.01 fee per coin minted. 

If you are reminting and the coins are still zerocoins, then sendstealthto(anything) is not the relevant command. You need something like this! 
```
spendzerocoin 100 false true 42 tps1qqpqflrprregnh2hetfxlvhefe6vzygxk5axpyyjnfc7rrqu38fhlmspq2hvahmlve3pdc7xaqgwtxsfsdz5mn6huz4uwu356d2tw3x2f3c72qqq300k6l 10
```
false is whether to mint any change
true is whether to minimise the amount of change
42 is the security level and how long to take. Bigger number is higher and longer.
The final 10 is the denomination to use.

**Comment by hubgitacc** [comment]
Ok thanks. 

But what is a tps... address? Did you mean a bv1 or an sv1 address? 

Also, will the fee come out of the source funds or be debited from amount that arrives?

**Comment by hubgitacc** [comment]
Ok got how this works now, and had some help / clarification from Dango. Will close this issue thanks.
