### ISSUE TITLE
Feature Request — Link transaction ID to the Explorer URL

### ISSUE THREAD

**Issue by gabrielnergaard** [Veil-Project/veil#377]
It would be very convenient for the user if the transaction ID listed on transaction pop-up windows was hyperlinked to the associated URL at the Veil Block Explorer:

https://explorer.veil-project.com/tx/{txid}

**Comment by seanPhill** [comment]
I would prefer if there was a hyperlink button beside it. I want to _continue to be able to_ select the txid  and copy it into the clipboard. I don't want an unexpected browser launch.

**Comment by gabrielnergaard** [comment]
Good point, Sean. Agreed.

**Comment by StrontiumZ38** [comment]
We keep circling back to have links in wallet. I'm personally all for them since usability is king, but I can 100% understand the argument against them for security reasons. Just need to make certain we communicate that people should only be downloading their wallets from the project's GitHub (as should always be the case anyhow).

**Comment by gabrielnergaard** [comment]
In this case, the suggestion is just linking the txid to the blockchain explorer, something done in 100% of the other wallets I use. I can't see a security risk in that.

**Comment by presstab** [comment]
There is an issue that arises with external dependencies. For example the block explorer changes its url scheme, or is on a fork and does not display what it should.

**Comment by gabrielnergaard** [comment]
The block explorer changing its URL scheme, or being on a fork, are risks. But they are low probability risks, and the consequences of those risks would seem enormously compensated by the access convenience for something that will be so often used. (And regarding the particular risk of the block explorer being on a fork, the consequences of *that* don't really change whether we link to it from the wallet or not, since, being the project's official explorer, we also link to it from the website.)

**Comment by StrontiumZ38** [comment]
Any further discussion on this? Perhaps we should do so on Discord or Basecamp.

**Comment by presstab** [comment]
Bounty Price: 208.33
Estimated Hours: 3.33

**Comment by veilgets** [comment]
Developer: drag0ng
