### ISSUE TITLE
May be a MAJOR ISSUE! Wrong Veil address in wallet. Starts with "b" instead of "V"

### ISSUE THREAD

**Issue by VeilDango** [Veil-Project/veil#38]
https://imgur.com/TrPV6ME

Wrong Veil address in wallet. Starts with "b" instead of "V"

3b. The receiving address starts with "bv1". A Veil address starts with V. I don't know what this is: bv1qyseyz9c8trcg9z7mx6xe033wxwacgsrkh9tuv5

https://imgur.com/2szc4SD

22. The address shown in Receive Veil is not a Veil address starting with V. I got: bv1qmyx9h43pk8w2p30244uyzvnmk7zmp07q2a8qk8

https://imgur.com/TzGCA28

25. After generating a new address, the address starts with "bv" instead of a Veil address "V". It also does not allow me to copy it to clipboard or copy+paste. The 3 vertical dot icon does nothing.

Reproducibility:

I can reliably reproduce the issue. Refer to screenshot.

Version used:

https://github.com/Veil-Project/veil/releases/download/testnet-1/veil-0.0.9-win64-setup-unsigned.exe

Hardware and OS:

6700k Intel CPU
Pro 970 SSD
32GB RAM
Windows 10 Pro

Debug.log:

https://cdn.discordapp.com/attachments/507024857847037962/527898028942688256/debug.log

**Comment by presstab** [comment]
This is correct. It is bech32 encoding, which starts with `bv` if it is a basecoin veil address.

**Comment by veildev** [comment]
closing this.
