### ISSUE TITLE
spendzerocoinmints spends TWO coins when given ONE (mint) serial hash!

### ISSUE THREAD

**Issue by seanPhill** [Veil-Project/veil#380]
I noticed this discussed by users in Discord.
I have just tested this once, and it happened the same.

```
spendzerocoinmints '["74644cbfce42e644a8a9d8984e9a07efa141fc28294330ce7368fccbb827409a"]' "tps1qqpqflrprregnh2hetfxlvhefe6vzygxk5axpyyjnfc7rrqu38fhlmspq2hvahmlve3pdc7xaqgwtxsfsdz5mn6huz4uwu356d2tw3x2f3c72qqq300k6l"
```
TXID: 6c1d4af06ea4d1f4fdc52ebe3fcbf49b8d7c892b3996dc7bc4d394575bfc383a

The specified zerocoin was a 100 denom with over 21,000 confirmations so I chose that one.
The spend also sent another 100 denom, with over 11,000 confirmations.

Here are the two zerocoins, the first being the one specified:

| serial hash | zerocoin ID | denomination  |
| ------------- |:-------------:| -----:|
| 74644cbfce42e644a8a9d8984e9a07efa141fc28294330ce7368fccbb827409a     | babb546c7f07e8de1f548e9bd0d69c43c45dc15d8ddb79af148761dc5e4a17cf | 100 |
| a91cfb647937bc178c2104a422d7c4655cb1acb550a61d4d66867e1082f00941      | 274a7576ef5f66a5152da97d12b923b772370284a725bd2f041b7155f7cf7791      |   100 |

**Comment by seanPhill** [comment]
The above is on testnet, in case you haven't scrolled all the way over to the right where you'll see the testnet Veil stealth address.

**Comment by random-zebra** [comment]
Closed in https://github.com/Veil-Project/veil/pull/382
