### ISSUE TITLE
Transaction listing not scaling down on small displays

### ISSUE THREAD

**Issue by gabrielnergaard** [Veil-Project/veil#385]
The following is a screenshot of Veil 1.0.1.5 running on my headless Mac mini (OS X Mojave), for which the virtual display dimensions are 1024 x 768.

As you can see, the transaction list doesn't scale down properly, and as a result the transaction amounts on the right can't be seen.

![](https://clipz.in/8ykfy.png)

**Comment by StrontiumZ38** [comment]
Similar issue to #354 and could probably be tackled simultaneously.

**Comment by veilgets** [comment]
Bounty: 281.25

**Comment by codeofalltrades** [comment]
@veilgets I'm pretty this is fixed. Merged pull #480 fixed the issue.
