### ISSUE TITLE
1.0.1.5 Windows - pref denom not saving on full exit

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#386]
Preferred zerocoin denom setting not saving on full exit on Windows wallet. Does persist as long as wallet is open.

Tested on Windows 64 bit.

**Comment by seanPhill** [comment]
The automint setting in macOS remains at 1000, but in my testnet wallet I have over 1700 tVeil in basecoin and it is not autominting.

**Comment by veildev** [comment]
Please, divide issues.

So, @StrontiumZ38 the wallet is not persisting the automint denom selection on windows? Latest version?

**Comment by StrontiumZ38** [comment]
@veildev yessir that's correct. Upon a full exit and reload of the wallet it returns to 10 denom pref.

**Comment by StrontiumZ38** [comment]
Issue persists in latest version.
