### ISSUE TITLE
Have to remove How to obtain Veil button on overview

### ISSUE THREAD

**Issue by VeilDango** [Veil-Project/veil#39]
https://imgur.com/TrPV6ME

3c. Remove How to obtain Veil button on overview. We're not using that FAQ item. It also links to the wrong FAQ item, How do I use the QR code?

Reproducibility:

I can reliably reproduce the issue. Refer to screenshot.

Version used:

https://github.com/Veil-Project/veil/releases/download/testnet-1/veil-0.0.9-win64-setup-unsigned.exe

Hardware and OS:

6700k Intel CPU
Pro 970 SSD
32GB RAM
Windows 10 Pro

Debug.log:

https://cdn.discordapp.com/attachments/507024857847037962/527898028942688256/debug.log

**Comment by veildev** [comment]
done on #59 .
