### ISSUE TITLE
Lost basecoins

### ISSUE THREAD

**Issue by kirjah** [Veil-Project/veil#390]
After the update of the new version and the restoration of the wallet, the balance of delivery of the basecoin wallet is lost. Recovery commands according to the instruction do not give anything. After sending the basecoins, I had to get an address for getting delivery from the exchange. after the restoration of the wallet by the phrase “recovery” the address is for delivery is not restored.

**Comment by StrontiumZ38** [comment]
@kirjah have you tried working through this with support staff on Discord at all? If you could provide some additional info, such as transaction id, it'll be a lot easier for devs here to investigate your problem. The support staff would also benefit from such info if you've not yet worked through your problem with them.

**Comment by kirjah** [comment]
> @kirjah have you tried working through this with support staff on Discord at all? If you could provide some additional info, such as transaction id, it'll be a lot easier for devs here to investigate your problem. The support staff would also benefit from such info if you've not yet worked through your problem with them.

I communicated with them, not even with one, but with several people. I provided my TXID. Already on the second wallet, I have a similar problem, all that the discord support could explain to me is that these coins are probably collected as dust, but it seems to me like nonsense.

**Comment by veilgets** [comment]
try typing getnewbasecoinaddress a number of times until u restore the address

**Comment by seanPhill** [comment]
As above, try either `getnewbasecoinaddress` (repeated until you get the correct one), and then `rescanblockchain`

or
```restoreaddresses 10``` and `rescanblockchain`. 

Repeat (the address restoration and the rescan) if the balance is not found.

Please let us know (here) how you went, and if not successful, please paste the commands that you used.

**Comment by seanPhill** [comment]
If there is confidential information, do not post it here or on Discord.

If necessary we might be able to handle it via Direct Message, but **_do not_** include seed words, or private keys and things like that.

**Comment by kirjah** [comment]
I once again restored my wallet through the recovery code phrase. I executed the commands for searching and recovering the lost zerocoins, once again according to the instructions. And lo and behold! I finally can see a list of my lost bazecoins (with the help of the listaddressgroupings command) with the pennies of the surrender. Thanks for the help!
