### ISSUE TITLE
Assertion Failed.  Wallet Will Not Start

### ISSUE THREAD

**Issue by jch9678** [Veil-Project/veil#393]
I updated from 1.0.1.4 to 1.0.1.5 using the standalone wallets (no installer).  My computer had restarted a couple days ago and I was syncing.  I saw there was an update so I exited 1.0.1.4 cleanly.  Downloaded .5 and started it up and I got this error:

---------------------------
MinGW Runtime Assertion
---------------------------
Assertion failed!

Program: C:\Users\zzzzzz\Wallets\Veil\veil-1.0.1.5\bin\veil-qt.exe
File: validation.cpp, Line 3265

Expression: !setBlockIndexCandidates.empty()
---------------------------
Abort   Retry   Ignore   
---------------------------

The error shows up for any wallet version now.

My wallet data is not in the default location if that means anything.

**Comment by MisterKangaroo** [comment]
This error indicates that your local copy of the blockchain got corrupted, which can happen if the wallet is force closed while running for example. 
A resync of the blockchain data will fix it.
Here is a guide how to resync your wallet:

https://veil.freshdesk.com/support/solutions/articles/43000468393-how-to-resync-your-blockchain

**Comment by jch9678** [comment]
Thank you mister k. Much appreciated.

**Comment by MisterKangaroo** [comment]
Np... Next time you have issues...jump in the discord. The support guys there are pretty helpful and almost 24/7 available. ;)
