### ISSUE TITLE
multiple Zerocoin minting actions soon after another produce a stuck TX

### ISSUE THREAD

**Issue by MisterKangaroo** [Veil-Project/veil#398]
When i minted multiple times 200 Zerocoin (from basecoin) soon after another one of these mints including Basecoin change got stuck in the local mempool (kept unconfirmed)
Abadontransaction HASH did release the initial Basecoin balance.

Same happend to a user in Discord today.

Windows 10 x64
actual wallet release 1.0.1.5

**Comment by seanPhill** [comment]
When I mint I always need to exit the Minting window and then go back in, for it to refresh the Basecoin, CT and RingCT (available) balances. If you just keep minting, especially from CT, the change is likely to have moved, at either into immature/pending CT or immature/pending RingCT, depending on the size of change.
While this might not be related to the repeated minting from basecoin issue, _the solution might be the same for both,_ to properly refresh the balances before allowing another minting. Maybe also include below the available balances, the unavailable/pending balances, so people don't freak out when they see more balance disappeared than the amount that they minted.
