### ISSUE TITLE
The overview icon is currently a refresh icon.

### ISSUE THREAD

**Issue by VeilDango** [Veil-Project/veil#40]
https://i.imgur.com/TrPV6ME.png

3d. The overview icon is currently a refresh icon. I suggest we use another icon.

Reproducibility:

I can reliably reproduce the issue. Refer to screenshot.

Version used:

https://github.com/Veil-Project/veil/releases/download/testnet-1/veil-0.0.9-win64-setup-unsigned.exe

Hardware and OS:

6700k Intel CPU
Pro 970 SSD
32GB RAM
Windows 10 Pro

Debug.log:

https://cdn.discordapp.com/attachments/507024857847037962/527898028942688256/debug.log

**Comment by veildev** [comment]
This is not an issue. Design choice.
