### ISSUE TITLE
Veil built-in miner, how to switch off?

### ISSUE THREAD

**Issue by goodthebest** [Veil-Project/veil#400]
When veil wallet starts (daemon) it will also start built-in miner. How to stop Veil wallet's built in miner, what flags to use to disable in conf ?

**Comment by StrontiumZ38** [comment]
@goodthebest have you tried asking for help in the support channel on [Discord](https://discord.gg/Ywyb9hs)? Someone should be able to walk you through it there.

**Comment by seanPhill** [comment]
I've _never_ seen the Veil built-in (cpu) miner running by default. 

But you can turn it off with ```./veil-cli generatecontinuous false```

What information tells you that veild is generating blocks by default?

**Comment by seanPhill** [comment]
Are you sure it is not just staking blocks?

**Comment by seanPhill** [comment]
If staking, you can prevent staking, by preventing minting to zerocoins, by running in exchanges and services mode. ``` exchangesandservicesmode=1```

**Comment by goodthebest** [comment]
hey whenever I used to start the daemon (wallet) I notice a message in debug miner starting I thought it was some built-in miner. I'll try that flag and see if it helps with unresponsive veil daemon at intervals. Issue explained below.

 @presstab @seanPhill 
Another issue I'm noticing is and I've tested on several machines, veil wallet will become unresponsive and return getblocktemplate 500 error. It apparently looks some bug, is there any work around it?

**Comment by seanPhill** [comment]
That does appear to be a mining issue. Are you sure you're not running a third party x16rt miner on your computer at those times?

**Comment by goodthebest** [comment]
Actually problem is with the daemon, please check this debug, it stops syncing when this error shows up and of course it won't work with the stratum then.

![image](https://user-images.githubusercontent.com/1715740/53597774-725b7e80-3bbc-11e9-92b0-72a6768eef1e.png)

**Comment by seanPhill** [comment]
@goodthebest **What was the resolution to this problem?** I see that the "issue" got closed, because the title question was answered, but I don't see a resolution of the _underlying_ problem.
