### ISSUE TITLE
Select oldest zerocoinmints first when spending zerocoins.

### ISSUE THREAD

**Issue by presstab** [Veil-Project/veil#402]
Default zerocoinspend mint selection should select oldest mints of a particular denomination first.

**Comment by seanPhill** [comment]
I can confirm that this does not happen. Attached is a spreadsheet showing the ten denoms that were selected in a spend of 210 Veil (for reminting).

On the right is the 'before' snapshot (from listmintedzerocoins true).
On the left is the 'after' snapshot, and I have **bolded** the evidently spent zerocoins in the right hand side.
[zerocoinsSelectedForSpend.pdf](https://github.com/Veil-Project/veil/files/2892117/zerocoinsSelectedForSpend.pdf)
