### ISSUE TITLE
Wallet mints wrong denomination

### ISSUE THREAD

**Issue by Veil-Grumpy** [Veil-Project/veil#408]
I was reminting zerocoin to basecoin

After the basecoin had at least 10 confirms I tried to remint them to zerocoin from the zerocoin GUI.
I did select the 100 denom, checked the use basecoin and started hitting mint.

After I did hit the mint button several times, I noticed a weird thing because it minted 10 denomination instead of 100.

Tried to remint the 10 denomiation back to basecoin but it gave me a error message: Failed to find Zerocoin in wallet.dat (code -4)

After restarting wallet with reindex-zdb I was able to spend the zerocoin and mint them into the correct denomination

Veil 1.0.1.5-win64-setup-unsigned.exe
Windows 10 Pro 64

**Comment by seanPhill** [comment]
Selecting the denomination at the left is for **autominting only**. It has no relevance to the manuall minting in the right hand side.

I've _never seen_ a manual mint do a wrong denomination. What amount was requested? Did it mint ALL tens? Manual minting _will_ mint a mixture of denoms, if appropriate, for example, minting 1960 will mint three different denoms, and presumably minting 11230 will mint four different denoms.

**Comment by gabrielnergaard** [comment]
What @seanPhill said — When manually minting, the left-hand selection has no applicability. So if you had 20,000 Basecoin and minted 20,000, you'd get two 10k zerocoins, regardless whether you had "1000" set as the auto mint specification.

**Comment by JoenPool** [comment]
I had this one time, this is the situation i had, placed by grumpy. Please dont tell me how to remint :D I also asked MADOS if this should be an github issue because i never had this, it was a one time ''issue''. But i've get the advise to make an github issue anyway. That's why i reported it to grumpy so he could make an issue on github.

**Comment by rlloyd2001** [comment]
> What @seanPhill said — When manually minting, the left-hand selection has no applicability. So if you had 20,000 Basecoin and minted 20,000, you'd get two 10k zerocoins, regardless whether you had "1000" set as the auto mint specification.

That is confusing, the UI around that needs an update.
