### ISSUE TITLE
spendzerocoinmints does not recognize basecoin addresses for the destination field (Error -5)

### ISSUE THREAD

**Issue by CryptoMaximalist** [Veil-Project/veil#409]
When trying to use spendzerocoinmints to spend a specific coin, it is not possible to spend them to a basecoin address

Expected:  It would send 

Actual: failed,

```
~/Downloads/veil-1.0.1.5/bin/veil-cli spendzerocoinmints '["b....e"]' "bv1...uw"
error code: -5
error message:
Invalid VEIL address
```

no debug.log entries show during the attempt

**Comment by seanPhill** [comment]
Is there another use-case of spending specific zerocoinmints than for reminting, which can be done to CT?

Also, recent commit spends the oldest minted coins.
Also, basecoin is not long for this world.

So, I don't see any relevance to making this spend type spend to basecoin.

**Comment by seanPhill** [comment]
Making it clear in the Help text that this is only to spend zerocoins to stealth would be fine by me. (Not that I'm the okayer.)

**Comment by CryptoMaximalist** [comment]
The fact that I can't recover my CT funds from seed currently makes me uneasy minting there.  Basecoin is not deprecated yet

**Comment by seanPhill** [comment]
Have you tried (presstab's advice)?
```
RingCT or CT:
- Use abandontransaction <txid> true on any unconfirmed transactions. Then use rescanringctwallet.
- If that does not work, use rescanblockchain
- RingCT and CT addresses work with the same concept as deterministic zerocoins. Everytime you make a transaction a new address is generated from your seed and used as a change address. If someone's stealth seed has 1 address, then they are likely unable to see any coins on it. Use restoreaddresses <# to generate> to regenerate some of those addresses. Then use rescanblockchain.
```

**Comment by CryptoMaximalist** [comment]
yes, all posted recovery advice.  Happy continue on discord if you have further questions

**Comment by presstab** [comment]
Why can you not recover your CT funds? Can you link to an open issue with the details?

**Comment by veilgets** [comment]
Bounty: 333.33

**Comment by PeterL73** [comment]
This Issue seems to already be fixed (https://github.com/Veil-Project/veil/commit/afdbb1f00e9475225381265f56c86d2871602472)

**Comment by seanPhill** [comment]
TESTED (on a new basecoin address), and it works! Please close.

**Comment by codeofalltrades** [comment]
@veilgets please close. This is fixed.
