### ISSUE TITLE
Staking enabled at launch. Can't turn off/on with toggle or Unlock Wallet Fully/for Staking

### ISSUE THREAD

**Issue by VeilDango** [Veil-Project/veil#41]
https://i.imgur.com/TrPV6ME.png

3e. Staking is enabled at launch which I am not sure people want done automatically. I can't turn it off with the toggle or within Settings>Unlock Wallet for Staking or Unlock Wallet Fully

Reproducibility:

I can reliably reproduce the issue. Refer to screenshot.

Version used:

https://github.com/Veil-Project/veil/releases/download/testnet-1/veil-0.0.9-win64-setup-unsigned.exe

Hardware and OS:

6700k Intel CPU
Pro 970 SSD
32GB RAM
Windows 10 Pro

Debug.log:

https://cdn.discordapp.com/attachments/507024857847037962/527898028942688256/debug.log

**Comment by veildev** [comment]
check now please @VeilDango

**Comment by StrontiumZ38** [comment]
This can be closed.

**Comment by VeilDango** [comment]
Still can't toggle from the overview page. It would be convenient if I could click the toggle from overview page and it will let me unlock from overview instead of from Settings icon>Unlock Wallet for Staking

**Comment by StrontiumZ38** [comment]
This can be closed now

**Comment by 4x13** [comment]
fixed
