### ISSUE TITLE
File and Help have limited options that can be inside Cog settings icon. Exit too (or remove).

### ISSUE THREAD

**Issue by VeilDango** [Veil-Project/veil#42]
https://i.imgur.com/i2mqQdD.png

14. File and Help are not that needed. There is only Exit under File which is redundant with upper right X menu item to exit.

There's a list of command-line options, About Veil Core, and About Qt under Help. All these could be included within the Cog settings icon.

Reproducibility:

I can reliably reproduce the issue. Refer to screenshot.

Version used:

https://github.com/Veil-Project/veil/releases/download/testnet-1/veil-0.0.9-win64-setup-unsigned.exe

Hardware and OS:

6700k Intel CPU
Pro 970 SSD
32GB RAM
Windows 10 Pro

Debug.log:

https://cdn.discordapp.com/attachments/507024857847037962/527898028942688256/debug.log

**Comment by ianGre** [comment]
I feel that File (with Exit) and Help are _a minimum_ to keep in the menu structure, even if you can't be bothered to duplicate **every** function into the menu interface. For people with visual difficulties it can be essential to have the basic functions of software available where their screen reader can find and read it, or where they can find it themselves, when the GUI just doesn't communicate well, such as when they cannot notice the little grey lock in the bottom right hand corner, when they already searched all over the settings section for the encrypt wallet (or unlock wallet) function!
