### ISSUE TITLE
Startup Crash: chain.cpp:105: const CBlockIndex* CBlockIndex::GetAncestor(int) const: Assertion `pindexWalk->pprev' failed.

### ISSUE THREAD

**Issue by CryptoMaximalist** [Veil-Project/veil#422]
After a graceful shutdown, during a blockchain sync, the following startup error appears:

```
veil-qt: chain.cpp:105: const CBlockIndex* CBlockIndex::GetAncestor(int) const: Assertion `pindexWalk->pprev' failed.
Aborted (core dumped)
```

Expected: Wallet could start normally or handle issues

Actual: Error above, hard crash

Reliability: Every time once it happens

Version: Veil 1.0.2, Ubuntu 18.04 x64

**Comment by MisterKangaroo** [comment]
Had the same issue as described above.

Version: Veil 1.0.2, Ubuntu 18.04 x64

**Comment by presstab** [comment]
![latest_segfault](https://user-images.githubusercontent.com/6628210/55017635-bb81d100-4fb6-11e9-9072-85cc6a92af0e.png)

**Comment by toptim** [comment]
same with veild after poweroff
ubuntu 16
veild: chain.cpp:105: const CBlockIndex* CBlockIndex::GetAncestor(int) const: Assertion `pindexWalk->pprev' failed.
Aborted (core dumped)
