### ISSUE TITLE
Amount on transaction history items not calculating properly.

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#429]
I believe this to be an aspect of a previously closed issue so remaking as standalone.

**Describe issue**
Amount on transaction history items not calculating correctly (eg. staking shows as 2050 rather than 50)

**Comment by presstab** [comment]
Bounty Price: 416.67
Estimated Hours: 5

**Comment by veilgets** [comment]
Developer: codeofalltrades

**Comment by codeofalltrades** [comment]
@StrontiumZ38 staking is the only transaction type listed. Are there others that are not correct?

**Any transaction types missing from the list below?**
spendzerocoin = send zerocoin to basecoin/stealth
sendstealthtobasecoin = send CT to basecoin
sendringcttobasecoin = send RingCT to basecoin
sendtoaddress = send basecoin/stealth
sendbasecointostealth = send basecoin to stealth
sendringcttostealth = send RingCT to stealth

**Comment by 4x13** [comment]
That looks correct
