### ISSUE TITLE
Staking is visually turned on at launch, but in Settings it is not visually turned on.

### ISSUE THREAD

**Issue by VeilDango** [Veil-Project/veil#43]
https://i.imgur.com/NpNfzW2.png

Staking is visually turned on at launch, but in Settings it is not visually turned on for Unlock Wallet for Staking or for Unlock Wallet Fully

16a. It turns on Staking on launch according to bottom left, but in Settings it is not turned on.

Reproducibility:

I can reliably reproduce the issue. Refer to screenshot.

Version used:

https://github.com/Veil-Project/veil/releases/download/testnet-1/veil-0.0.9-win64-setup-unsigned.exe

Hardware and OS:

6700k Intel CPU
Pro 970 SSD
32GB RAM
Windows 10 Pro

Debug.log:

https://cdn.discordapp.com/attachments/507024857847037962/527898028942688256/debug.log

**Comment by veildev** [comment]
Check it now please.

**Comment by VeilDango** [comment]
If I click the toggle to toggle  it off, it says Miner Stopped. I am not sure what is being stopped. After clicking the toggle and disabling, it doesn't show it as being off within Settings icon>Unlock Wallet for Staking.

There is a ~6 second delay between toggling on and off on the overview screen. There is a ~4-5 second delay after clicking the toggle on Settings icon>Unlock Wallet for Staking before something happens.

At Settings icon>Unlock Wallet for Staking, trying to toggle it off from default on, it took me to "Encrypt wallet" pop-up to create a new password and confirm it.

After the wallet tries to shut down to encrypt it doesn't try to start up again, I have to start it up again. Trying to input wrong password at Settings icon>Unlock Wallet for Staking, I get a fatal error.

I can't input password by toggling on overview toggle. I have to go to Settings icon>Unlock Wallet for Staking.

**Comment by StrontiumZ38** [comment]
This can be closed.

**Comment by VeilDango** [comment]
Can't be closed. Still can't toggle from the overview page. It would be convenient if I could click the toggle from overview page and it will let me UNLOCK FROM THERE

**Comment by 4x13** [comment]
let me reiterate the issue here.. both 'Staking Switrches" Should function the same way as well as update the other switch. as it stands now, the one on the front page, turns staking on and of, but it should also check if the wallet is locked, if it is not locked, it should prompt the user to enter password to unlock. Same for the internal "Unlock for Staking Only" switch. both of these switches should function the same. if the wallet is not encrypted, then don't ask for a password.

**Comment by veildev** [comment]
check it on the next version and close this if it's done please.

**Comment by StrontiumZ38** [comment]
This is, from what I can tell, resolved. There are some inconsistencies still with unlocking, but I think they merit a new issue.
