### ISSUE TITLE
Allow Automint interval to be user selectable

### ISSUE THREAD

**Issue by 4x13** [Veil-Project/veil#433]
Add a time option to automint in the GUI to allow the user to select how frequent automint should do it's thing

**Comment by furszy** [comment]
PR for this already opened 11 days ago. #411

**Comment by veildev** [comment]
@4x13 PR for this already opened 11 days ago. #411

**Comment by 4x13** [comment]
ok, it was a WIP last I checked. if it is completed, then this should be closed.

**Comment by veilgets** [comment]
Bounty: 375
