### ISSUE TITLE
Automint should use all coin types

### ISSUE THREAD

**Issue by 4x13** [Veil-Project/veil#434]
Automint should select from all coin types, not just basecoin. Automint should also be able to select partial amounts from multiple coin types to create the chosen zerocoin.

**Comment by seanPhill** [comment]
Maybe we could change the default automint denom from ten to a hundred?
Ten would have been okay in January. People spending (to stealth) out of tens (to mint hundreds or thousands) might not want them autominted right back again.
But it would be cool if they would automint from CT/RingCT in a higher denom.

**Comment by 4x13** [comment]
Kind of off point for my suggestion. ATM, automint only uses basecoin, where it should use all coin types. Users can already select their preferred denom.
