### ISSUE TITLE
Add ability for user to select overall security level

### ISSUE THREAD

**Issue by 4x13** [Veil-Project/veil#436]
I would like to see an option for the user to choose the security level, default should be 100 for everything from staking, precomputing and spends. The user should be able to select from a reasonable base level like 42-60 all the way to the default security level of 100.

I am assuming this would allow the user to slightly reduce the overhead caused by spending as well as precomputing and staking.

**Comment by presstab** [comment]
I vote against this, and in favour of removing the concept of security level altogether. Using small security levels significantly leaks timing metadata.

**Comment by Fuzzbawls** [comment]
doesn't precompute essentially render the whole security level thing redundant anyways?
