### ISSUE TITLE
Staking debug log spam

### ISSUE THREAD

**Issue by CryptoMaximalist** [Veil-Project/veil#437]
My debug log was filled with 83,318 copies of "FOUND 0 STAKABLE ZEROCOINS" during the block before my first zerocoins became eligible to stake.  I had staking enabled, the wallet unlocked, and 2 coins becoming mature during that block, and another the next block.  The debug.log file was not producing this entry or anything staking related before this point.  The file became 9.8mb after this happened.  Others have reported giant debug log sizes, but their's were in the GB range

veild 1.0.2 x64, ubuntu 18.04 x64

```
grep "SelectStakeCoins: FOUND 0 STAKABLE ZEROCOINS" debug.log | wc -l
83318
```

**Comment by blondfrogs** [comment]
@CryptoMaximalist Are you enabling a debug flag on starting the Veil client or in the veil.conf

e.g. -debug=**n**

**Comment by CryptoMaximalist** [comment]
oh yeah, debug=blockcreation

**Comment by StrontiumZ38** [comment]
So Max does that make this a bug or a feature? If the latter, perhaps we can give warning when sharing the debug=blockcreation flag that this is something likely to take place. I see a fair bit of flag console command slinging on Discord with little to no explanation of what it does or how, which is dangerous really as it leaves people open to being unintentionally mislead or even scammed.

**Comment by presstab** [comment]
This could be reduced for sure. But also, you can opt out by removing `debug=blockcreation`.

**Comment by blondfrogs** [comment]
I don't think this is a bug or feature. I vote to close this issue.
