### ISSUE TITLE
Staked blocks don't broadcast, 100% orphans

### ISSUE THREAD

**Issue by CryptoMaximalist** [Veil-Project/veil#439]
I'm not sure this is titled correctly, but here is the issue as I have seen it:  

Staking is active: true, debug=blockcreation shows staking happening as normal, everything looks correct and the wallet even wins some blocks.  It then creates the transaction, adds it to your chain, and then it gets orphaned.  It looks like bad luck, but this happens 100% of the time.  The only strange thing I notice is that my staked blocks and tx don't seem to be on the block explorer, so perhaps they aren't being broadcast?  Normally they will show up at least until they are orphaned

As a workaround once this has happened, running the following commands seems to fix it.  I have not seen the issue return but it's only been a week since I've seen 3 cases.
rescanblockchain
rescanzerocoinwallet
-reindex-zdb

veil v1.0.2 x64 on ubuntu 18.04 x64 in two cases, another user on v1.0.2 on unknown platform

Happy to provide debug logs in private

**Comment by presstab** [comment]
Try adding debug=net and see what else you see in there.

**Comment by CryptoMaximalist** [comment]
It is currently fixed on my mainnet net, but I"ll try this if it comes back on my main or testnet nodes.  Would it be proper to have 2 debug lines:

debug=blockcreation
debug=net

**Comment by veilgets** [comment]
I’ve heard from other users that the following commands also appear to help:
Reconsiderzerocoins
resetspentzerocoins
resetmintedzerocoins true.

**Comment by CryptoMaximalist** [comment]
running rescanblockchain and rescanzerocoinwallet fixed this for me
