### ISSUE TITLE
Backup Wallet tries to save in My Computer>Documents without write access

### ISSUE THREAD

**Issue by VeilDango** [Veil-Project/veil#44]
https://i.imgur.com/cW8hsa5.png

17. When I click Backup Wallet, it tries to save Wallet Data (*.dat) file in My Computer>Documents. For Windows, this directory+subdirectories can be protected from write access by apps like wallets. Default should be somewhere like C>Users>USERNAME, Downloads folder, or the Veil data directory (I prefer). When I try to backup again, it doesn't remember my last saved location, instead it takes me back to My Computer> Documents

Reproducibility:

I can reliably reproduce the issue. Refer to screenshot.

Version used:

https://github.com/Veil-Project/veil/releases/download/testnet-1/veil-0.0.9-win64-setup-unsigned.exe

Hardware and OS:

6700k Intel CPU
Pro 970 SSD
32GB RAM
Windows 10 Pro

Debug.log:

https://cdn.discordapp.com/attachments/507024857847037962/527898028942688256/debug.log

**Comment by 4x13** [comment]
fixed per strontium
