### ISSUE TITLE
'getblockstats' doesn't always work 1.0.2.0

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#440]
Entering geblockstats (block) doesn't always work. It instead returns Unexpected internal error (tx index seems corrupt) (code -32603)
Confirmed by Rock-N-Troll, random.zebra

**Comment by presstab** [comment]
Bounty Price: 281.25

**Comment by MatWaller** [comment]
Example of block that gives `Unexpected internal error (tx index seems corrupt) (code -32603)` error consistently.

```
getblockstats 19187
```

**Comment by veilgets** [comment]
reopened
Bounty: 281.25

**Comment by veilgets** [comment]
developer: CaveSpectre11

**Comment by CaveSpectre11** [comment]
Ready for QA/Code Review - PR #650

**Comment by codeofalltrades** [comment]
closed via #650
