### ISSUE TITLE
rpc call spendzerocoin fails when no destination address is given

### ISSUE THREAD

**Issue by blondfrogs** [Veil-Project/veil#446]
The rpc call says that it will generate a change address that the zerocoins will be minted to but it doesn't which causes the spend to fail. 

example call "spendzerocoin 10 false true 100 "" 10"

To fix this, we need to generate a change address if an address isn't given when this rpc is called.

**Comment by blondfrogs** [comment]
In order to fix this, we need to know what type of address will be created when making this call. Should we even allow this to be called without a destination address?

**Comment by 4x13** [comment]
I would say it should be a stealth address, but I don't know if that is possible right now. I believe we need to fix the zerocoin protocol to allow for spending directly to CT address type in lew of un-shielded basecoin (This is on the list to be done)

**Comment by blondfrogs** [comment]
Closing, as a new issue will be created with the proposed fix to this.
