### ISSUE TITLE
Move precompute to own database, and improve database shutdown sequence

### ISSUE THREAD

**Issue by blondfrogs** [Veil-Project/veil#450]
Because precomputing isn't consensus based, it needs its own database location that can be removed at any time. 
Precomputing is solving zerocoin proofs, which live in the wallet. So a good location for the precompute database could be **wallet/precomputes**

**Comment by CryptoMaximalist** [comment]
Are there any privacy or security concerns with storing the precompute data presumably unencrypted?

I remember early zerocoin stored zerocoin data like serials outside of the encrypted space of the wallet.dat

**Comment by blondfrogs** [comment]
@CryptoMaximalist All data that is stored in the precompute database is public data. No serials are stored outside of the wallet.dat.
