### ISSUE TITLE
Renaming stealth address label "stealth" to another name causing segmentation fault

### ISSUE THREAD

**Issue by vereten** [Veil-Project/veil#452]
> Describe the issue:

Renaming first stealth address label "stealth" to another name causing segmentation fault .

> What behavior did you expect?:

Wallet functionality to be not dependent on address label. 

> What was the actual behavior (provide screenshots if the issue is GUI-related)?:

![Screenshot at 2019-03-03](https://user-images.githubusercontent.com/11050858/54811364-d38ce400-4c88-11e9-88c2-1340c50022e4.png)
![Screenshot at 2019-03](https://user-images.githubusercontent.com/11050858/54811372-d7206b00-4c88-11e9-9009-275f773848d1.png)

> How reliably can you reproduce the issue, what are the steps to do so?:

Rename default wallet address label "stealth" to another name and restart wallet.

> What version of the Veil client are you using, where did you get it (website, self-compiled, etc)?:

tested on 1.0.2 also self-compiled from latest git

**Comment by drag0ng** [comment]
I don't think this is still happening.

<img width="1098" alt="vei" src="https://user-images.githubusercontent.com/44994855/55601882-d9b6a200-5717-11e9-84d8-16b1dcda36c7.png">

**Comment by vereten** [comment]
Did you try to restart wallet after renaming?

**Comment by drag0ng** [comment]
yes. I did.

**Comment by veilgets** [comment]
Bounty: 166.67

**Comment by ClashLuke** [comment]
Isnt it looking for an address with the label stealth, so if you rename it, its not a stealth address anymore which is still supposed to be treated like a stealth address, causing your program to segfault?

**Comment by veilgets** [comment]
Developer: rikublock

**Comment by rikublock** [comment]
Ready for QA
