### ISSUE TITLE
Segfault on latest precomputing test branch

### ISSUE THREAD

**Issue by 4x13** [Veil-Project/veil#456]
Segfault after shutting down to make a chain backup. Wallet was running for a few days without issue, and is running on latest Ubuntu 64/ latest pre-computing test branch.

![latest segfault](https://user-images.githubusercontent.com/39984029/55022676-57f8a300-4fb8-11e9-8e12-48aea6f72cbc.png)

then upon restoring from a known good chain snapshot I get this segfault

![next_segfault](https://user-images.githubusercontent.com/39984029/55022710-69da4600-4fb8-11e9-9b74-b6dd96eb8067.png)

I will try syncing from scratch on this wallet, and then restoring from seed to recover if that doesn't work. will report back.

**Comment by blondfrogs** [comment]
@4x13 Now that precomputing has been merged into the master branch. Are you still seeing this occur?

**Comment by veilgets** [comment]
Bounty: 1111.11
