### ISSUE TITLE
Failed to add standard inputs (code -4) when doing zerocoin spend

### ISSUE THREAD

**Issue by 4x13** [Veil-Project/veil#458]
I am unable to get past this error. I have completed all of the following and yet the error still exists since I used the latest precomputes branch. Even if I revert back to the release branch and restore via the seed.

resetmintzerocoin
resetspendzerocoin
rescanzerocoinwallet
restore from seed phrase
searchdeterministiczerocoin 0 40000 4

I am confused by the error message as well as the log enbtry as it shows an error with RingCT as well each time I get this error. as well as what input is involved when spending a zerocoin aside from the zerocoin being spent??

[unable to spend zerocoin on latest branch](https://user-images.githubusercontent.com/39984029/55134770-fedb5d00-50e6-11e9-9be4-03eedcbdad43.png)

**Comment by StrontiumZ38** [comment]
I can try to recreate.
Were you spending to yourself?
Were you expecting change from the spend? (I wonder if it may be something to do with this and not the Zerocoin itself)
Anything else I should know?
Cheers

**Comment by 4x13** [comment]
This issue has been discovered to be a fee issue.
