### ISSUE TITLE
When I click Select file, it starts in the My Computer>Documents folder without write access.

### ISSUE THREAD

**Issue by VeilDango** [Veil-Project/veil#46]
https://i.imgur.com/KVJrjrF.png

19b. When I click Select file, it starts in the My Computer>Documents folder. The starting directory should either be C>Users>USERNAME, Downloads folder, the Veil data directory, or the LAST place where a Wallet Data *.dat backup was saved (I prefer).

Reproducibility:

I can reliably reproduce the issue. Refer to screenshot.

Version used:

https://github.com/Veil-Project/veil/releases/download/testnet-1/veil-0.0.9-win64-setup-unsigned.exe

Hardware and OS:

6700k Intel CPU
Pro 970 SSD
32GB RAM
Windows 10 Pro

Debug.log:

https://cdn.discordapp.com/attachments/507024857847037962/527898028942688256/debug.log

**Comment by StrontiumZ38** [comment]
There are still two of this issue. It's not yet solved, but one should be closed to clear up issues.

**Comment by 4x13** [comment]
fixed
