### ISSUE TITLE
Add syncing indicators to lower bar in GUI

### ISSUE THREAD

**Issue by 4x13** [Veil-Project/veil#462]
Add a visual indicator next to the lock icon that shows the wallet is syncing and the block number and an indicator that it is synced to the tip of the chain.

**Comment by presstab** [comment]
By visual indicator, do you mean progress bar? This is something that is in the new GUI mockup, so best to leave this issue as untouched until the mockup is finalized and the build up of the new GUI begins.

**Comment by presstab** [comment]
Bounty: 500
Estimated Hours: 6

**Comment by veilgets** [comment]
Developer: MatWaller

**Comment by MatWaller** [comment]
This one is pretty straight forward as we already have access to the progress percentage.

I'll see what I can come with up.

Thanks.

**Comment by MatWaller** [comment]
closed with #543

**Comment by codeofalltrades** [comment]
closed with #543
