### ISSUE TITLE
Precompute not able to keep up with new blocks

### ISSUE THREAD

**Issue by seanPhill** [Veil-Project/veil#463]
I've tested precompute on two wallets, 

- ONE, on testnet with many, many zerocoins, generating new stake rewards every two minutes or more frequently, and continually trying to spend the ten denoms out to CT for minting into ten thousand denoms. Using `showspendcaching` I saw that it continually got further and further behind, so I turned off precomputing.
- TWO, on mainnet with a wallet that had only one 10K denom in it. It did win one stake reward overnight, but it has been twenty hours since, and twenty hours before that (while not on precomputing) that it had not won. 

With the additional five tens, I checked the precomputing and it was not keeping up. So I spent the five tens into CT and another four hundred from my other wallet and minted four hundreds. With the four freshly minted hundreds, and the less than a day old 10K, I also found that precomputing was not able to complete and was falling behind _most of the time._

With six coins (1x10K + 5x10) only:
```
showspendcaching
[
  {
    "total_blocks_computed": 1482,
    "total_blocks_to_compute": 2820,
    "percent_precomputed": 52.55319148936171
  }
]
```
four and a half minutes later:
```
[
  {
    "total_blocks_computed": 1482,
    "total_blocks_to_compute": 2856,
    "percent_precomputed": 51.89075630252101
  }
]
```
Later, with the four hundreds and the one 10K:
```
01:12:47
￼showspendcaching

01:12:47
￼[
  {
    "total_blocks_computed": 307,
    "total_blocks_to_compute": 531,
    "percent_precomputed": 57.81544256120527
  }
]
```
Twenty seven minutes later:
```
showspendcaching

01:39:56
[
  {
    "total_blocks_computed": 327,
    "total_blocks_to_compute": 704,
    "percent_precomputed": 46.44886363636363
  }
]
```
For further background, I have `-threadbatchverify` set to 4 on a six core Xeon with SSD and 32GB RAM in macOS, and am running the latest Blondfrogs precompute final.

I have since turned off precomputing as it continued to mostly fall behind.

If I can catch a stake reward on this 10K one more time I'd like to remint it to hundreds, in case being a 10K it is regularly _attempting_ to stake, which _maybe_ is interfering with precomputing?

**Comment by seanPhill** [comment]
Should I do something like `precomputeblockpercycle=200` in the conf file? (Or also force precomputing on with `precompute=1`?

**Comment by seanPhill** [comment]
I just found this:```
setprecomputeblockpercycle 1000
```

**Comment by seanPhill** [comment]
Currently at ```
[
  {
    "total_blocks_computed": 2798,
    "total_blocks_to_compute": 5162,
    "percent_precomputed": 54.20379697791554
  }
]
```

**Comment by seanPhill** [comment]
I think this is relevant to ask in here. With `setprecomputeblockpercycle 1000` over half an hour this is all the progress I am getting, still on a tiny number of zerocoins. Which way should I optimise the settings for precomputing on a XEON 6-core computer with 32GB RAM and SSD? And what would be the advice for a more modest computer? 
```
showspendcaching
10:33:35
￼
[
  {
    "total_blocks_computed": 3248,
    "total_blocks_to_compute": 5337,
    "percent_precomputed": 60.85816001498969
  }
]

showspendcaching
11:04:00
￼
[
  {
    "total_blocks_computed": 3518,
    "total_blocks_to_compute": 5683,
    "percent_precomputed": 61.90392398381137
  }
]
```

**Comment by 4x13** [comment]
if you start out with thousands of mints, and are also doing spends from the same wallet at the same time, you will always have issues..

**Comment by Rock-N-Troll** [comment]
```
[
  {
    "total_blocks_computed": 2619138,
    "total_blocks_to_compute": 2755943,
    "percent_precomputed": 95.03600038172053
  }
]
```

My numbers are much larger than yours and I have had no problem staying at 95% after initial start.

**Comment by 4x13** [comment]
I believe he is on testnet with thousands of 10 denoms, but in normal use cases, once you are caught up, it should stay that way

**Comment by seanPhill** [comment]
The actual spendcache examples above are from the mainnet wallet with only a small number of coins. The testnet wallet was thoroughly overwhelmed, and definitely could not keep up.

My mainnet wallet is now at about 80%, but the question of how to optimise the settings, what might make it get more precomputing done within a reasonable amount of time, those questions remain.

**Comment by seanPhill** [comment]
And it seems to be be working nicely on the mainnet one, since it exceeded 80% completed, anyway.

**Comment by seanPhill** [comment]
I'm closing this issue, because it eventually catches up okay, except maybe if it has thousands of old tens. The higher `setprecomputeblockpercycle` rate seems that it might not improve things, with the default, 100(?) possibly being the most efficient for a generic setup.
