### ISSUE TITLE
Feature request - disable Zerocoin automint in GUI

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#465]
This is to propose an additional option to the zerocoin minting window, allowing for minting to be disabled if the user prefers to manually control their minting how and when they wish. It includes a new radio option, and a note explaining that improperly handling this option will hurt their staking ability.
![image](https://user-images.githubusercontent.com/38264865/55306181-4454ad00-548e-11e9-806c-bc0a0ef741f7.png)

**Comment by 4x13** [comment]
NACK - This requests goes against maintaining always privacy on and private by default.

**Comment by presstab** [comment]
This has been discussed many times, and the answer has always been to not do this. Until there is wider support for this issue, I am going to keep it closed.
