### ISSUE TITLE
Feature Request: 16 Individual PoW Algorithm Difficulties RPC call

### ISSUE THREAD

**Issue by Rock-N-Troll** [Veil-Project/veil#470]
This feature request calls for creating an RPC call that returns each of the 16 algorithm difficulties at a given blockheight.

The reasoning for making this request is because currently there is no easy way to determine what the PoW difficulty of a block means. It fluctuates wildly but really doesn't mean anything to potential miners and it isn't very useful when graphing difficulty increases and decreases over time. However, with the proposed feature request in place, being able to see how the 16 different PoW algorithm difficulties change over time will be useful for determining things such as: What algorithms are "weak"? Which algorithms are "strong"? And other analysis of different algorithms chained together in combination with each other over time. 

Additionally, graphing or displaying PoW difficulty (which is often a sign of network strength to users) will be much clearer if broken up into individual components instead of the current "lump sum chained average" that the PoW difficulty currently represents.

If my thought process is correct (which is just a guess) Dev blondfrogs thinks there is a way but I am unsure exactly how it would work (Thank you for our chat, blondfrogs.)), this could possibly be achieved the same way that the current zerocoin supply of each denom is calculated and retrieved at each block using the ```getzerocoinsupply blockheight``` command

**getzerocoinsupply 16000**
```
[
  {
    "denom": "10",
    "amount": 49109000000000,
    "percent": 61.40153084106412
  },
  {
    "denom": "100",
    "amount": 7650000000000,
    "percent": 9.5648803871824
  },
  {
    "denom": "1000",
    "amount": 2900000000000,
    "percent": 3.62590236899725
  },
  {
    "denom": "10000",
    "amount": 0,
    "percent": 0
  },
  {
    "denom": "total",
    "amount": 59659000000000,
    "percent": 74.59231359724377
  }
]
```

Currently, the **x16r** and **x16rt** algorithms utilize 16 different algorithms chained together with Veil using **x16rt** and **x16r** existing in coins like RavenCoin.

https://en.bitcoinwiki.org/wiki/X16R:

```
List of algorithms:

0=blake
1=bmw
2=groestl
3=jh
4=keccak
5=skein
6=luffa
7=cubehash
8=shavite
9=simd
A=echo
B=hamsi
C=fugue
D=shabal
E=whirlpool
F=sha512

Example:

Previous block hash: 0000000000000000007e8a29f052ac2870045ae3970270f97da00919b8e86287
```
The final 8 bytes: ​**0x7da00919b8e86287**
```
Each hex digit (nibble) determines which algorithm to use next. cubehash(7) -> shabal(d) -> echo(a) -> blake(0) -> blake(0) -> simd(9) -> bmw(1) -> simd(9) -> hamsi(b) -> shavite(8) -> whirlpool(e) -> shavite(8) -> luffa(6) -> groestl(2) -> shavite(8) -> cubehash(7)
```
the main difference between **x16r** and **x16rt** is the "t" is for **timestamp** (or time).
The **blockhash** is not used for creating the `"(nibble) which determines which algorithm to use next."`, but instead a special hasing/manipulation of the block's timestamp is used for creating the `"(nibble) which determines which algorithm to use next.""`

It is a special function that hashes/mutates the current block timestamp (which also ends up being a **_uint256_** like the **blockhash** which is used in **x16r** which makes the **x16r** vs **x16rt** very similar except for this slight difference)

So the call I'm proposing would essentially be something like ```getpowdifficulty blockheight```:

**getpowdifficulty 16000**
```
[
  {
    "algorithm": "blake",
    "difficulty": 49038
  },
  {
    "algorithm": "bmw",
    "difficulty": 3735
  },
  {
    "algorithm": "groestl",
    "difficulty": 23423
  },
  {
    "algorithm": "jh",
    "difficulty": 11001
  },
  {
    "algorithm": "keccak",
    "difficulty": 33838
  },
  {
    "algorithm": "skein",
    "difficulty": 33342
  },
  {
    "algorithm": "luffa",
    "difficulty": 19883
  },
  {
    "algorithm": "cubehash",
    "difficulty": 100030
  },
  {
    "algorithm": "shavite",
    "difficulty": 382934
  },
  {
    "algorithm": "simd",
    "difficulty": 99193
  },
  {
    "algorithm": "echo",
    "difficulty": 39933
  },
  {
    "algorithm": "hamsi",
    "difficulty": 64413
  },
  {
    "algorithm": "fugue",
    "difficulty": 1883
  },
  {
    "algorithm": "shabal",
    "difficulty": 389489
  },
  {
    "algorithm": "whirlpool",
    "difficulty": 30033
  },
  {
    "algorithm": "sha512",
    "difficulty": 76767
  }
]
```

**Comment by blondfrogs** [comment]
The PoW difficulty is basically a number that the blockhash needs to be below. X16RT doesn't have separate difficulty for each algorithm. 


e.g. Difficulty: 00000546790
e.g Valid PoW block: 00000446790
e.g Not Valid PoW block: 00001546790

**Comment by Rock-N-Troll** [comment]
We spoke about this via Discord and our conversation went like this which is why I thought this was possible:

**Rock-N-Troll:**
> "Is there any way to get the individual difficulties out of the combined difficulty? I know the Algos are chained together and in a specific way for each block, but is it possible to do a better estimate than dividing and bucketing and by dividing by 16?"

**blondfrogs:**
> "Um, i think they would need to be calulated seperately"

**Rock-N-Troll:**
> "It's possible to get individual difficulties?"

**blondfrogs:**
> "I could write something to give that information. I am not sure if it exists already.
> If you need it could you create an issue on github requesting this, and why you need it."

..................

**Rock-N-Troll:**
> "Oh thatd be great if you think it's possible. I'll make a feature request later tonight then."

**blondfrogs:**
"yeah. make sure you put exactly what you need.
That way when us devs have a sprint planning we can figure out if we can get it done in the next sprint."

**Comment by blondfrogs** [comment]
Oh. I thought you were talking about the two separate difficulties, Proof of Stake diff, vs Proof of Work.

**Comment by blondfrogs** [comment]
Oh. I thought you were talking about the two separate difficulties, Proof of Stake diff, vs Proof of Work.

**Comment by blondfrogs** [comment]
Oh. I thought you were talking about the two separate difficulties, Proof of Stake diff, vs Proof of Work.

**Comment by blondfrogs** [comment]
Oh. I thought you were talking about the two separate difficulties, Proof of Stake diff, vs Proof of Work.

**Comment by Rock-N-Troll** [comment]
I think that is already in the wallet which explains why you thought it might already be there. Feel free to close this feature request if it isn't possible.

**Comment by Rock-N-Troll** [comment]
I think that is already in the wallet which explains why you thought it might already be there. Feel free to close this feature request if it isn't possible.

**Comment by blondfrogs** [comment]
Closing as it isn't possible.
