### ISSUE TITLE
getbalance only shows basecoin balance

### ISSUE THREAD

**Issue by CryptoMaximalist** [Veil-Project/veil#474]
The getbalance command only shows the spendable basecoin balance
Veil v1.0.2

**Comment by seanPhill** [comment]
Should we make it an alias for getbalances or would you want this to be a grand total?

**Comment by CryptoMaximalist** [comment]
I assume a grand total is the intention

**Comment by blondfrogs** [comment]
Closing as this rpc call is working as intended. A new rpc call will be created to get the full balance of the wallet.

**Comment by seanPhill** [comment]
I can accept that, as having a standard getbalance call that reveals zero (basecoin) balance is a bit of a veil over a possibly high value account, that might help it escape the attention of hackers. :)

**Comment by MatWaller** [comment]
#574 How about that? @seanPhill
