### ISSUE TITLE
Add reindexing progress to statusbar when reindexing blocks.

### ISSUE THREAD

**Issue by Rock-N-Troll** [Veil-Project/veil#476]
Instead of just displaying "Reindexing blocks on disk..." in the main wallet GUI, it should show the current progress: something like "Reindexing blocks on disk...(56.54%)"

Screenshot provided by Hort:

![image](https://user-images.githubusercontent.com/34344520/55588782-a6b2e500-56fc-11e9-9dff-95b42baa6c01.png)

**Comment by presstab** [comment]
Bounty: 208.3
Estimated Hours: 2.5

**Comment by veilgets** [comment]
Developer: drag0ng
