### ISSUE TITLE
Miscellaneous GUI/Display Bugs: Send Screen

### ISSUE THREAD

**Issue by Rock-N-Troll** [Veil-Project/veil#488]
In the send screen, it is impossible to send any value in the last decimal place. Attached is a screenshot that shows the last digit not being populated after trying to put in the maximum number of characters possible into the main screen as shown in the top right of the screenshot.

![image](https://user-images.githubusercontent.com/34344520/55842333-07795d80-5b01-11e9-857e-04beb617c40a.png)

This is an extra issue that is probably not GUI related, but an empty error message pop-up can happen when using odd (but should still be possible) decimal places:
![image](https://user-images.githubusercontent.com/34344520/55842576-2fb58c00-5b02-11e9-8188-d08e0f0826aa.png)

Additionally, it looks like commas are allowed to be entered but don't work at all anyway.

![image](https://user-images.githubusercontent.com/34344520/55842473-b6b63480-5b01-11e9-849c-d03ca38fb39f.png)

![image](https://user-images.githubusercontent.com/34344520/55842493-d188a900-5b01-11e9-8520-33cf87766a67.png)

Miscellaneous error messages
```
2019-04-10T00:00:15Z ERROR: ringctwallet AddStandardInputs_Inner: Failed to calc fee
2019-04-10T00:00:15Z ERROR: CreateZerocoinSpendTransaction: AddStandardInputs failed: 
2019-04-10T00:00:15Z ERROR: PrepareZerocoinSpend : Failed to add standard inputs
```

**Comment by 4x13** [comment]
good catch on the initial issue, should defintiely be fixed.. :) the second issue is actually telling you that there is a problem before you hit send (the red underline) But, I am thinking maybe it should just not allow commas to be written regardless??

**Comment by StrontiumZ38** [comment]
Wonder why comma is allowed. CSV perhaps? Probably just an oversight, but maybe devs did on purpose?

**Comment by codeofalltrades** [comment]
@StrontiumZ38 EU Currency Formatting? https://docs.microsoft.com/en-us/globalization/locale/currency-formatting
