### ISSUE TITLE
Forked on testnet after stop mining

### ISSUE THREAD

**Issue by ianGre** [Veil-Project/veil#5]
Yesterday morning my testnet wallet info said current number of blocks 5920, but getblockchaininfo said blocks: 5930 and headers 5939. (It was up to 5939 when I restarted and reindexed it.) The block hash for 5930 checked out okay with the block explorer at https://veil-testnet.randomzebra.party/block/4134593f3a2c29da69cb4d01e1ed2c81c014a425d0e85f529e093b5008e6bead

**Comment by ianGre** [comment]
It looks like the bad blocks after this were from when I stopped mining, by typing "generatecontinuous false" in the debug Console.

**Comment by dickvalis** [comment]
Also unable to find any peers on testnet

**Comment by ianGre** [comment]
Hi Dick. Are you in the Discord? Might be able to get some IP addresses in there. There's an invite link on the project's website.

**Comment by ianGre** [comment]
I found a server with a veil testnet peer running.
veil.suprnova.cc -> 145.239.0.50
--> addnode 145.239.0.50 add
(while in Debug Console)

**Comment by 4x13** [comment]
These should get you going until the testnet stabilizes.

addnode=107.191.47.215
addnode=37.187.140.168
addnode=veil.suprnova.cc
addnode=191.102.122.182
addnode=71.38.91.110


whitelist=107.191.47.215
whitelist=37.187.140.168
whitelist=191.102.122.182
whitelist=71.38.91.110(edited)
whitelist=145.239.0.50

**Comment by ianGre** [comment]
This addnode(s) list has proven helpful in getting people synced. Thanks.
