### ISSUE TITLE
Wallet allows alphabets and special characters for Amount input

### ISSUE THREAD

**Issue by VeilDango** [Veil-Project/veil#50]
https://i.imgur.com/n6ZxcGD.png

24b. Wallet allows me to type in alphabets and special characters for Amount. It should only allow numbers 0-9.

Reproducibility:

I can reliably reproduce the issue. Refer to screenshot.

Version used:

https://github.com/Veil-Project/veil/releases/download/testnet-1/veil-0.0.9-win64-setup-unsigned.exe

Hardware and OS:

6700k Intel CPU
Pro 970 SSD
32GB RAM
Windows 10 Pro

Debug.log:

https://cdn.discordapp.com/attachments/507024857847037962/527898028942688256/debug.log

**Comment by veildev** [comment]
Done on `gui-fixes` branch.

**Comment by VeilDango** [comment]
Lets me type in "e" still but small issue.
