### ISSUE TITLE
Add the ability to designate what denom should be precomputed and ignore the other denoms that exist

### ISSUE THREAD

**Issue by 4x13** [Veil-Project/veil#500]
Meaning, add a selector of ALL, 10, 100, 1000, 10000 so if a user wants to designate the wallet to staking only, they can fine tune which denoms are precomputed.

**Comment by veilgets** [comment]
Bounty: 312.50

**Comment by codeofalltrades** [comment]
Closing. 
Precompute was removed in release v1.0.4.4
Zerocoin denoms will be removed in a future release.
