### ISSUE TITLE
Make Block Processing and Computing Spends use their own threads

### ISSUE THREAD

**Issue by 4x13** [Veil-Project/veil#501]
Issue I am seeing is that when doing spends, or staking and spending a zerocoin at the same time, stops the wallet from processing blocks, so the wallet will get stuck on occasion and not recover without a restart.

The log shows nothing, and gdb doesnot crash, the wallet just hangs and processes no new blocks.

**Comment by 4x13** [comment]
Also upon restart, the wallet rewinds the chain around 1400 blocks and the log says

CleanBlockIndexGarbage: Erasing 12411 irrelevant indexes

not sure if this pertains to that.

**Comment by presstab** [comment]
They are on their own threads.
