### ISSUE TITLE
Feature Request: Text Input Boxes (I.E. Unlock Wallet) Should Work With ENTER Key

### ISSUE THREAD

**Issue by Rock-N-Troll** [Veil-Project/veil#502]
Most text box inputs in the wallet do not respond to the ENTER key despite it being the default user experience instinct. 

As an example, the "Unlock Wallet" password input pop-up requires clicking UNLOCK to actually confirm the action.

The same can be said for the SEND screen and most confirmation pop-ups in the GUI. Whether or not it is a good idea to allow ENTER in all scenarios is to be determined.

However, I think it can be agreed that clicking ENTER after typing a password into the UNLOCK WALLET pop-up should not be an issue.

**Comment by MatWaller** [comment]
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

The enter key seems to submit and unlock wallet for me with the above setup.

What is your setup i will try reproduce in a VM.

**Comment by blondfrogs** [comment]
The ability to use the enter key to unlock that wallet was added in #454. Other prompts will need to add this feature

**Comment by veilgets** [comment]
Bounty: 250

**Comment by veilgets** [comment]
Developer: drag0ng
