### ISSUE TITLE
GUI Bug Fix: Toggle Switches Do Not Always Respond To Clicks

### ISSUE THREAD

**Issue by Rock-N-Troll** [Veil-Project/veil#503]
It looks like the GUI Toggle buttons do not have the expected "hit box" or "click box" that would be expected of them as displayed on the screen. 

In my experience, clicking on the text associated with the toggle has always worked for me, but clicking on the toggle directly in some cases does nothing.

Because this is a cross-platform display GUI issue and I imagine it isn't a simple fix, the fix for this should be built and tested across multiple wallet builds before submitting the fix if possible.

![image](https://user-images.githubusercontent.com/34344520/56083380-2f630c80-5df2-11e9-86e3-c12f8fb956da.png)

Clicking the areas in red has no effect despite it being the first or second choice as user action for making the toggle to change state. Alternatively, drag and slide would be the other first user expected experience which also doesn't work.

**Comment by veilgets** [comment]
Bounty: 361.1

**Comment by veilgets** [comment]
Developer: Matwaller

**Comment by MatWaller** [comment]
Ready for QA
