### ISSUE TITLE
GUI Text Change Request: "Enter address" should be "Enter address label"

### ISSUE THREAD

**Issue by Rock-N-Troll** [Veil-Project/veil#505]
This is fairly self-explanatory but should be corrected anywhere in the wallet that a "label" is asked for but the default text is "Enter address". This issue at the very least occurs  in the address book section of the wallet but might appear in other sections such as the send or receive screen.

![image](https://user-images.githubusercontent.com/34344520/56083633-9cc46c80-5df5-11e9-90c0-85956637e93d.png)

**Comment by MisterKangaroo** [comment]
https://github.com/Veil-Project/veil/pull/506

**Comment by MisterKangaroo** [comment]
Fix already merged into master... pls check and close the issue if it fixed the issue

**Comment by blondfrogs** [comment]
Closing as #508 already fixed this issue
