### ISSUE TITLE
GUI Bug: Generate Address Icon doesn't work

### ISSUE THREAD

**Issue by Rock-N-Troll** [Veil-Project/veil#509]
Clicking the "Generate Address" circle arrow icon in the bottom left of the Receive screen shows a pop up for "address generated" but it doesn't do anything

![image](https://user-images.githubusercontent.com/34344520/56085776-0ef97900-5e17-11e9-95c8-62641f232a13.png)

but the debug log shows:

> 
> 2019-04-13T22:06:13Z GUI: QObject::connect: No such slot AddressesWidget::hideThisWidget() in qt/veil/addresseswidget.cpp:283
> 2019-04-13T22:06:13Z GUI: QObject::connect:  (receiver name: 'AddressesWidget')
> 2019-04-13T22:06:15Z GUI: QObject::connect: No such slot ReceiveWidget::hideThisWidget() in qt/veil/receivewidget.cpp:203
> 2019-04-13T22:06:15Z GUI: QObject::connect:  (receiver name: 'ReceiveWidget')
> 2019-04-13T22:06:18Z GUI: QObject::connect: No such slot AddressesWidget::hideThisWidget() in qt/veil/addresseswidget.cpp:283
> 2019-04-13T22:06:18Z GUI: QObject::connect:  (receiver name: 'AddressesWidget')
> 
>

**Comment by veilgets** [comment]
Bounty: 166.67

**Comment by veilgets** [comment]
Developer: rikublock

**Comment by rikublock** [comment]
ready for QA

**Comment by veilgets** [comment]
re-opened

**Comment by CaveSpectre11** [comment]
Ready for QA/Code Review - PR #652

**Comment by veilgets** [comment]
Developer: CaveSpectre11

**Comment by codeofalltrades** [comment]
closed via #652
