### ISSUE TITLE
Restore wallet ignoring real wallet password. Can't restore wallet.

### ISSUE THREAD

**Issue by VeilDango** [Veil-Project/veil#51]
https://i.imgur.com/EDDfabZ.png

26a. I entered a password and despite putting it in correctly, it is asking me for old password for changing passphrase.

Reproducibility:

I can reliably reproduce the issue. Refer to screenshot.

Version used:

https://github.com/Veil-Project/veil/releases/download/testnet-1/veil-0.0.9-win64-setup-unsigned.exe

Hardware and OS:

6700k Intel CPU
Pro 970 SSD
32GB RAM
Windows 10 Pro

Debug.log:

https://cdn.discordapp.com/attachments/507024857847037962/527898028942688256/debug.log

**Comment by 4x13** [comment]
This is also verified on LInux

**Comment by coinmon300** [comment]
MacOS too.

**Comment by presstab** [comment]
It seems that this is an issue with the GUI not being fully connected. Will check back once it is connected to see if it is still an issue.

**Comment by MisterKangaroo** [comment]
After importing a encrypted backup'd wallet.dat it loads without funds in the wallet.
The "new" wallet isnt encrypted.

Windows 10 x64
Testnet10

**Comment by 4x13** [comment]
moved to new issue
