### ISSUE TITLE
Dropdown menu for "Unit to show amounts in:" has black background with black text.

### ISSUE THREAD

**Issue by VeilDango** [Veil-Project/veil#52]
https://i.imgur.com/zAox7qn.png

29.  The dropdown menu for Unit to show amounts in: is black. I can't see MilliVEIL or MicroVEIL units without hovering over them. Make white background and black text.

Reproducibility:

I can reliably reproduce the issue. Refer to screenshot.

Version used:

https://github.com/Veil-Project/veil/releases/download/testnet-1/veil-0.0.9-win64-setup-unsigned.exe

Hardware and OS:

6700k Intel CPU
Pro 970 SSD
32GB RAM
Windows 10 Pro

Debug.log:

https://cdn.discordapp.com/attachments/507024857847037962/527898028942688256/debug.log

**Comment by MisterKangaroo** [comment]
persists in the actual wallet version (testnet3 on win10 x64)

![](https://cdn.discordapp.com/attachments/523336739134242828/528429221849333780/IMG_20181229_052820.jpg)

**Comment by veildev** [comment]
Done.
