### ISSUE TITLE
GUI Bug: Transaction Details - Transaction Size is "n/a Kb"

### ISSUE THREAD

**Issue by Rock-N-Troll** [Veil-Project/veil#523]
![image](https://user-images.githubusercontent.com/34344520/56257645-ebdefb80-609a-11e9-998d-8f10dd2c1642.png)

In the individual GUI Transaction Details Pop-Up, the size is always **`n/a Kb`**, for **Confirmed** and **Unconfirmed**. 

The GUI Transaction Details Pop-Up should display the actual size of the transaction if possible which I believe at the very least applies to **Confirmed** transactions but possibly not for **Unconfirmed** transactions. Might require some detective work.

**Comment by veilgets** [comment]
Bounty: 138.9

**Comment by veilgets** [comment]
Developer: PeterL73
