### ISSUE TITLE
Enable coin control features not checked/enabled, but available on Send screen.

### ISSUE THREAD

**Issue by VeilDango** [Veil-Project/veil#53]
https://i.imgur.com/pTLzqaH.png

30b. "Enable coin control features" is not checked/enabled here,  but it is available in the Send screen. I think we should remove Enable coin control features option here, and just keep it as a visible button in Send tab.

Reproducibility:

I can reliably reproduce the issue. Refer to screenshot.

Version used:

https://github.com/Veil-Project/veil/releases/download/testnet-1/veil-0.0.9-win64-setup-unsigned.exe

Hardware and OS:

6700k Intel CPU
Pro 970 SSD
32GB RAM
Windows 10 Pro

Debug.log:

https://cdn.discordapp.com/attachments/507024857847037962/527898028942688256/debug.log

**Comment by veildev** [comment]
done on #59 .
