### ISSUE TITLE
QValueComboBox GUI Debug Error When Opening Preferences

### ISSUE THREAD

**Issue by Rock-N-Troll** [Veil-Project/veil#533]
Shows some styling errors in the debug log each and every time Preference window pops up. 

Noticed while testing on build for Windows from PR  https://github.com/Veil-Project/veil/pull/529

![image](https://user-images.githubusercontent.com/34344520/56537830-87ef8380-652f-11e9-8378-ceea9e1a6c52.png)

**Comment by drag0ng** [comment]
`optionsdialog` is using `qproperty-alignment` for combo boxes.

**Comment by veilgets** [comment]
Bounty: 125

**Comment by veilgets** [comment]
Developer: codeofalltrades
