### ISSUE TITLE
Feature Request: Show Coin Confirmations For Stake Transactions GUI Addition

### ISSUE THREAD

**Issue by Rock-N-Troll** [Veil-Project/veil#534]
Similar to Issue #460 

![image](https://user-images.githubusercontent.com/34344520/56539220-33e69e00-6533-11e9-9599-0804919fe20b.png)

For **Staking** transaction only (unless a lead developer thinks it doesn't hurt to put the zerocoin confirmation age for normal transactions as well):

Display **"Staked Zerocoin Confirmations"** section which is the age of the zerocoin (total number of confirmations since the zerocoin was minted) that has just staked (Confirmed or Unconfirmed; it should display for both). 

The reasoning for adding this is to help users see that older coins are (hopefully) just as successful staking with precompute enabled as new ones. 
This is also to prove or disprove any sort of advantage minting might hold after precompute is enabled.
It also might be useful for debugging in the event that older coins are actually not staking as regularly as newer coins (with precompute not being the reason why).

![image](https://user-images.githubusercontent.com/34344520/56539439-ea4a8300-6533-11e9-801f-922ec497d60e.png)

Finally, this data is just a nice thing to have and it is already readily available using the "listmintedzerocoins true" call

![image](https://user-images.githubusercontent.com/34344520/56539275-62647900-6533-11e9-8649-5c13b70852e8.png)

Additionally, should be disabled by default and can be enabled via a checkbox in the "Expert Mode" section of the wallet GUI preferences screen.

**Comment by presstab** [comment]
I don't see any reason this should be added to an expert mode, other than adding more complexity to the task, and more confusion to users.
