### ISSUE TITLE
Chinese Translation Change Request : Bitcoin -> Veil

### ISSUE THREAD

**Issue by Rock-N-Troll** [Veil-Project/veil#535]
The following translation errors were found and documented by bruceyin:

![image](https://user-images.githubusercontent.com/34344520/56539606-69d85200-6534-11e9-80bf-ead7ae11a87e.png)

In Chinese version, Preferences --》 Display tab, the circled 比特币means Bitcoin. We might need to change it to Veil币

![image](https://user-images.githubusercontent.com/34344520/56539634-778dd780-6534-11e9-9144-649a9328d8fb.png)

I also found a translation question.  The circled statement means "Please input a BTC address" would bring the confuse to users.  The more propper one shoud be “请输入一个Veil币地址”

**Comment by Fuzzbawls** [comment]
All translation changes should go through [Transifex](https://www.transifex.com/veil-project/public/). Anyone with a Transifex account can request a new language and/or to be a contributor for a particular language.

Also see #524 for more info.
