### ISSUE TITLE
GUI Display Bug: Text In Tooltip Boxes In Preferences Do Not Scale Well

### ISSUE THREAD

**Issue by Rock-N-Troll** [Veil-Project/veil#536]
![image](https://user-images.githubusercontent.com/34344520/56539870-27634500-6535-11e9-91c4-b312f3a34800.png)

![image](https://user-images.githubusercontent.com/34344520/56539886-33e79d80-6535-11e9-959e-9b37cc86334d.png)

Self Explanatory. The text should scale and display properly. This issue appears in a lot of places in the wallet and has supposedly been tackled in one of the most recent sprints for a different area of the wallet. Maybe a similar fix is possible reusing similar solutions.

**Comment by codeofalltrades** [comment]
@Rock-N-Troll This is same issue as #63 and #54. It is fixed pending this pull request #515

**Comment by presstab** [comment]
Closing as a duplicate.
