### ISSUE TITLE
"Open Configuration File" and "Reset Options" Empty Tool Tip Labels

### ISSUE THREAD

**Issue by Rock-N-Troll** [Veil-Project/veil#537]
![image](https://user-images.githubusercontent.com/34344520/56540202-0818e780-6536-11e9-92f7-5cb3088a698a.png)

![image](https://user-images.githubusercontent.com/34344520/56540082-b6705d00-6535-11e9-8888-c8e35c6e98f5.png)

Currently there is no description or help text for the "Open Configuration File" and "Reset Options" Tool Tips. 

**ToolTip Text Suggestions:**

**"Open Configuration File":** _"Creates a wallet configuration file **"veil.conf"** in the root directory unless a wallet configuration file already exists. Additionally, the configuration file is opened in the system's default text editor."_

**"Reset Options":** _"Erases and sets all options in the wallet configuration file back to its default state"_

Note: There might be text but if there is, it is currently not displayed properly.

**Comment by DrBrainstorm** [comment]
Also,  text in Tool Tip Labels doesn't scale well.

![veil](https://user-images.githubusercontent.com/46718457/56591557-a453f480-65f1-11e9-987d-367cc3ee5b57.png)

![veil2](https://user-images.githubusercontent.com/46718457/56591575-a918a880-65f1-11e9-8999-3e4c1c4e787c.png)

**Comment by MisterKangaroo** [comment]
> Note: There might be text but if there is, it is currently not displayed properly.

The tooltip text is there, but not displayed properly. Didnt find the reason for it, since it should be shown as black text accordingly to Qt Designer.
![openconfig](https://user-images.githubusercontent.com/43561981/56617842-2dceeb00-6621-11e9-8682-3fa14d20a666.png)
![reset options](https://user-images.githubusercontent.com/43561981/56617844-30314500-6621-11e9-87b4-3fbc0351bc91.png)

**Comment by drag0ng** [comment]
This is fixed with https://github.com/Veil-Project/veil/pull/484

**Comment by crypt0-fusi0n** [comment]
My initial test on Linux shows that this is fixed with #484 ... mac and windows testing pending...

**Comment by veilgets** [comment]
Bounty: 125

**Comment by veilgets** [comment]
Developer: codeofalltrades

**Comment by codeofalltrades** [comment]
This issue is already fixed on the master branch. I fixed the issue with pull #515.
