### ISSUE TITLE
GUI Enhancement: Add "Filter By" And Cascade The Selection With "Sort By" In Transactions List

### ISSUE THREAD

**Issue by Rock-N-Troll** [Veil-Project/veil#540]
![image](https://user-images.githubusercontent.com/34344520/56622979-3a8f1700-6600-11e9-9963-73316b3c469f.png)

A cascading filter for "Filter By" in connection with "Sort By" should be added for further filtering of the Transactions List View.

`Filter By` should filter by transaction types (listed below) which can be found in the `TransactionRecord` class:

![image](https://user-images.githubusercontent.com/34344520/56683562-c86c1000-669b-11e9-9b3f-08dc3cea13d3.png)

**--Send _(Wherever there is RED text in the transaction list)_
--Receive _(Wherever there is GREEN text in the transaction list)_
--Mint
--Stake
--Basecoin
--CT
--RingCT
--Zerocoin _(Always with --Mint and --Stake)_**
```
class TransactionRecord
{
public:
    enum Type
    {
        Other,						--???
        Generated,					--???
        SendToAddress,					--Receive
        SendToOther,					--Send
        RecvWithAddress,				--Receive
        RecvFromOther,					--Receive
        SendToSelf,					--Receive                                              
        CTSendToSelf,					--CT --Receive                      
        CTSendToAddress,				--CT --Send
        CTRecvWithAddress,				--CT --Receive
        CTGenerated,					--CT --Receive
        RingCTSendToSelf,				--RingCT --Receive
        RingCTSendToAddress,				--RingCT --Send
        RingCTRecvWithAddress,				--RingCT --Receive
        RingCTGenerated,				--RingCT --Receive
        ZeroCoinMint,					--ZeroCoin --Mint --Receive
        ZeroCoinSpend,					--ZeroCoin --Send
        ZeroCoinSpendRemint,				--ZeroCoin --Mint --Receive
        ZeroCoinSpendSelf,				--ZeroCoin --Send
        ZeroCoinRecv,					--ZeroCoin --Receive
        ZeroCoinStake,					--ZeroCoin --Stake --Receive
        ConvertBasecoinToCT,				--CT --Basecoin --Receive
        ConvertBasecoinToRingCT,			--CT --RingCT --Receive
        ConvertCtToRingCT,				--CT --RingCT --Receive
        ConvertCtToBasecoin,				--CT --Basecoin --Receive
        ConvertRingCtToCt,				--CT --RingCT --Receive
        ConvertRingCtToBasecoin,			--RingCT --Basecoin
        ConvertZerocoinToCt,				--CT --ZeroCoin --Receive
        ZeroCoinMintFromCt,				--CT --Zerocoin --Mint --Receive
        ZeroCoinMintFromRingCt				--RingCT --Zerocoin --Mint --Receive
    };
}
```

I may have mis-attributed some of these filters because I based them on my interpretation of their English naming instead of determining their actual use.

I am also unsure what **Other** and **Generated** apply too so left them empty for now. Part of this task is to also ensure the correct filter attributes are setup correctly.

**Comment by veilgets** [comment]
Bounty: 611

**Comment by veilgets** [comment]
Developer: MatWaller

**Comment by MatWaller** [comment]
Ready For QA.
