### ISSUE TITLE
Check boxes are not available for the options on Linux its available on Windows 64.

### ISSUE THREAD

**Issue by ncrypter90** [Veil-Project/veil#546]
The check box against each selectable options windows is missing for Linux but its seen in Windows 64. Find the screen shots for the reference,

Windows 64:
![image](https://user-images.githubusercontent.com/49970996/56856121-d2df1180-6908-11e9-9599-21798e48e617.png)

linux:
![image](https://user-images.githubusercontent.com/49970996/56856129-dffc0080-6908-11e9-9be8-2af6df97326c.png)

**Comment by MatWaller** [comment]
Could you let me know what desktop environment you are using?

I'm able to replicate this when running `unity` but when i use `budgie` it seems to display fine;

![Budgie](https://user-images.githubusercontent.com/8047888/56939485-82320900-6b00-11e9-8f71-68faea7c1f0b.png)

Could you also check you have `libcanberra-gtk-module` installed?

**Comment by codeofalltrades** [comment]
@MatWaller I'm pretty sure it is only the checkboxes on the Window tab.

**Comment by ncrypter90** [comment]
HI ,

@MatWaller Check boxes are not available on Ubuntu.

**Comment by veilgets** [comment]
Bounty: 166.7

**Comment by veilgets** [comment]
@codeofalltrades Your PR fixes this issue correct?

**Comment by codeofalltrades** [comment]
Yes, I thought pull #515 would fix it. There was some miscommunication between myself and QA regarding issue number or pull request number.  I think it is fixed. I will pull Master, test on a Linux machine and report back.
