### ISSUE TITLE
GUI Enhancements: Make modal, popup & window styling consistant & uniform.

### ISSUE THREAD

**Issue by MatWaller** [Veil-Project/veil#548]
## The Problem.
At present modals, popups & windows sizing, spacing & overall style is inconsistent & non uniform with many instances of repetition within the styling itself [Inline styling] -- This makes for a confusing user experience & bit of a developer headache when re-skinning/restructuring the application when the new UI/UX is good to go.

## Current modals, popups & windows
![learn](https://user-images.githubusercontent.com/8047888/56886560-2d8e7f80-6a67-11e9-9ceb-cd70edd6cad1.png)
![options](https://user-images.githubusercontent.com/8047888/56886562-2e271600-6a67-11e9-9b89-89cc78f01f23.png)
![pass](https://user-images.githubusercontent.com/8047888/56886564-2e271600-6a67-11e9-8945-2ebb12620c11.png)
![sync](https://user-images.githubusercontent.com/8047888/56886565-2e271600-6a67-11e9-9bd3-c4797626d0ff.png)

## The Solution.

1. Move in-line styling into a set of common `qss` as to allow for easier/cleaner development and management of the style & layout moving forward (While also reducing the amount of code needed for styling)
2. Update styling & layouts as so sizing, spacing etc.. is uniform and consistent throughout the wallet.

**Comment by veilgets** [comment]
Bounty: 333.33

**Comment by veilgets** [comment]
Developer: matwaller

**Comment by MatWaller** [comment]
Ready for QA.

**Comment by MatWaller** [comment]
Ready for QA. (Created as new PR)
