### ISSUE TITLE
veild v1.0.3 does not allow listzerocoinamounts or listmintedzerocoins

### ISSUE THREAD

**Issue by CryptoMaximalist** [Veil-Project/veil#550]
The latest version of the veil wallet does not allow the RPC commands listzerocoinamounts or listmintedzerocoins.  It return an error asking for the wallet to be unlocked first, even when it already is.  This even happens when calling with the veil-cli binary from v1.0.2 against the daemon running the v1.0.3 veild daemon.  However, it does not seem to be an issue in the veil-qt GUI wallet

Happens every time, tested on ubuntu server and desktop, both 18.04 x64

`jon@veil:~$ ~/Downloads/veil-1.0.3/bin/veil-cli listzerocoinamounts
error code: -13
error message:
Error: Please enter the wallet passphrase with walletpassphrase first.`

**Comment by presstab** [comment]
Try not mixing and matching the binaries and see if that makes any difference. Is the wallet fully unlocked or unlocked for staking only?

**Comment by CryptoMaximalist** [comment]
Ha!  I didn't know Staking Only was added to this release, good call that was it
