### ISSUE TITLE
Indication bar searchdeterministiczerocoin

### ISSUE THREAD

**Issue by Veil-Grumpy** [Veil-Project/veil#552]
At the moment when doing searchdeterministiczerocoin in debug console it doesn't show any progress, users just need to wait until it gives the done output message.

Some users might be confused if it's stuck or not working at all.

Making a indication bar for the command searchdeterministiczerocoin would be a great thing to have.

Example from rescanblockchain command:
![bar](https://user-images.githubusercontent.com/46780798/56919847-f13c3d00-6ac1-11e9-88e6-c59a9c291832.JPG)

**Comment by veilgets** [comment]
Bounty: 250

**Comment by veilgets** [comment]
Developer: PeterL73
