### ISSUE TITLE
GUI requires two clicks on lock button in the status bar.

### ISSUE THREAD

**Issue by presstab** [Veil-Project/veil#553]
The GUI requires two clicks of the lock icon in the status bar before it opens the unlock wallet dialog.

**Comment by presstab** [comment]
Assigned to @MatWaller

**Comment by MatWaller** [comment]
Seems to only occur with the first interaction with the button, each time after that only 1 click is required to open the window correctly -- Would imagine the first click is focusing the `veilstatusbar`.

**Comment by veilgets** [comment]
Bounty: 194.4

**Comment by MatWaller** [comment]
Ready for QA
