### ISSUE TITLE
Wallet Crashes with Double Free Segfault and corrupts chain

### ISSUE THREAD

**Issue by 4x13** [Veil-Project/veil#554]
![double free segfault - 1](https://user-images.githubusercontent.com/39984029/57011892-a3eec700-6bb8-11e9-85b5-89e05c92ac46.png)

![double free segfault - 2](https://user-images.githubusercontent.com/39984029/57011899-aa7d3e80-6bb8-11e9-9d36-dcb437923b37.png)

Happens at random intervals, Corrupts the chain every time it occurs.

**Comment by presstab** [comment]
Believe this is a duplicate of #547
