### ISSUE TITLE
When wallet contains zerocoin, trying to send an amount less than 10 VEIL via the coin send dialog, the transaction fails

### ISSUE THREAD

**Issue by blondfrogs** [Veil-Project/veil#555]
- The wallet will try to spend your balance in the following order
1. zerocoin
2. ringct
3. ct

which make me think it is a zerocoin issue

**Comment by ncrypter90** [comment]
![Veil_build_517_Rebuild_Screengrab](https://user-images.githubusercontent.com/49970996/57223367-57aae900-6ff5-11e9-8e83-3960151c7e9b.gif)
