### ISSUE TITLE
wallet missed a transaction output

### ISSUE THREAD

**Issue by seanPhill** [Veil-Project/veil#558]
A user in Discord reported seeing on orphans of a 1000 denom stake (surely not all orphans) 1040 showing as immature, instead of 1050.

I remembered seeing something like this once, but not on an orphan. 

My wallet did not see one of the output tens in a stake winning. I checked the explorer and all five tens were there. I did a rescanzerocoinwallet and after it was mature I checked and saw that all five tens were found.

It might have been on a testnet wallet that was busy processing a lot of transactions. I have only seen that once.

When this happened to me it was before 1.0.3.0, but probably on a prerelease wallet. I didn't raise the issue then, because it was easily fixed, however now that it has been mentioned in Discord, as if it may be more frequent, here is the Github issue now.

**Comment by seanPhill** [comment]
To put this into context. I have had thousands of stakes across testnet and mainnet, and this is the only time I have seen this happen. The Discord user also mentioned that it was the only one he has seen, but presumed that he just happened to see it while it was "immature" and as it was an orphan, would never have seen it if not looking at the wallet at the time, which also matches my case.

**Comment by veilgets** [comment]
Bounty: 416.67

**Comment by seanPhill** [comment]
An update on this. While it had seemed rare a couple of months ago, this past week I have had to (more often than not)  `rescanzerocoinwallet` to find one or two of the ten denomination zerocoins, even once it was a 10000 denom and a 10 denom. 

While rescanzerocoinwallet has worked on its own to find the coins, I have in the past found coins with `rescanringctwallet` also.

MAYBE I need to generate a new wallet seed again (due to the number of transactions), but this particular wallet seed, is less than four weeks old.

**Comment by seanPhill** [comment]
One other SIDE-EFFECT of this is that if one or two of my stake winnings' ten denom zerocoins is missing and I have to rescanzerocoinwallet to find it or them, I have to manually spend the found zerocoins before autospend will resume!

**Comment by codeofalltrades** [comment]
@seanPhill I haven't seen any reports of this issue recently. Have you?

**Comment by seanPhill** [comment]
Not recently.

**Comment by codeofalltrades** [comment]
Closing. Issue has not been witnessed for two months.
