### ISSUE TITLE
Spending zerocoins en masse

### ISSUE THREAD

**Issue by seanPhill** [Veil-Project/veil#559]
This Feature Request is for people who may have found themselves with more than ten thousand ten denom zerocoins that they cannot spend, without eating into processing power so much that spending x thousand zerocoins prevents staking for more than it is worth in moving the zerocoins to larger denominations.

If we can figure out a better way of spending ten thousand tens, ie. 100K Veil of ten denoms, it would be helpful for some people.

I have two testnet wallets that could test any solution being trialled.

One wallet has ONLY tens and a value of 157K (testnet) Veil. It has become so slow that I have had to turn OFF staking, as it forks from the chain while it calculates stakes or when trying to spend. _That is my **small** wallet!_

My other wallet is also accumulating thousands of tens, because having several hundred thousand (testnet) Veil in 10K, 1K and some 100s, it stops generating blocks as it tries to spend, and other nodes fork from it. So I've given up trying to spend the tens for now.
This wallet was created while trying to spend out the zeorocoins from the other wallet, which had bloated to hundreds of MB, but having moved the large denoms to this wallet, I have _never been able to complete the process_ of moving all the zerocoins from wallet to wallet.

I am currently only using the released 1.0.3 wallet, but this problem has been building for some time.

I also have precomputing turned off, because these testnet wallets appear not to be able to cope with precomputing on.

**Comment by seanPhill** [comment]
Even if we were able to get a solution to efficiently spending 10050 Veil from zerocoin and then minting to a single 10K, that would be hugely helpful, because it would still be much, much more easy than now, to clear out 100K Veil of ten denoms.

**Comment by 4x13** [comment]
unlikely to happen as we wont be continuing with zerocoin much longer. But that being said, the best way is to make a script to do the zerocoin spends to basecoin, and workout the timing for that particular system to spend for example (2) 10 denoms every 6 minutes so the wallet is not locked up 100% of the time.

**Comment by presstab** [comment]
This could be done more quickly if we limit the privacy aspect of what is being spent. Seeing as right now there is no privacy, that would not be a concern.

**Comment by seanPhill** [comment]
I LOVE PR#569 !!!! Way to go! :)
