### ISSUE TITLE
Adjust TravisCI timeout thresholds

### ISSUE THREAD

**Issue by Fuzzbawls** [Veil-Project/veil#567]
TravisCI has a global timeout of 50 minutes, which cannot be changed. The current job scripts have timing checkpoints after various "stages" that try to estimate if the remaining stages will have sufficient time to complete before reaching the global timeout.

Need to review if those checkpoint thresholds can be further adjusted so as to not have to babysit TravisCI builds as much.

**Comment by veilgets** [comment]
Bounty: 1493.06

**Comment by CaveSpectre11** [comment]
Babysitting solved by removing travis and replacing with Github Actions.  Much less babysitting needed.
