### ISSUE TITLE
Under Zerocoin Minting, I can only select one Zerocoin denomination at a time. Need to be able to select 1, 2, 3, or all of them.

### ISSUE THREAD

**Issue by VeilDango** [Veil-Project/veil#57]
https://i.imgur.com/aTJ35xw.png

31c. In the Select Zerocoin denominations.... header, I can only select one item at a time. I should be allowed to select 1, 2, 3, or all of them. I should not be allowed to select NONE of them.

Reproducibility:

I can reliably reproduce the issue. Refer to screenshot.

Version used:

https://github.com/Veil-Project/veil/releases/download/testnet-1/veil-0.0.9-win64-setup-unsigned.exe

Hardware and OS:

6700k Intel CPU
Pro 970 SSD
32GB RAM
Windows 10 Pro

Debug.log:

https://cdn.discordapp.com/attachments/507024857847037962/527898028942688256/debug.log

**Comment by veildev** [comment]
@presstab the backend don't have it, only supporting one preferred denom --> nPreferredDenom on util.cpp, if there is other way then point me to where you left it.

**Comment by presstab** [comment]
@veildev As far as I see, this is a feature request, not a problem that needs to be addressed.

**Comment by veildev** [comment]
Ok, it was a request for @4x13

**Comment by 4x13** [comment]
We can add this after launch
