### ISSUE TITLE
Feature request: Limit denoms of Automint all at once

### ISSUE THREAD

**Issue by seanPhill** [Veil-Project/veil#572]
Because automint full balance at once do exactly that, and because there is a small fee to mint, if you have an exact thousand amount arrive then instantly it mints EIGHTEEN coins that you would prefer not to mint!

For example, withdrawing 2000 from exchange, it arrives at 1999.9. Already it is slightly short of the needed amount to mint two thousands and it mints TWENTY coins, including nine hundreds and nine tens. Other example, you receive exactly 2000 Veil, and it does exactly the same thing.

Please can this function simply be able to be used, but limited by a selection of the denomination to mint? For example, receive 5000 Veil and instantly mint four thousands, leaving the 999.95 where it is, or returned as change to its appropriate place. Likewise, if receiving 7500 Veil, it should still automint 7000, and leave the remainder to its ordinary course.

**Comment by seanPhill** [comment]
Unless the chosen denom is 100, or even 10, but I'm sure you get the idea.

**Comment by seanPhill** [comment]
Maybe have an additional function to ensure that people do not have ten selected when all at once is selected, lest someone instantly mint 749 tens from a 7500 Veil receipt!!

There possibly could be another button to enable minting as it currently works, if desired. For example, if they select 100 denom and minimise coins, then, when they receive 7500 Veil it should mint seven thousands, four hundreds and that's all. If they select Do not minimise coins then it could mint 74 hundreds instead. Maybe simply rule out minting tens entirely, when ALL AT ONCE is selected.

**Comment by 4x13** [comment]
That is how it works now if you have 1k selected. by default it is set to 10 denom, a user would have to select manually the mint all option otherwise.

**Comment by seanPhill** [comment]
Okay, so I've just seen how the automint 1000 works now. It seems different to how it used to be, where it would mint one at a time.
I had it **set to 1000 and it minted all the thousands at once** (for the first time, for me). That is preferable to the All-At-Once option where it also mints an unreasonable number of tens and hundreds, which you may or may not want.

So this will now just be a matter of explaining to people, or people learning this through experience. We had so many complaints when basecoin change first began going to CT. I didn't realise it had been changed, but maybe that's why the complaints have disappeared.
