### ISSUE TITLE
recoveraddresses indication bar not showing correctly

### ISSUE THREAD

**Issue by Veil-Grumpy** [Veil-Project/veil#577]
The indication bar of the command recoveraddresses is only showing the % amount but not the green bar.

Check screenshot:
![rover](https://user-images.githubusercontent.com/46780798/57361148-142eb700-717c-11e9-912e-c1ae1419b140.JPG)

Windows 10
Self compiled version from this month

**Comment by veilgets** [comment]
Bounty: 166.67
