### ISSUE TITLE
Feature request: Warning to select preferred automint denomination after wallet restart

### ISSUE THREAD

**Issue by seanPhill** [Veil-Project/veil#578]
This is a feature request to help avoid people minting _too many_ ten denomination zerocoins.

Granted, minting tens is fine, when people are starting out with a small amount of Veil, but some people are depositing (literally) tens of thousands of Veil into their wallet and getting them autominted into tens! Also, some people have experimented with reminting 10000 denoms into 10 denoms now that precomputing has been released, being unaware of any performance implications that this may have.

This used not to be a problem for two reasons (that no longer exist). 
1. People did not have large amounts of Veil
2. Autominting was slow.

Now that autominting is minting large numbers of zerocoins in a much shorter amount of time, the default automint setting is more critical.

It has been suggested that we simply should have some kind of pop up after a restart for users to confirm that the current automint denom is what they want.

I think that something one step further should exist, such as a check when automatic or manual minting is about to mint hundreds or thousands of tens, it should warn that this is a large number of zerocoins, and the user may be advised to consider choosing a larger denomination. Or, as the user probably is going to do a large number of manual iterations of `mintzerocoin 90` then maybe a check should be done, at least once in a day, that gives a warning (that this action may negatively affect wallet performance) if there are already 1000 tens in the database.

**Comment by 4x13** [comment]
I agree with the popup when a user starts the wallet each time, butnot sure if a popup everytime automit triggers is a good idea, Seams a bit intrusive.

**Comment by seanPhill** [comment]
Yeah. I don't mean repeating it like that. Once they have made their decision, it's on them!

**Comment by veilgets** [comment]
Bounty: 645.83

**Comment by veilgets** [comment]
Developer: JSKitty
