### ISSUE TITLE
rpc call "spendzerocoin" fails if denomination is not multiples of 10

### ISSUE THREAD

**Issue by ncrypter90** [Veil-Project/veil#584]
Issue while spending fractions of a ten denomination zero coin to stealth or base address.

Tried changing fee by settxfee 0.0001 or settxfee 0.00001, but did not work.

However, with multiples of 10 it works beautifully.
 
example:
spendzerocoin 12 false true 42 <baseaddress> --> fails
spendzerocoin 5 false true 42 <baseaddress> --> fails
spendzerocoin 10 false true 42 <baseaddress> --> successful
spendzerocoin 20 false true 42 <baseaddress> --> successful

Error message from console:
Transaction Created (code -4)

**Comment by blondfrogs** [comment]
Fixed with #556
