### ISSUE TITLE
Zercoin minting settings/options reset to defaults when wallet is closed and opened.

### ISSUE THREAD

**Issue by rlloyd2001** [Veil-Project/veil#585]
Zercoin minting settings/options reset to defaults when wallet is closed and opened.

I expect the last configuration that was set to be the same. such as if I select 1000 zerocoin denomination, close the UI and re-open, I would like it to still be set to 1000.

Very easy, change a zerocoin setting/option, close the wallet and re-open

Veil Core version v1.0.3.0-4249d573d (64-bit)

**Comment by MatWaller** [comment]
@rlloyd2001 Unable to replicate using;

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

Steps tried to replicate
- Setting Zerocoin denomination to 1000
- Closing `veil-qt`
- Reopening `veil-qt`
- Check Zerocoin denomination [Still set to 1000]

Could you let me know your operating system and ill try replicate on a VM?

Thanks.

**Comment by rlloyd2001** [comment]
Windows 10

**Comment by seanPhill** [comment]
So far as I'm aware this only affects Windows. There was an early issue that was fixed for MacOS and Linux.

**Comment by veilgets** [comment]
Bounty: 270.83

**Comment by veilgets** [comment]
Developer: codeofalltrades

**Comment by CaveSpectre11** [comment]
Claim released by codeofalltrades; open and up for grabs.

**Comment by CaveSpectre11** [comment]
This is a slight annoyance and not worth the effort as we're phasing out zerocoin
