### ISSUE TITLE
Wallet 1.0.3.0 crash on different Windows computers

### ISSUE THREAD

**Issue by pcarballeda** [Veil-Project/veil#591]
I have a problem with last update of Veil wallet. I start the wallet after update but it closed unexpectedly every time. I tried fresh installation in different computers and wallet starts but it crash without warning or error message, just sync for a while and then it stop working.

I am running Veil wallet 1.0.3.0 unsigned on Windows 10 64 bit

My expectations were that the wallet worked as always.

I can't provide screenshots or images because wallet stop working unexpectedly.

The steps to reproduce the error are: start the wallet and wait, sometimes 1 hour, sometimes 4 hours...

I tried to compile the wallet myself but I can't due to the infinite dependencies and errors, just I am not capable.

**Comment by mreash16** [comment]
I'm having the same issues, I've tried everything but the wallet wont completely sync. After about 60% of the wallet sync's. The wallet just crashes, no error or anything the wallet just closes. I've been trying to get the wallet to work for a week now

**Comment by 4x13** [comment]
Have either of you tried to build from the master bramch? The fix for this issue has already been pushed.

**Comment by mreash16** [comment]
How do you build from the master branch?

**Comment by seanPhill** [comment]
You'll need to check other resources for Windows building instructions, and how to download from Github, but some of the information you'll need can be found inside the docs folder in the Veil wallet source.

**Comment by N8Thrasher** [comment]
I have same issue with new wallet on Windows 7 64bit while syncing

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	veil-qt.exe
  Application Version:	1.0.3.0
  Application Timestamp:	00000000
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.1.7601.23418
  Fault Module Timestamp:	5708a857
  Exception Code:	c0000005
  Exception Offset:	000000000004eef1
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	67fe
  Additional Information 2:	67fe561776104509dc74e041bb3606ea
  Additional Information 3:	4dbf
  Additional Information 4:	4dbfcab842d9ac404eca8854b16f3044

[debug.log](https://github.com/Veil-Project/veil/files/3203294/debug.log)

**Comment by presstab** [comment]
This particular issue is fixed. A new release will be coming out soon that has prebuilt binaries for everyone to use that can't compile the code themselves.
