### ISSUE TITLE
GUI Bug: Status Text Potential Misalignment

### ISSUE THREAD

**Issue by Rock-N-Troll** [Veil-Project/veil#602]
![image](https://user-images.githubusercontent.com/34344520/58172104-9ed7e180-7c65-11e9-83ca-1225543e234b.png)

As shown in the image, the "Processing blocks on disk..." text is no longer aligned with the middle of the shown area at the bottom of the wallet. It is now very close to the toggle switches and looks a bit odd being so close to them. This issue might have already been fixed as I am using a wallet compiled from master closer to the beginning of May.

**Comment by veilgets** [comment]
Bounty: 50.78

**Comment by veilgets** [comment]
Developer: codeofalltrades
