### ISSUE TITLE
Lost Veil after ZeroCoin minting!

### ISSUE THREAD

**Issue by mreash16** [Veil-Project/veil#606]
I had 177 base coin in my Veil wallet and I tried to mint 170 of the base coin to zero coin. After I entered 170 into the mint zero coin veil tab, checked the use base coin box and clicked mint. I lost all 177 veil in my wallet. There is 0 coins a crossed the board now and what I mean by that is there is 0 coins in unconfirmed, 0 in immature, 0 in all three coin tabs etc...

**Comment by 4x13** [comment]
Sounds like you have a stuck transaction, come to discord and get with one of the support guys wjo will get you squared away.

**Comment by Veil-Grumpy** [comment]
My name is Grumpy from Veil Support, contact me in Discord I will help you get your coins back!

If you don't have Discord and you want to try yourself, please follow this link on how to fix:
https://veil.freshdesk.com/support/solutions/articles/43000480109-i-ve-minted-spent-some-zerocoins-a-few-hours-ago-and-they-are-still-unconfirmed-

**Comment by mreash16** [comment]
Thank you for your Help and the link, I was able to get the coins back into my wallet! You guys are the best!
