### ISSUE TITLE
[rpc] rescanzerocoinwallet help message returns incorrect method

### ISSUE THREAD

**Issue by MatWaller** [Veil-Project/veil#610]
Help message returned for `help rescanzerocoinwallet` is incorrectly returned as that of `resetmintzerocoin`

![rescan](https://user-images.githubusercontent.com/8047888/58768433-f8f47300-8592-11e9-9d1a-11ca3c7aee6e.png)

**Comment by Veil-Grumpy** [comment]
Good catch

**Comment by veilgets** [comment]
Bounty: 67.71

**Comment by veilgets** [comment]
Developer: JSKitty
