### ISSUE TITLE
Add how to unlock wallet to wallet FAQ

### ISSUE THREAD

**Issue by Veil-Grumpy** [Veil-Project/veil#612]
Add a new FAQ in wallet on how to unlock wallet

For new users might be hard to know how to correctly unlock wallet, like by clicking the lock in the right under corner of the wallet.

![where](https://user-images.githubusercontent.com/46780798/58974532-e82a4400-87c2-11e9-820d-8358ca93462a.png)

**Comment by ianGre** [comment]
I think there is going to be only one unlock switch in the future. Not sure when.

**Comment by veilgets** [comment]
Bounty: 135.42

**Comment by veilgets** [comment]
Developer: MattWaller

**Comment by MatWaller** [comment]
Ready for QA.
