### ISSUE TITLE
Spending from RingCT fails because some funds are allegedly already spent

### ISSUE THREAD

**Issue by CryptoMaximalist** [Veil-Project/veil#626]
When trying to spend from RingCT, the wallet seems to believe some of the TXOs are already spent (but it does not correct their status in the wallet).  For example, if I have 1050 Veil and try to mint a 1k zerocoin, it will fail with this error as if one or more TXOs in that 1050 are spent and I actually have less than 1,000 Veil.  Supporting this theory, sometimes you can add more RingCT and then it will work, but of course this is not really a solution.

Expected: If the wallet says I have 1050, I can mint a 1000 zerocoin

Reproduction:  I can reproduce reliably when I have the issue like right now, but can't cause the issue in the first place

Version: 1.0.3

CLI Output:
`~/Downloads/veil-1.0.3/bin/veil-cli mintzerocoin 1000
error code: -4
error message:
Error: The transaction was rejected! This might happen if some of the coins in your wallet were already spent, such as if you used a copy of wallet.dat and coins were spent in the copy but not marked as spent here.`

Debug log example:

`2019-06-21T16:32:54Z CreateZerocoinMintTransaction: new mint  DeterministicMint:
   version=2
   count=6085
   hashseed=8ac8c7c9dec9d023d92af4c24c9f5f3a25d882a0
   hashSerial=2a881d6992fc73dd561a90cef1b121eca7d8ac0ec9e545f116f21c1562163537
   hashStake=994e37bdf8e5dc9369b936851de8bf4ffc6246589d06e77f0bc995c6075b5dbc
   hashPubcoin=7bb7fbc2b2de95e3c645538952e5ee2605eb3f0712e7fc8fa93c70c42b5ea82d
   txid=0000000000000000000000000000000000000000000000000000000000000000
   height=0
   denom=1000
   isUsed=0

2019-06-21T16:32:54Z Fee Calculation: Fee:1000000 Bytes:13253 Needed:1000000 Tgt:6 (requested 6) Reason:"Minimum Required Fee" Decay 0.96200: Estimation: (0 - 1e+99) 68.55% 37.2/(50.9 1 mem 2.4 out) Fail: (-1 - -1) -nan% 0.0/(0.0 0 mem 0.0 out)
2019-06-21T16:32:54Z CommitTransaction:
CTransaction(hash=37b491a286, ver=2, vin.size=1, nLockTime=0)
    CTxIn(COutPoint(0000000000, 4294967200), scriptSig=)
    CScriptWitness(cc8a02ae8e02e98d02e967cb8702f22ef46bfc6ffe5e80820295ff01ae8902de9801a38b02cefc01a8cc01f05be28102a78102918e02d78b028b8a01a28a0289a801eb8802ec8902a35abbf701ca...947ee059e467a1fd01a4ac01c99f01b8af0191e901b26bc18e02d48502b27fd8db01808d02c264, b9b1918d574521036e9ba652788f198043774bb6a90d78e79d83f6d3c7c2f8ddc4000427b9a1fbf0f1f87cf20d20c51c3a3a939516f78f57d2dc6f13fe8e979de973ea3c97fcbff89b149845140e40ce91456bcb2fd...300ed50197411d8362b27b9a782af5d174b17a24b5bfd0bf6f4c017bca3bbf3419159194e065cc749cbbdeadc21aa4f721e870f1966e0a5bffe16e6a054aa1259702de8ccc2bab41d6ff724b7125390bee45acbd10)
    CTxOutData(data=06c0843d)
    CTxOutStandard(nValue=1000.00000000, scriptPubKey=c10280004c80e7cf2dbea2e460287a)
    CTxOutRingCT(data=02572bc193b7db00cacaae90e2fc2e, pk=03d29d33862bbfc19116f96bca09cc)
2019-06-21T16:32:54Z [default wallet] AddToWallet 37b491a2867be20cae91c5f983236490bc10d1a951703cb3d12bd085425ecb7f  new
2019-06-21T16:32:54Z ERROR: CommitTransaction(): Transaction cannot be broadcast immediately, bad-witness-nonstandard (code 64)`

**Comment by Veil-Grumpy** [comment]
Had the same issue once.
For me a rescanblockchain and rescanringctwallet solved this issue but doesn't seems to work for everybody. Second fix is restoring from seed because that seems to fix the stuck/spended RingCT.

**Comment by CryptoMaximalist** [comment]
Oh yeah I meant to include that.  The rescan commands have not been working for me, but restore from seed has been 100% reliable so far.  And to add to the theory of incorrect balance and spent TXOs, the restoration from seed usually comes up with a smaller balance for RingCT

**Comment by seanPhill** [comment]
If you know which block, even approximately, you can restrict the number of blocks it rescans: ```rescanblockchain 260000 270000```

**Comment by CryptoMaximalist** [comment]
This issue has now occurred on a fresh wallet restore from seed.  Weirdly, it happened when trying to mint a 10k, but I was able to mint 10 1k's just fine

**Comment by DrBrainstorm** [comment]
Had a similar issue, where part of my RingCT balance was marked as already spent, although ```getbalances``` was reporting all of it as ringct_spendable. Not sure if I am on the correct path, but since I was constantly going zerocoin->CT->RingCT->zerocoin, it might have something to do with addresses reuse and change being marked as spent although owned as UTXO.
Upon seed restore part of my RingCT balance went missing and I was unable to recover it with provided in-wallet functionality.

**Comment by vereten** [comment]
I have similar issue. All time im minting zerocoins from ring, all time some of ring ct disappear. And no way to restore em from seed or backup.

**Comment by CryptoMaximalist** [comment]
As discussed in github private channel here https://discordapp.com/channels/481997816982405130/510598374094012427/676259809833648177

The issue seems to be related to all ringCT spend types (to basecoin, stealth, ringCT, zerocoin mints).  As far as I can tell, the issue seems to be reproduced any time there is more than ~10 inputs. 

If spending to RingCT or basecoin the error will be:
`Transaction commit failed: bad-witness-nonstandard (code 64)`

If spending to stealth the error will be:
'Transaction commit failed: bad-commitment-sum (code 16)'

If minting to zc the error will be:
`Error: The transaction was rejected! This might happen if some of the coins in your wallet were already spent, such as if you used a copy of wallet.dat and coins were spent in the copy but not marked as spent here.`

The workaround is to spend your ringCT to yourself, in the highest amounts you can.  (Churning)  This will consolidate your UTXOs and allow you to spend your coins with less than 11 inputs

**Comment by CaveSpectre11** [comment]
The bad-witness-nonstandard causing limit has been raised to 50 inputs (#756).  Leaving this open for now since I want to review a few other things that exist in this Issue; but likely will be closed when 756 is accepted.

**Comment by seanPhill** [comment]
Checked that the matching PRs were (tested and) merged some time ago.

(Cleaning up)
