### ISSUE TITLE
Stuck on sync

### ISSUE THREAD

**Issue by MisterKangaroo** [Veil-Project/veil#64]
Latest wallet binaries on win 10 x64.

After some good sync progress the wallet now stucks on sync (same block) since several hours.
I do have active peers and connections but no progress.
Checked the firewall, but its not the reason.
I shut down the wallet, delete the debug.log and start the wallet with the -debug flag.
Now it runs since about 2h.
Below you will find a link to the debug.log:
https://cloud.cryptographic.pro/index.php/s/rx8ojNCxM3HeFx2

**Comment by 4x13** [comment]
issue is resolved in upcoming test release
