### ISSUE TITLE
std::bad_alloc error

### ISSUE THREAD

**Issue by subarist004** [Veil-Project/veil#641]
First time (on screens attached) std::bad_alloc error appeared on 1.0.3 wallet when user tried to spend zerocoins. We did all "standart" commands which helps in this case - no result. Wallet restart also didn't help. We solved it by upgrading to 1.0.3.1 version.

Second time std::bad_alloc error appeared on 1.0.3.1 wallet when user tried to send stealth to basecoin (he had stealth on balance). Wallet restart also didn't help. PC restart solved the issue.

First one - 1.0.3
Second - 1.0.3.1

First one - Win 10 64 bit
Second - Win 7 64 bit

![IMG_20190709_220607_168](https://user-images.githubusercontent.com/47253342/61085011-ec87f380-a437-11e9-8ae0-f5bb60627f4c.jpg)
![IMG_20190709_220446_149](https://user-images.githubusercontent.com/47253342/61085012-ec87f380-a437-11e9-9ac0-8233d37ee64c.jpg)
![IMG_20190709_215830_781](https://user-images.githubusercontent.com/47253342/61085013-ed208a00-a437-11e9-8775-46e01508fe3c.jpg)
![IMG_20190709_212229_037](https://user-images.githubusercontent.com/47253342/61085014-ed208a00-a437-11e9-9970-4d62a4c3bfc4.jpg)

**Comment by seanPhill** [comment]
Just had someone have the exact same problem, on wallet 1.0.4.1, and Windows 10, 64-bit.
A reboot of the PC fixed it.

**Comment by codeofalltrades** [comment]
Any reports of this recently? Can this be closed?

**Comment by mimirmim** [comment]
No updates or further reports. Closing.
