### ISSUE TITLE
Feature Request: Stealth address support in listunspent RPC

### ISSUE THREAD

**Issue by JSKitty** [Veil-Project/veil#646]
Currently, `listunspent` displays unspent outputs for both Mining addresses and Basecoin addresses. This can easily be tested by generating a new wallet, sending a single transaction to it, and using `listunspent`.

This works perfectly for Basecoins, however, Stealth addresses appear to be non-functional.
If you generate a new wallet, a new stealth address, and send a transaction to that stealth address. `listunspent` seems to consistently return a *mining address* for them.

This makes it impossible for an RPC-based application (E.g: Exchange, Payment Processor, Financial Backends), to track Stealth deposits, as the actual address the coins were sent to, is entirely different to what it displays.

For example, you send 1 Veil to `sv1------------------`, you type `listunspent`, and you can see a single-Veil input. But the address of that input is a `V-------------------` address, completely different from the actual `sv1--------------` address it was sent to.

The main reason this is a problem~ Is applications that rely on `listunspent` to detect incoming transactions (Deposits) to services, may not be able to detect Stealth deposits, forcing them to use Basecoin, unless they can find an additional method of tracking funds. This will render `listunspent` useless after the swap to full-time RingCT.

**Comment by 4x13** [comment]
@blondfrogs This one should be a priority along with your RCT Mining

**Comment by CaveSpectre11** [comment]
This should be fixed with https://github.com/Veil-Project/veil/pull/696.  closing.

**Comment by CaveSpectre11** [comment]
confirmed fixed with #696
