### ISSUE TITLE
Cannot connect to peers

### ISSUE THREAD

**Issue by lbphp** [Veil-Project/veil#647]
Wallet is stuck while connecting to peers.
I have tried launching it with -resync 

I've also run clearbanned from the console, and it printed "null".

It was ineffective

**Comment by Kholdheart** [comment]
Same issue here. Was almost finished syncing then peers disappeared. :(

Any help would be greatly appreciated!

**Comment by Veil-Grumpy** [comment]
Have you tried this?


Close wallet, delete everything besides wallet.dat, wallets, backups, veil.conf
Start wallet and let it find peers and catch up some blocks
Close wallet and replace blockchain with snapshot and start wallet

**Comment by Kholdheart** [comment]
Snapshot worked. Thanks Grumpy.

**Comment by Veil-Grumpy** [comment]
Please close this issue

**Comment by codeofalltrades** [comment]
Closing per @Veil-Grumpy. 
Used snapshot.
