### ISSUE TITLE
Where are the linux Veil wallet installation instructions?

### ISSUE THREAD

**Issue by PoLabs** [Veil-Project/veil#648]
Is there no linux install instructions what-so-ever? Nothing on the readme or in the release notes. Just a tar.gz download? Nothing on the website either

so far I tried the veil-1.0.3 download and
`
./autogen.sh`

which built something

**Comment by HORT-VEIL** [comment]
[Compile Linux Veil Wallet from Source.docx](https://github.com/Veil-Project/veil/files/3453224/Compile.Linux.Veil.Wallet.from.Source.docx)
This should work for you.

**Comment by Veil-Grumpy** [comment]
Here you can find as well how to build Linux:
https://github.com/Veil-Project/veil/blob/master/doc/build-unix.md

**Comment by 4x13** [comment]
Not really the correct place. If you have further issues, please come and visit us on Discord.. :)
