### ISSUE TITLE
Staking wallet starts constantly draining one CPU core at some point of running.

### ISSUE THREAD

**Issue by vereten** [Veil-Project/veil#655]
Staking wallet starts constantly draining one CPU core at some point of running.

To reproduce the issue:
Run wallet, enable staking, precompute and wait few days.

Im not sure if non-staking wallet is affected. Ony way to stop CPU draining is to restart veil wallet. Trying to disable precomputing or staking on running wallet does not help and veil wallets keeps draining one CPU core. For me to hit issue takes 1-9 days.

Tried on precompiled wallet from github v1.0.3.1, also self-compiled wallet v1.0.3.1 from source from github on Ubuntu 18.04.3 LTS uptodate.

![002](https://user-images.githubusercontent.com/11050858/63209310-65393a00-c0df-11e9-96cc-419c23d22fa5.png)
![001](https://user-images.githubusercontent.com/11050858/63209311-65d1d080-c0df-11e9-8e6f-62bf8d8e53ac.png)

**Comment by codeofalltrades** [comment]
@vereten Is this still occurring?

**Comment by vereten** [comment]
> @vereten Is this still occurring?

@codeofalltrades Im not sure, i did script which restarts wallet in regular intervals.

**Comment by CaveSpectre11** [comment]
Closing.  Been running for months with staking
