### ISSUE TITLE
wallet 1.0.4 wont syn.

### ISSUE THREAD

**Issue by mreash16** [Veil-Project/veil#658]
I downloaded the newest version of the wallet yesterday and everything worked well but today the wallet will not syn. its been sitting at 99.85% for hours now.
![veil](https://user-images.githubusercontent.com/47542027/63536917-97350c80-c4e2-11e9-89fe-bd7551d912ec.PNG)

**Comment by Veil-Grumpy** [comment]
Have you tried this?
https://veil.freshdesk.com/support/solutions/articles/43000479941-wallet-syncing-is-stuck-on-a-block

Otherwise you might want to try to use a snapshot:
https://veil.freshdesk.com/support/solutions/articles/43000478708-how-to-use-a-snapshot

-Grumpy

**Comment by mreash16** [comment]
Thank you, it worked! but now I'm having the same issue with 1.0.4.4 and your fix wont work on that wallet, the wallet is stuck on block 355978

**Comment by Veil-Grumpy** [comment]
This one is for 1.0.4.4
https://veil.freshdesk.com/support/solutions/articles/43000530941-how-to-sync-wallet-v1-0-4-4

**Comment by codeofalltrades** [comment]
@Veil-Grumpy assuming this can be closed? Snapshot is the fix?

**Comment by mreash16** [comment]
yes it can be closed
thanks for your help!
 
 
 
-----Original Message-----

**Comment by codeofalltrades** [comment]
Resolved. Used snapshot.
