### ISSUE TITLE
Set unlimited wallet unlock from cli unlocktime to 0

### ISSUE THREAD

**Issue by Veil-Grumpy** [Veil-Project/veil#659]
Instead of using 99999, it's much easier to set it to 0 for unlimited time.

From example:
walletpassphrase YOURWALLETPASSWORD true/false 999999

to example:
walletpassphrase YOURWALLETPASSWORD false 0

**Comment by seanPhill** [comment]
Maybe a minimum time of 60 or 30 seconds? Gotta work fast to do something in less seconds than that. Zero seconds is pretty short. ;)

**Comment by Veil-Grumpy** [comment]
I mean instead of having to type 9999999 just a 0 would do the same trick.
