### ISSUE TITLE
Cannot see transaction list at all, in the Windows x64 version

### ISSUE THREAD

**Issue by ianGre** [Veil-Project/veil#66]
My Windows 64-bit (testnet-2 d5cbc6b) wallet is synced, it seems, for some hours, but the transaction list is still not showing. Just the "Time to transfer some Veil to your wallet" screen, but there is a balance showing (from a previous mining session). 

**Maybe** this problem will go away when we are sure we are synced to at least two peers?

**Comment by ianGre** [comment]
Transaction list is showing only AFTER shutting the wallet down and starting it up again.

![veil-with-tx-list-20181229](https://user-images.githubusercontent.com/36124423/50530153-17bb8d00-0b4f-11e9-8d3c-2182f056be38.png)

Maybe please look into why the transaction list was missing, and then why it required a wallet restart to display it.

**Comment by 4x13** [comment]
I would guess it was due to the wallet being not fully synced. this issue of getting stuck is fixed and will be released soon.

**Comment by ianGre** [comment]
Thanks.
