### ISSUE TITLE
Blank page in wallet on checking v1.0.4.7-007651e15 on Settings page.

### ISSUE THREAD

**Issue by seanPhill** [Veil-Project/veil#671]
When the Veil v1.0.4.7-007651e15 wallet is redisplayed (having been minimised for a while) and the settings page is already selected, the central (main content) section is completely blank.

To display the settings page it is necessary to firstly select "Overview", then re-select "Settings."

I am using MacOS 10.13.6 (High Sierra), NOT using Dark Mode.
The wallet was not self-compiled, so far as I can remember. 

I am using a Mac Pro with 32GB RAM and an SSD.

The previous behaviour, of display the content window should be maintained.

For comparison I am launching the Veil wallet (same version) on my iMac (8GB, HDD, same OS version) which has been turned off for a couple of days.
It opened up normally, and is showing the Syncing dialog, with the Overview screen visible behind it (non-transparent), just around the outside of the synchronising dialog.

I clicked "Hide" and the overview page shows as normal, and tapping the Settings page shows as it normally does. (I'll check back here when I get that wallet to be not seen for a while and then see if the central section is visible when I come back to it.)

**Comment by seanPhill** [comment]
Yes, I redisplayed the wallet from the Dock, where it had been minimised for only a minute (with the Settings screen active) and the central section was blank.

So far it has not happened when the Overview screen was selected when it was minimised (for a couple of minutes).

**Comment by seanPhill** [comment]
Even after a long time with the screen asleep and the wallet minimised it does not happen if you had the Overview screen selected when it was minimised, only with the Settings screen.
This only started with version 1.0.4.7. I would have noticed it earlier if it had been a present behaviour in 1.0.3.x.

**Comment by seanPhill** [comment]
It also happens even if not minimised, but out of focus.

**Comment by CaveSpectre11** [comment]
Fixed with PR #687
