### ISSUE TITLE
Bug? "vout" field is missing from non-standard transaction types.

### ISSUE THREAD

**Issue by mimirmim** [Veil-Project/veil#675]
The `vout` field is missing from all non-standard transaction types. It can easily be added by in and should be. Right now `gettxout` is useless on getting non-standard transaction data because it requires `vout` number.

I expected to be able to pull up `txout` out data from veil-cli or the console in the wallet.

The actual behavior is that I'm getting `Empty Result` errors for all non-basecoin transactions.

This currently is a part of all released version of Veil.

**Comment by CaveSpectre11** [comment]
Fixed with PR #868
