### ISSUE TITLE
Coin selection currency shows "BTC" instead of "Veil".

### ISSUE THREAD

**Issue by ianGre** [Veil-Project/veil#68]
In the Coin Selection window the totals are denominated in "BTC" instead of "Veil".
Veil Core version v0.0.9.9-d5cbc6b2f

Windows 64-bit wallet on Windows 10
![coinselection](https://user-images.githubusercontent.com/36124423/50530507-72a2b380-0b52-11e9-8901-88bada1c6248.png)

**Comment by veildev** [comment]
done, good catch.

**Comment by veildev** [comment]
` gui-fixes ` branch.
