### ISSUE TITLE
Send in GUI with EMPTY address field instant segfault crash

### ISSUE THREAD

**Issue by seanPhill** [Veil-Project/veil#684]
If you put an amount in the GUI Send page and hit the Send button (without also putting an address in the Address field it instantly crashes.
(I did not notice this before, because 99.99% of the time I use the Debug Console.)

I expected it to check that a required field has been filled (with an appropriate content type) and to move the cursor there, and display a red box around it, with a message saying that "an amount is required".

Instant crash.
[In the Terminal window]
$ ./veil-qt -testnet
PublicCoin::validate value is not prime
Segmentation fault: 11

[In the Apple Problem Report dialog]
Process:               veil-qt [3317]
Path:                  /Applications/Veil-newTestnet4-pr680/*/veil-qt
Identifier:            veil-qt
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        bash [3309]
Responsible:           veil-qt [3317]
User ID:               501

Date/Time:             2019-11-09 17:44:04.465 -0500
OS Version:            Mac OS X 10.13.6 (17G9016)
Report Version:        12
Anonymous UUID:        98807FAC-5A43-94B1-AF1F-9E55DC64D4BA

Time Awake Since Boot: 160000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

Tested multiple times between the reporting user and mine, resulting in 100% the same result.

A recent master (end user on testnet) and the testnet PR (mine).

Windows 10 (end user) MacOS 10.13.6 (mine) iMac, i7 cpu, 8 GB RAM, HDD.

**Comment by MatWaller** [comment]
Does not occur on Ubuntu

```
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
```

Booting into Windows now and checking there.

**Comment by seanPhill** [comment]
Great to hear!
