### ISSUE TITLE
"View explorer" tool tip is floating on Mac running in dark mode.

### ISSUE THREAD

**Issue by ncrypter90** [Veil-Project/veil#685]
The floating tool tip "view explorer" in transaction details odd.

Reproduce:
Goto Transactions -> select a transaction -> Transaction details -> hover over "eye" symbol on the top right corner.

Screen shot:

![Screen Shot 2019-11-11 at 9 19 52 pm](https://user-images.githubusercontent.com/49970996/68847395-ba0e4000-0722-11ea-8469-38e74143f37a.png)

**Comment by codeofalltrades** [comment]
Similar to #63
