### ISSUE TITLE
1.0.4.7 crash on start up, but working fine on 1.0.4.5

### ISSUE THREAD

**Issue by seanPhill** [Veil-Project/veil#690]
Shortly after upgrading to 1.0.4.7 on mainnet I got start up crashes that remained consistent on repeated attempts. Starting with 1.0.4.5 started successfully.
After running 1.0.4.5 reliably for more than a month I got a crash in that, involving something that was fixed in the later version. I restarted in 1.0.4.5 on a second attempt with no problem. (I don't want to confuse the issue by giving _that_ error message in the debug.)

So I decided to try the later version again, and I immediately got those same start up crashes, which did not disappear after several repeated attempts. Going back to the older version eliminated the errors. Error details follow.

Running the CLI version in Ubuntu 18.04, SSD, 8GB RAM.

Extracted from debug.log (with timestamps removed): 

```No coin database inconsistencies in last 6 blocks (14 transactions)
 block index            8464ms
Opening LevelDB in /home/user/.veil/indexes/txindex
Opened LevelDB successfully
Using obfuscation key for /home/user/.veil/indexes/txindex: 0000000000000000
init message: Loading wallet...
txindex thread start
Syncing txindex with block chain from height 451118
[default wallet] nFileVersion = 1000407
[default wallet] Keys: 0 plaintext, 4396 encrypted, 4396 w/ metadata, 4396 total. Unknown wallet records: 3401
[default wallet] Wallet completed loading in              72ms
ERROR: NewStealthKey Wallet must be unlocked to derive hardened keys.


************************
EXCEPTION: St12out_of_range       
map::at       
veil in AppInit()       

Shutdown: In progress...
```

**Comment by seanPhill** [comment]
So far as I'm aware from other peoples' experiences, going back to 1.0.4.6 would have been just as successful.

**Comment by seanPhill** [comment]
In case this was a wallet.dat issue, I later was able to upgrade to 1.0.4.8 by creating a fresh seed wallet and spending into that.

**Comment by CaveSpectre11** [comment]
OBE
