### ISSUE TITLE
Chain tips database should clean out orphans from time to time

### ISSUE THREAD

**Issue by mimirmim** [Veil-Project/veil#693]
Chain tips database fills up with many chain tips over time and the only solution I know of right now is restarting the client every once in a while. There should be functionality added to clean it up every once in a bit. Preferably, after blocks become stored permanently in the blockchain.

I'm opening up the dialogue to discuss potential solutions as it is a waste of space currently as those chain tips are stale.

**Comment by CaveSpectre11** [comment]
Addressed with #727
