### ISSUE TITLE
Wallet segfaults when clicking Send without inputs

### ISSUE THREAD

**Issue by crypt0-fusi0n** [Veil-Project/veil#697]
**Describe the issue**
Wallet segfaults if you click on the Send button in send dialog without any inputs.

**What behavior did you expect?**
A prompt asking me to input the address and amount

**What was the actual behavior (provide screenshots if the issue is GUI-related)?**
![segfault](https://user-images.githubusercontent.com/48879483/69910119-2e9ee980-145a-11ea-83be-6ad60dc4a6f7.gif)

**How reliably can you reproduce the issue, what are the steps to do so?**

1. Open wallet
2. Go to Send tab
3. Click **Send** without any inputs

**What version of the Veil client are you using, where did you get it (website, self-compiled, etc)?**
1.0.4.7 (website) and current master (self-compiled)

**This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.**
Backtrace here [2019.12.01 - Segfault on Send.txt](https://github.com/Veil-Project/veil/files/3907861/2019.12.01.-.Segfault.on.Send.txt)

**Comment by codeofalltrades** [comment]
Similar to #684

**Comment by sinetek** [comment]
Managed to reproduce this on v1.0.4.7. but not on master compiled locally.

I suggest if this is an issue we might have to bump the Qt version in our builds.

**Comment by sinetek** [comment]
v1.0.4.8 also affected.
