### ISSUE TITLE
Coin selection sum of coins and calculation of fee is not working (in Win64 at least)

### ISSUE THREAD

**Issue by ianGre** [Veil-Project/veil#70]
Coin selection allows you to select a coin, and if the amount is not enough after the fee it warns you (when you try to send the payment), _but_ in the Coin Selection screen, no amounts get put into the totals at the top, (which also needs "BTC" to be edited to "Veil".

Secondly, no fee amount is calculated, so you have to grab a calculator and work out how much you have to send in order to cover the fee also.

**Comment by presstab** [comment]
This was commented out for some reason when a lot of code was merged together. We are working on a fix for this.

**Comment by ianGre** [comment]
![screen shot 2018-12-29 at 11 45 26 am](https://user-images.githubusercontent.com/36124423/50544583-816e9080-0c4e-11e9-9074-6e8b08409340.png)
Here is where I was told about the fee 0.3720 VEIL, but when the tx processed the actual fee was much smaller and I got some change! (See issue regarding transaction details.)

**Comment by 4x13** [comment]
Moved to a new issue
