### ISSUE TITLE
Software Versioning issue in Releases.

### ISSUE THREAD

**Issue by sinetek** [Veil-Project/veil#709]
This one is trivial.
We might want to rename the releases to specify the build version.

![image](https://user-images.githubusercontent.com/5908875/70923811-cb4fb280-2028-11ea-8a6b-a63123f6c708.png)

1.0.4 -> 1.0.4.7

**Comment by codeofalltrades** [comment]
Agreed. Gitian it the problem from my understanding.

**Comment by mimirmim** [comment]
The problem is that we have x.x.x.x, not x.x.x, this was discussed in dev chat already where we remarked that we will be going to sane semantic versioning from 2.0.
