### ISSUE TITLE
Unlock wallet for staking/fully unlock wallet

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#71]
NOTE this issue is from test binary version of wallet and may not reflect current code
### Describe the issue
The wallet in options gives 'invalid password' on 'unlock for staking' but switched toggle anyway. The 'fully unlock' below it doesn't require/doesn't ask for a password at all.
### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
Run wallet. Enter Settings. interact with unlock wallet options.

### Expected behavior
Unlock wallet for staking should ask for wallet password, and accept the correct password. An incorrect password should be denied, leaving staking unlock disabled. Fully unlock wallet should ask for a password, and behave as above.'

### Actual behavior
Unlock for staking displays 'invalid password' message when correct password is entered, and slider changes state. Unlock fully changes state without a prompt for password at all.

### What version of Veil wallet are you using?
Testing binary builds Windows (64) and Linux (64)

**Comment by 4x13** [comment]
should be fixed tomorrow

**Comment by StrontiumZ38** [comment]
This problem has changed. It now accepts a valid password after encryption, but a failed or blank password will cause a crash on Windows.

**Comment by StrontiumZ38** [comment]
Looks to be fixed.
