### ISSUE TITLE
Assertion Failed! nThreadsServicingQueue == 0

### ISSUE THREAD

**Issue by Veil-Grumpy** [Veil-Project/veil#714]
![error1](https://user-images.githubusercontent.com/46780798/71017676-3798e780-20f7-11ea-957a-8b7f51d60073.png)
![error2](https://user-images.githubusercontent.com/46780798/71017677-3798e780-20f7-11ea-942c-bcb7c9d4cb40.png)

User Vonem_PL from Discord reporting this issue:

Error upon upgrading to newest version 1.0.4.8
When downgrade to 1.0.4.6 wallet is starting normally 

Windows 10

**Comment by mimirmim** [comment]
This is an usual error that requires discussion.

**Comment by MisterKangaroo** [comment]
Not sure if its related... 
i have also an Assertion error on linux (Ubuntu 18.04LTS) with the 1.0.4.8 wallet version.
Downgrade as a workaround fixes the issue... 
Here is the backtrace:

EXCEPTION: St12out_of_range       
map::at       
veil in Runaway exception       

[Thread 0x7ffff1d9e700 (LWP 18992) exited]
veil-qt: /home/ anonuserblackened/veil/depends/x86_64-pc-linux-gnu/share/../include/boost/thread/pthread/condition_variable_fwd.hpp:116: boost::condition_variable::~condition_variable(): Assertion `!ret' failed.

Thread 1 "veil-qt" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff5bc1801 in __GI_abort () at abort.c:79
#2  0x00007ffff5bb139a in __assert_fail_base (
    fmt=0x7ffff5d387d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x555557630b97 "!ret", 
    file=file@entry=0x555557630b20 "/home/ anonuserblackened/veil/depends/x86_64-pc-linux-gnu/share/../include/boost/thread/pthread/condition_variable_fwd.hpp", 
    line=line@entry=116, 
    function=function@entry=0x555557640860 <boost::condition_variable::~condition_variable()::__PRETTY_FUNCTION__> "boost::condition_variable::~condition_variable()") at assert.c:92
#3  0x00007ffff5bb1412 in __GI___assert_fail (assertion=0x555557630b97 "!ret", 
    file=0x555557630b20 "/home/ anonuserblackened/veil/depends/x86_64-pc-linux-gnu/share/../include/boost/thread/pthread/condition_variable_fwd.hpp", line=116, 
    function=0x555557640860 <boost::condition_variable::~condition_variable()::__PRETTY_FUNCTION__> "boost::condition_variable::~condition_variable()")
    at assert.c:101
#4  0x00005555558d5bae in boost::condition_variable::~condition_variable() ()
#5  0x0000555555aa12c5 in CCheckQueue<CScriptCheck>::~CCheckQueue() ()
#6  0x00007ffff5bc4041 in __run_exit_handlers (status=1, 
    listp=0x7ffff5f6c718 <__exit_funcs>, 
    run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true)
    at exit.c:108
---Type <return> to continue, or q <return> to quit---
#7  0x00007ffff5bc413a in __GI_exit (status=<optimized out>) at exit.c:139
#8  0x0000555555754a7e in BitcoinApplication::handleRunawayException(QString const&) ()
#9  0x000055555658e702 in QObject::event(QEvent*) ()
#10 0x00005555560965a4 in QGuiApplication::event(QEvent*) ()
#11 0x00005555568a466f in QApplication::event(QEvent*) ()
#12 0x000055555689eb7c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    ()
#13 0x00005555568a61cf in QApplication::notify(QObject*, QEvent*) ()
#14 0x000055555655b558 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    ()
#15 0x000055555655e50d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
#16 0x00005555565b3fa4 in QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#17 0x000055555605f53d in QUnixEventDispatcherQPA::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#18 0x000055555655933f in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
#19 0x0000555556562f68 in QCoreApplication::exec() ()
#20 0x000055555572bc6b in main ()

**Comment by seanPhill** [comment]
For what it's worth. I had trouble with 1.0.4.8 crashing 100% of the time (which was worked around by going back to 1.0.4.6), *until* I created a fresh seed wallet in 1.0.4.8 and transferred everything into it. I never had any trouble with 1.0.4.8 after that.

**Comment by seanPhill** [comment]
There have been some PRs such as #962 since this issue that have addressed "assertion" crashes. short of any recent clear example I think this can be closed.

(Cleaning up)
