### ISSUE TITLE
Wallet encrypted / wrong password

### ISSUE THREAD

**Issue by MisterKangaroo** [Veil-Project/veil#72]
After encrypting the wallet it restarted...
decrypt the wallet shows the error screen (screenshot).
No typo possible... copy pasted password.

Win10 x64
Latest binaries (testnet3)

![copypaste pw](https://user-images.githubusercontent.com/43561981/50533743-e338d880-0b30-11e9-8033-8a7259038827.PNG)

**Comment by veildev** [comment]
this is not GUI. @4x13

**Comment by presstab** [comment]
#93
