### ISSUE TITLE
 Get rid of precompute.

### ISSUE THREAD

**Issue by sinetek** [Veil-Project/veil#724]
#723 

This is to get the ball rolling on removing all precompute related bits, which if I understand correctly has been disabled already.

Q: should we also get rid of the precompute DB? Is it necessary for correct operation of the client?

**Comment by codeofalltrades** [comment]
> Q: should we also get rid of the precompute DB? Is it necessary for correct operation of the client?
Yes I think the DB should be removed also. 
Precompute was added as a feature a few months after the Jan 2019 launch.

**Comment by sinetek** [comment]
Done. Removed useless RPC commands. Removed precompute DB.
Please go over `CWallet::MintToTxIn` with a very fine comb.

**Comment by sinetek** [comment]
I think it works, I could mint coins successfully here.

**Comment by CaveSpectre11** [comment]
#723 merged
