### ISSUE TITLE
Fix Mint Zerocoin UI Text size

### ISSUE THREAD

**Issue by crypt0-fusi0n** [Veil-Project/veil#738]
### Issue
The "minimum" display on the 'Zerocoin minting' page takes away from the real estate for the Mint Zerocoin Veil details:

![image](https://user-images.githubusercontent.com/48879483/72212416-c1d63f00-352f-11ea-9b4e-e54aed53c7ef.png)

This display comes up when there is less than 10 basecoins in the wallet.  The display when there is enough is still slightly chopped in the display box (near the bottom)

![image](https://user-images.githubusercontent.com/48879483/72212415-ac611500-352f-11ea-90e3-f1a4e2fbc0bc.png)

(note the 'g' and 'y' in the last line.

**Comment by CaveSpectre11** [comment]
Bounty: 300
Assigned to @MatWaller

**Comment by CaveSpectre11** [comment]
bounty assigned: @PeterL73
