### ISSUE TITLE
Current branches crashes quickly on MacOS Catalina

### ISSUE THREAD

**Issue by mylof** [Veil-Project/veil#745]
Immediate crash upon running code built on `master` or `1.1.0` branch. 
Please fix so I can run code compiled from source on MacOS

This is a lldb trace

Process 70240 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10000)
    frame #0: 0x0000000100fa5d8e libdb_cxx-4.8.dylib`__lock_get_lk_max_locks + 53
libdb_cxx-4.8.dylib`__lock_get_lk_max_locks:
->  0x100fa5d8e <+53>: movl   %eax, (%rsi)
    0x100fa5d90 <+55>: xorl   %eax, %eax
    0x100fa5d92 <+57>: popq   %rbp
    0x100fa5d93 <+58>: retq
Target 0: (veild) stopped.

**Comment by seanPhill** [comment]
I've had good success running the MacOS binaries coming from Github Actions, which we started using long after you posted this.
I too was unable to compile on Catalina, but I could compile on High Sierra, no problem.
