### ISSUE TITLE
MacOS Catalina 10.15.3 dark mode seed phrase white on white

### ISSUE THREAD

**Issue by seanPhill** [Veil-Project/veil#747]
I thought this had already been addressed by ignoring dark mode in Mojave and therefore Catalina, but the seed words were white on light grey when reading them, which was hard enough to read, but to type them back they are white on white.

A workaround can be to select the typed word to give it a blue background while selected.

However, it does not seem to want to allow me to select the Apple menu to get to preferences while this wallet setup is currently displayed, so I can't turn off dark mode at this moment.

**Comment by seanPhill** [comment]
I just found another workaround!
Just type it blind. If incorrect the underline will be red. :)

**Comment by sinetek** [comment]
Assigning @mimirmim our mac-head.  thanks for reporting!

**Comment by codeofalltrades** [comment]
What wallet version?

**Comment by seanPhill** [comment]
1.1.0 devnet. Not that I can see it as the white text is in all sorts of other parts of the wallet too.

**Comment by seanPhill** [comment]
At least now I can get to preferences to turn off Dark Mode until this is fixed.

**Comment by sinetek** [comment]
![image](https://user-images.githubusercontent.com/5908875/74033940-8a847200-49b7-11ea-993b-4c6e9edf133c.png)
We have two choices here:
* Disable the dark mode.
* Write new styles and switch according to the running theme.

In the interest of simplicity I propose we go with the first option.

**Comment by seanPhill** [comment]
PR767 has tested fine on Catalina.
