### ISSUE TITLE
ISSUE_TEMPLATE.md please update for VEIL and change the Stack Exchange and security issue reporting link.

### ISSUE THREAD

**Issue by ianGre** [Veil-Project/veil#75]
This issue tracker is only for technical issues related to **Bitcoin Core**.

General bitcoin questions and/or support requests are best directed to the **Bitcoin StackExchange** at https://**bitcoin.stackexchange.com**.

For reporting security issues, please read instructions at https://**bitcoincore.org/en/contact/**.

If the node is "stuck" during sync or giving "block checksum mismatch" errors, please ensure your hardware is stable by running memtest and observe CPU temperature with a load-test tool such as linpack before creating an issue!

Describe the issue
What behavior did you expect?

What was the actual behavior (provide screenshots if the issue is GUI-related)?

How reliably can you reproduce the issue, what are the steps to do so?

What version of **Bitcoin** Core are you using, where did you get it (website, self-compiled, etc)?

**Comment by 4x13** [comment]
fixed

**Comment by ianGre** [comment]
Thanks, but I forgot to highlight one of the Bitcoin words.

General **bitcoin** questions and/or support requests are best directed to the Discord https://discord.gg/A3u524
