### ISSUE TITLE
Add an RPC method to determine all RingCT addresses in the wallet

### ISSUE THREAD

**Issue by gabrielnergaard** [Veil-Project/veil#772]
It seems that in the current Qt wallet `listreceivedbyaddress` only returns basecoin addresses. We would need a method to retrieve all RingCT addresses as well.

**Comment by sinetek** [comment]
Will look into this.

**Comment by sinetek** [comment]
![image](https://user-images.githubusercontent.com/5908875/81105742-aa72f580-8f14-11ea-993b-2d6cf5953bc4.png)

**Comment by seanPhill** [comment]
(Cleaning up)
This issue was addressed in #842 and other shortcomings at the time of this issue (mentioned in #863) were also addressed in #911.
