### ISSUE TITLE
addnode in veil.conf not adding peers

### ISSUE THREAD

**Issue by ianGre** [Veil-Project/veil#81]
When starting fresh build and with an empty Veil data folder, except for the veil.conf file with addnodes in it, I got no connections. 

I had to add the nodes in the Debug Console.

Did I just not wait long enough?

**Comment by MisterKangaroo** [comment]
same for me (win10 x64)

**Comment by presstab** [comment]
This is default behaviour from bitcoin. Not totally sure the correct formatting at the moment, but look at your debug.log right when you startup:
`2018-12-29T18:48:29Z Warning: Config setting for -addnode only applied on test network when in [test] section.`

**Comment by ianGre** [comment]
I have tested this and it works! :)
testnet=1

[test]
addnode=...
