### ISSUE TITLE
Coin control unselect all - fatal error

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#813]
Win64 1.0.4.8

Using the (un)select all button in Coin control resulted in a fatal error, forced shutdown of wallet application, and a subsequent corruption calling for snapshot.

**Comment by CaveSpectre11** [comment]
Please test with the latest wallet; this is likely a duplicate of #660 or #661 and fixed with #757 

You can find the latest wallet here:
https://github.com/Veil-Project/veil/actions/runs/187835942

**Comment by StrontiumZ38** [comment]
Cheers
