### ISSUE TITLE
Crash when inputting wrong password, miscellaneous issues with toggles

### ISSUE THREAD

**Issue by VeilDango** [Veil-Project/veil#83]
![Image](https://i.imgur.com/awgMjlu.png)

Trying to input wrong password at Settings icon>Unlock Wallet for Staking, I get a fatal error.

I can't input password by toggling on overview toggle. I have to go to Settings icon>Unlock Wallet for Staking.

I have to click the right side of the toggle to enable it, within about 40% of the toggle's total length from the right. If I click the left side or center of the toggle nothing happens.

**Comment by presstab** [comment]
#93

**Comment by VeilDango** [comment]
The pop-up says "Wallet not unlocked for staking" when I input wrong password. It should say:

Incorrect password

Or

Incorrect password. Wallet not unlocked

Or

Incorrect password. Wallet not unlocked for staking (good to differentiate if we're adding back in unlocking wallet fully)
