### ISSUE TITLE
Feature request: Encryption reminder

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#852]
Upon starting an unencrypted wallet, present a pop-up that reminds user to encrypt wallet for the safety of their funds.

**Comment by seanPhill** [comment]
Cleaning up old issues. This feature request is basically addressed in PR #900 as a suggested action to encrypt their wallet while waiting for initial sync. It doesn't nag them every time they start their wallet, though, and is not in a pop-up, but is on the overview page before funds are detected by the wallet. (Sorry it's not _exactly_ as requested, but I think it is close enough, and was done several months after this feature request.)
