### ISSUE TITLE
[Mining] Provide a way to mine to a specific wallet address

### ISSUE THREAD

**Issue by dragonmike** [Veil-Project/veil#867]
the parameter -miningaddress (tested in command line and as conf file entry) followed by a bv- or V- address does not force the wallet to mine randomX towards given address. The wallet still mines to a randomly generated mining address.

 the wallet should have mined towards the given address

 the wallet generated a new mining address and mined towards it, ignoring the set parameter

 tested several times, easy to reproduce

 v1.1.0 from github

 Windows 10, Ryzen 9 3900, Sandisk SSD

 n/a

 n/a

**Comment by CaveSpectre11** [comment]
To follow with a note on this:

`miningaddress` is used by progpow's `getblocktemplate` and is confusing as it is not originally intended to be a target for all mining payouts.  As that doesn't override the feature request intended here [for a use case that has a central management wallet with the private keys for a users distributed mining wallets], the feature is not without merit.  So the title will be renamed to be more in line with the feature.

**Comment by Zannick** [comment]
*Should* `miningaddress` be the address the wallet uses for in-wallet mining, or should we have separate options, e.g., `walletminingaddress` and `rpcminingaddress`?

**Comment by CaveSpectre11** [comment]
> _Should_ `miningaddress` be the address the wallet uses for in-wallet mining, or should we have separate options, e.g., `walletminingaddress` and `rpcminingaddress`?

I'm not a miner, so I'll leave that to those that are to answer the following question:  "What is the use case for two separate addresses?"

**Comment by Zannick** [comment]
The use case I was picturing was doing some local cpu mining plus the rpc mining, but I seem to have forgotten that you can't mine two different algorithms with one wallet. So, if it's acceptable to expand the usage of miningaddress for in-wallet mining, this ends up looking pretty simple.

**Comment by CaveSpectre11** [comment]
Bounty assigned: @Zannick

**Comment by Zannick** [comment]
Included in versions >= 1.2
