### ISSUE TITLE
Total Balance question mark is difficult to use

### ISSUE THREAD

**Issue by WetOne** [Veil-Project/veil#897]
The checkmark for total balance in the balance section of the UI does not properly respond to clicks.  Once it appears, it does not properly go away.

Referenced in discussion:
https://discord.com/channels/481997816982405130/566636115990151169/804968820811890688

**Comment by sinetek** [comment]
Yes I have hit that issue as well.

**Comment by seanPhill** [comment]
In cleaning up these issues I have confirmed that the current master does not have this problem, and the behaviour is as described in the commit merged #902 on March 17th, 2021.
