### ISSUE TITLE
Windows 10 NOTIFICATIONS say "(GUI node for Bitcoin)"

### ISSUE THREAD

**Issue by ianGre** [Veil-Project/veil#90]
Every time a stake (or any transaction) comes in
Windows 10 NOTIFICATIONS say "Veil Core (GUI node for Bitcoin)"

src/qt/res/bitcoin-qt-res.rc

```Lines 22, 23, 25, 28
            VALUE "CompanyName",        "Bitcoin"
            VALUE "FileDescription",    PACKAGE_NAME " (GUI node for Bitcoin)"
            VALUE "FileVersion",        VER_FILEVERSION_STR
            VALUE "InternalName",       "bitcoin-qt"
            VALUE "OriginalFilename",   "bitcoin-qt.exe"
```

**Comment by ianGre** [comment]
Still present in the current build testnet-9. 
Veil Core version v0.0.9.9-8a33e3978 (64-bit)

**Comment by MisterKangaroo** [comment]
solved for me in the testnet12 version:

![](https://cdn.discordapp.com/attachments/490677232352624652/529518469587271680/IMG_20190101_053656.jpg)

**Comment by ianGre** [comment]
Excellent!
