### ISSUE TITLE
Make automated rescanringctwallet and friendly message enabling exchanges to send to stealth without worrying recipients

### ISSUE THREAD

**Issue by seanPhill** [Veil-Project/veil#922]
Exchanges are only sending to basecoin. Users are worried when receiving stealth txs.

 
  Noobs need the process of confidently receiving stealth funds to be noob-friendly, even grandma, executive, or trainee / intern friendly.

  The Vinex exchange very early in Veil history tried sending withdrawals to SV addresses, but customers thought they only received a single Satoshi of Veil as their wallet was locked at the time. This lead Vinex to suspend withdrawals to stealth addresses due to support workload. 

 If the wallet is locked when processing the block containing the transaction, it will (in the recipient's wallet) have a placeholder value of one satoshi only. After unlocking it is necessary to `rescanringctwallet`. This needs to be automated if a received transaction has been detected, and a friendly message needs to be generated for the GUI QtWallet user and for RPC-using  exchanges alike. 

My write-up in Discord:

> The only exchange that did implement stealth withdrawals was Vinex, early on, but when people began receiving stealth transactions while their wallets were locked and therefore it just looked like they received a (placeholder amount of) 1 satoshi of Veil, support requests increased. It turns out that if your wallet is locked when you receive a stealth payment you have to unlock your wallet and do rescanringctwallet in the Debug Console (or the equivalent command in Terminal).
> 
> In the future, so that exchanges can send and receive stealth transactions I would like to see the wallet give a message like "You have received a payment. Please unlock your wallet so the amount can be decrypted." Then it should automatically rescanringctwallet, which only takes a few seconds in most cases. [There would be no need to add "stealth" to describe "a payment", because Veil transactions are normally stealth and eliminating basecoin transactions as a norm, such as from mining pools or to and from exchanges, will achieve this overwhelmingly.]

Much of this, I believe is already planned for the RingCT release, but I am posting this on the suggestion of a user, in relation at least to the friendly notification mentioned in the second paragraph. I don't see any specific related issues although I believe plans and intentions have been previously discussed. Please add any references if found.

**Comment by seanPhill** [comment]
The core wallet (GUI & CLI) **automatically doing `rescanringctwallet` after a spend or after getting unlocked is all the more necessary**, as I found while trying to spend a large wallet from the ringct balance.

**Every** spend left a detected balance that did not account for all of the spent utxos, and which was only corrected after the first confirmation, by doing `rescanringctwallet`. Failing to do this not only left the balance incorrect (too high), but also made any subsequent attempt to spend fail until rescanning the ringct wallet.

A subsequent test by a spending script did a hundred successful spends by `sendringcttoringct`, pause 600 seconds, do the `rescanringctwallet`, pause ten seconds, check and record the balance and block height and hash), and then do the next spend.

**Comment by seanPhill** [comment]
![Screen Shot 2022-02-02 at 12 15 55 pm](https://user-images.githubusercontent.com/46495592/152206713-7498606e-cd6e-4837-afde-e7e3e13ce42f.png)
FYI, here's what it looks like if your wallet is not unlocked when you receive RingCT funds. Those were actually incoming 50K transfers. Veil needs the keys to read stealth amounts properly, because **it's private.**
(By the way, these are only transfers between an old wallet and a replacement wallet.)

**Comment by Zannick** [comment]
> **Every** spend left a detected balance that did not account for all of the spent utxos, and which was only corrected after the first confirmation, by doing `rescanringctwallet`. 

Is this a new bug in the latest release? I remember trying to clean up some ringct-related things while working on multitx, and that included fixing something odd as far as I recall. If so let's file a separate issue to track it.

**Comment by seanPhill** [comment]
Just checking, the sending wallet was on Ubuntu 20.04.3 LTS running build (v1.2.2.99-g4df3a3435e356d1b7f2f7cbf024c81aa4c50145f (64-bit)), 

the receiving wallet was on macOS Monterey 12.0.1 running build (v1.2.2.99-g4879d2cd85a8533914d59939c3b6ca9a2600e934 (64-bit) ... checked, this is still running on PR984, not sure if your ringct work was active in that, sorry.

The other sending wallet was on macOS Catalina 10.15.7 running the new release, 1.2.3.1-f4c915222 (64-bit).

Regarding the specific thing you quoted, yes, this was happening on both of the sending wallets.

I'll create a separate issue for it.

**Comment by seanPhill** [comment]
> the PRs I'm referencing were not in the 1.2.3.1 release

Are these PRs in the current master at present? I think the others reporting this _may be_ using the lastest master, but I can't be sure. I can test again.

**Comment by us77ipis** [comment]
Yes it was using the latest `master`.

**Comment by us77ipis** [comment]
Probably the following should be implemented:
1. When wallet is unlocked auto `rescanringctwallet`
2. `rescanringctwallet` must update the transaction history too.
3. I would also prefer to see in the transaction history something like `unknown` instead of a `-0.00000002`. Maybe with a question mark on the side that when you hover shows a message "Please unlock wallet first" or something like that.

**Comment by us77ipis** [comment]
I have not tested it yet but I think this commit https://github.com/Veil-Project/veil/commit/96877a883d37d72fe360e3cb8fd0a081b31dba6b is related to the bug, which commented out the line https://github.com/Veil-Project/veil/blob/7c8bee132ea6305b29a613679b7591a27d8edbd8/src/veil/ringct/anonwallet.cpp#L5622 which causes `SetValue(0)` not being called anymore in https://github.com/Veil-Project/veil/blob/7c8bee132ea6305b29a613679b7591a27d8edbd8/src/veil/ringct/anonwallet.cpp#L5212

Was there any substantial reason to comment that out, or was that change accidentally commited maybe after debugging?

**Comment by us77ipis** [comment]
Another thing that looks strange to my eyes is that there are two functions `AnonWallet::ProcessLockedBlindedOutputs()` and `AnonWallet::ProcessLockedStealthOutputs()` which are unused?

**Comment by seanPhill** [comment]
> 2\. `rescanringctwallet` must update the transaction history too.

As I had recently remembered seeing the history update after running `rescanringctwallet` I've just run a test, to be sure.

Current release wallet v1.2.3.1, receiving (on testnet) stealth amounts from another wallet.
Starting the wallet, it needs to sync. Once it opens up it has a series of 0.00000001 amounts received. Unlocked and ran `rescanringctwallet`, but as yet, the old (recent) transactions are not updated yet.
STOPPED the wallet, and restart. My wallet is pretty big, so it actually took 45 minutes to fully load, after which, all the previously 0.00000001 Veil received amounts *were corrected*, but of course, more had come in, which only showed one satoshi, as the wallet starts up locked. Unlocked and ran `rescanringctwallet` again, which would correct the actual balance, and I can be reasonably certain that the amounts in the transactions list will be correct on the next restart again.

Regardless of restarting, after `rescanringctwallet` any transactions and balances freshly queried in the CLI or Debug Console show the correct amounts.

**Comment by us77ipis** [comment]
> Once it opens up it has a series of 0.00000001 amounts received

I'm pretty sure those amounts come from the default value of `COutputRecord::nValue` which is -1 and is nowhere overwritten when a blinded output is received while the wallet is locked. https://github.com/Veil-Project/veil/blob/7c8bee132ea6305b29a613679b7591a27d8edbd8/src/veil/ringct/outputrecord.h#L43

And thus depending on how many outputs there are in the transaction, when summing up it is -0.00000001, -0.00000002, -0.00000003, etc.

**Comment by us77ipis** [comment]
> 3. I would also prefer to see in the transaction history something like `unknown` instead of a -0.00000002

As for solving this, the case can be detected in the UI by uncommenting the line I already referenced above: https://github.com/Veil-Project/veil/blob/7c8bee132ea6305b29a613679b7591a27d8edbd8/src/veil/ringct/anonwallet.cpp#L5622

Then the UI can check the presence of the `ORF_LOCKED` flag to determine whether to show `"unknown"` or the amount from the output records.

**Comment by us77ipis** [comment]
I have also noticed that currently if the transaction has a change, then even after `rescanringctwallet` and restarting of the wallet, there's still a 0.00000001 missing in the transaction of the GUI transaction history, which is the default value -1 of this change output which doesn't belong to the wallet.
@seanPhill does this also happen to you?

**Comment by us77ipis** [comment]
> I have also noticed that currently if the transaction has a change, then even after `rescanringctwallet` and restarting of the wallet, there's still a 0.00000001 missing in the transaction of the GUI transaction history, which is the default value -1 of this change output which doesn't belong to the wallet.

This is caused by lines https://github.com/Veil-Project/veil/blob/7c8bee132ea6305b29a613679b7591a27d8edbd8/src/qt/transactionrecord.cpp#L68 and https://github.com/Veil-Project/veil/blob/7c8bee132ea6305b29a613679b7591a27d8edbd8/src/qt/transactionrecord.cpp#L70 which should be `r.nFlags` instead of `nFlags`.

**Comment by us77ipis** [comment]
Is there any special reason for the default value of -1, or can this safely be changed to 0? https://github.com/Veil-Project/veil/blob/7c8bee132ea6305b29a613679b7591a27d8edbd8/src/veil/ringct/outputrecord.h#L43
