### ISSUE TITLE
Change automint default to off

### ISSUE THREAD

**Issue by seanPhill** [Veil-Project/veil#943]
Although changing the default automint denomination from ten to 1000, in the v1.2.x upgrade was good, the fact that the wallet "strongly" recommends against minting from basecoin to zerocoin suggests that autominting zerocoins at all should not be the default.

While `automintoff=1` solves this in the veil.conf file, including such a veil.conf file in the release would be bad as many people would already have their preferred settings in their conf file.

Can we please change the default internally in the code?

**Comment by ohcee** [comment]
https://github.com/Veil-Project/veil/pull/1028#issue-1675413390 should fix and close this if merged.

**Comment by seanPhill** [comment]
This works well! Tested with veil.conf as
`automintoff=1` still not autominting
`automintoff=0` it automints perfectly
`# automintoff=0` commented out, therefore using default, ... not autominting. Success.

There are more enhancements I want, but they belong in a new issue.
Here's a preview of what I have in mind, but **this** PR is ready to commit.
![Zerocoin Minting Page proposed enhancements](https://user-images.githubusercontent.com/46495592/235545495-fd25736b-4536-4502-a2fa-d1c16072b823.png)

**Comment by seanPhill** [comment]
I should have commented this on the PR itself, not just in the issue. I'll add it there.

**Comment by seanPhill** [comment]
Completed with PR #1028
