### ISSUE TITLE
Some items in the FAQs menu have content cut off prematurely

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#97]
### Describe the issue
Some items in the FAQs menu have content cut off prematurely.

#### Can you recreate the problem
Yes
#### If so, please list the steps to reproduce below:
Run wallet. Enter Settings. Open FAQ OR alternatively click 'Learn more about Veil' from main page.

### Expected behavior
Each menu item should bring up the appropriate page and conclude the contents found on said page's .ui or .cpp file.

### Actual behavior
Some items cut off content prematurely and leave parts of the source out.
![image](https://user-images.githubusercontent.com/38264865/50545366-fcd34080-0c54-11e9-93c3-2c482a8e6788.png)

### What version of Veil wallet are you using?
Testing binary builds Windows (64)

**Comment by 4x13** [comment]
fixed, ty Random.. :)
