### ISSUE TITLE
coins disappeared after upgrading to latest version 1.2.2.1

### ISSUE THREAD

**Issue by ncrypter90** [Veil-Project/veil#983]
@seanPhill I have updagraded my wallter to Version 1.2.2.1. Also downloaded latest snapshot,once wallet fully synced all the coins i had disappeared. Can you please help me restore?

I tried deleting old fils and started with new snapshot but no luck.

**Comment by seanPhill** [comment]
Hi! As this is a support issue can we follow this up either on Discord or Freshdesk? Obviously this issue should not have occurred and I don't know what happened to your wallet.dat in the upgrade, and it should involve some of the rescan commands, and if you restored from seed words, you would need to lock the wallet if the previous wallet was locked, before completing the recovery procedures. --> https://veil.freshdesk.com/support/home where you will also find relevant guides.

**Comment by Zannick** [comment]
It's relevant what version you upgraded from, as 1.2.1.1 was a mandatory upgrade to avoid a fork. If you were on the forked chain, any transactions after the fork are invalid.

**Comment by ncrypter90** [comment]
I had updated from 1.1 and also,
here is the things happens chronological order:
When i upgraded to 1.2.1 then i could see all the coins and wallet had synced and i turned on stake.
then wallet went into hung state then after an hour i had to kill the application and start again.
when restarted it then i could see 80% less coins. and synced then turned on stake which went into hung state then restarted after 3 hours or so.
When restarted it could see less than 10%. then i copied the whole wallet along with snapshot to different computer there when it tried to open the wallet it say wallet.dat is invalid then i restored old wallet.dat file but after the restore I could see no coins at all. 
But same time i have wallet running on old computer where it is still showing 10% of the coins which I had since 3 years.

No idea whats happening. is there any I can restore all?

**Comment by seanPhill** [comment]
I want to ask too many questions to be in Github. One of the other support options from my previous message?

**Comment by ncrypter90** [comment]
I tried below page, i got some coins back(5% of total coins lost) and also on another computer it says double the amount with same procedure. 
https://veil.freshdesk.com/support/solutions/articles/43000468391-missing-veil


I will connect with you on discord.
