### ISSUE TITLE
Add stratum connection and cli option

### ISSUE THREAD

**Issue by b8engl** [Veil-Project/veil#999]
For the love of god, please add a proper node with a proper connection base on startum and only cli.
This GUI thing is slow!

**Comment by b8engl** [comment]
That's slow also. Plus, why wallet GUI must be opened, why not use all in one cli node

**Comment by us77ipis** [comment]
You do not have to open the GUI, you can use the cli.

**Comment by b8engl** [comment]
Please elaborate, which *.exe and what arguments to use

**Comment by b8engl** [comment]
And why the external python implementation...

**Comment by b8engl** [comment]
why ask randomx and progpow in the same request

**Comment by b8engl** [comment]
thisn is really a mess, I'm out!
